---
title: 'DCATS: Differential composition analysis tweaked with similarity in single-cell
  RNA-seq data'
author: "Xinyi Lin"
date: "1/20/2021"
output:
  slidy_presentation: default
  powerpoint_presentation: default
  beamer_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Main Goal

Differential Abundance Analysis

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(MCMCpack)
library(pROC)
```

```{r}
source("functionsV2.r")
```

```{r}
theme_set(theme_minimal())
```

```{r}
cluster_num = 3  # numbers of clusters
concentration = 50 # indicate how simulated proportion far away from true, the larger the closer
rep1 = 6
rep2 = 4
simulation_times = 50
simulation_size = 50
sample_size1 = 1000
sample_size2 = 2000
```

```{r}
## more negative
if (cluster_num == 3){
  probC1 = c(1/3, 1/3, 1/3)  # True proportions
  probC2 = c(1/3, 1/2, 1/6)
  truthRes = c("N", "P", "P")
} else if (cluster_num == 7){
  probC1 = c(rep(0.1, 4), rep(0.2, 3))
  probC2 = c(0.1, 0.1, 0.1, 0.15, 0.2, 0.3, 0.05)
  truthRes = c("N", "N", "N", "P", "N", "P", "P")
} else if (cluster_num == 12) {
  probC1 = c(rep(0.1, 4), rep(0.2, 2), rep(0.05, 2), rep(0.025, 4))
  probC2 = c(0.1, 0.1, 0.1, 0.1, 0.2, 0.15, 0.05, 0.075, 0.05, 0.025, 0.025, 0.025)
  truthRes = c("N", "N", "N", "N", "N", "P", "N", "P", "P", "N", "N", "N")
}
```

```{r}
set.seed(123)
simil_mat = matrix(c(1, 0, 0, 0, 0.8, 0.3, 0, 0.2, 0.7), ncol = 3)
## Data generation part
totals1 = ceiling(runif(rep1, sample_size1, sample_size2))
totals2 = ceiling(runif(rep2, sample_size1, sample_size2))
diri_s1 = probC1 * concentration
diri_s2 = probC2 * concentration
sim_dat <- DCATS::simulator_base(totals1, totals2, diri_s1, diri_s2, simil_mat)
numb_cond1 = as.matrix(sim_dat$numb_cond1)
numb_cond2 = as.matrix(sim_dat$numb_cond2)
```

```{r}
## plots for lab meeting
colnames(numb_cond1) = c("A", "B", "C")
cond1DF = numb_cond1[1:4,] %>% as.data.frame() %>% 
  rownames_to_column("rep") %>% 
  mutate(rep = str_c("rep", rep),
         cond = "cond1",
         sum = A + B + C,
         A = A/sum,
         B = B/sum,
         C = C/sum) %>% 
  pivot_longer(A:C, names_to = "cluster", values_to = "prop")

colnames(numb_cond2) = c("A", "B", "C")
cond2DF = numb_cond2 %>% as.data.frame() %>% 
  rownames_to_column("rep") %>% 
  mutate(rep = str_c("rep", rep),
         cond = "cond2",
         sum = A + B + C,
         A = A/sum,
         B = B/sum,
         C = C/sum) %>% 
  pivot_longer(A:C, names_to = "cluster", values_to = "prop")

condDF = rbind(cond1DF, cond2DF)
```

```{r}
condDF %>% 
  ggplot(aes(x = rep, y = prop, fill = cluster))+
  geom_bar(stat="identity") + 
  coord_flip() + 
  facet_grid(. ~ cond)
```


