---
title: "Figure1 Draft"
output: html_document
---

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(MCMCpack)
library(pROC)
```

```{r}
source("functionsV2.r")
```

```{r}
theme_set(theme_minimal())
```

Fig 1 (theoretical simulation might be enough): the usefulness of using similarity matrix to correct the bias;

Draw a boxplot to show AUC results of DCATS, chi-square, scDC(, fisher) without BC, with BC and with BC using resampling.

```{r}
cluster_num = 9  # numbers of clusters
concentration = 70 # indicate how simulated proportion far away from true, the larger the closer
rep1 = 2
rep2 = 3
simulation_times = 50
simulation_size = 50
sample_size1 = 1000
sample_size2 = 2000
```

```{r}
probC1 = c(rep(0.1, 8), 0.2)  # True proportions
probC2 = c(rep(0.1, 7), 0.15, 0.15)
truthRes = c(rep("N", 7), "P", "P")
```

```{r}
## more negative
if (cluster_num == 3){
  probC1 = c(1/3, 1/3, 1/3)  # True proportions
  probC2 = c(1/3, 1/2, 1/6)
  truthRes = c("N", "P", "P")
} else if (cluster_num == 7){
  probC1 = c(rep(0.1, 4), rep(0.2, 3))
  probC2 = c(0.1, 0.1, 0.1, 0.15, 0.2, 0.3, 0.05)
  truthRes = c("N", "N", "N", "P", "N", "P", "P")
} else if (cluster_num == 12) {
  probC1 = c(rep(0.1, 4), rep(0.2, 2), rep(0.05, 2), rep(0.025, 4))
  probC2 = c(0.1, 0.1, 0.1, 0.1, 0.2, 0.15, 0.05, 0.075, 0.05, 0.025, 0.025, 0.025)
  truthRes = c("N", "N", "N", "N", "N", "P", "N", "P", "P", "N", "N", "N")
}
```

```{r}
set.seed(123)
simulationDF_list = vector(mode = "list", length = simulation_times)
for (j in 1:simulation_times) {
  simulationDF = data.frame()
  for (i in 1:simulation_size){
    ## create confusion matrix that is not uniformly distributed
    simil_mat = get_similarity_mat(cluster_num, confuse_rate=0)
    ##simil_mat = matrix(c(1, 0, 0, 0, 0.6, 0.4, 0, 0.4, 0.6), ncol = 3)
    if (FALSE){
      mis_idx = runif(1, -0.2, 0.2)
      change_rate = simil_mat[1,1]*abs(mis_idx)
      if (mis_idx < 0){
        simil_mat[1,1] = simil_mat[1,1] - change_rate
        simil_mat[1,3] = simil_mat[1,3] + change_rate
        } else {
          simil_mat[3,1] = simil_mat[1,1] - change_rate
          simil_mat[3,3] = simil_mat[1,3] + change_rate 
        }
      }
    
    ## Data generation part
    totals1 = ceiling(runif(rep1, sample_size1, sample_size2))
    totals2 = ceiling(runif(rep2, sample_size1, sample_size2))
    diri_s1 = probC1 * concentration
    diri_s2 = probC2 * concentration
    sim_dat <- DCATS::simulator_base(totals1, totals2, diri_s1, diri_s2, simil_mat)
    numb_cond1 = as.matrix(sim_dat$numb_cond1)
    numb_cond2 = as.matrix(sim_dat$numb_cond2)
    
    ## Test part 1
    ### DCATS
    dcats_res1 = betabinLRT_rw(numb_cond1, numb_cond2, bias_corr = FALSE)
    ### fisher
    fisher_pvals1 = getFisher(numb_cond1, numb_cond2)
    
    ## Bias Correction
    numb_cond1BC = numb_cond1
    numb_cond2BC = numb_cond2
    for (i in seq_len(nrow(numb_cond1))) {
      numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) *
        multinom_EM(numb_cond1[i, ], simil_mat, verbose = FALSE)$mu
      numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])
      }
    for (i in seq_len(nrow(numb_cond2))) {
      numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) *
        multinom_EM(numb_cond2[i, ], simil_mat, verbose = FALSE)$mu
      numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])
    }
  
    ## Test part 2
    ### DCATS
    dcats_res2 = betabinLRT_rw(numb_cond1BC, numb_cond2BC, bias_corr = FALSE)
    ### fisher
    fisher_pvals2 = getFisher(numb_cond1BC, numb_cond2BC)
  
    all_res = data.frame(cluster = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L")[1:cluster_num], truth = truthRes) %>% 
      mutate(dcats_noBC = dcats_res1$pvals,
            fisher_noBC = fisher_pvals1,
            dcats_withBC = dcats_res2$pvals,
            fisher_withBC = fisher_pvals2)

    simulationDF = rbind(simulationDF, all_res)
    }
  simulationDF_list[[j]] = simulationDF
}

#file_name = str_c("./data/simulationRES/repplicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_countSim.RData")
#save(simulationDF_list, file = file_name)

## send email after finishing
sendEmail("Simulation is done!!")
```

```{r, eval=FALSE}
## plots for lab meeting
colnames(numb_cond1) = c("A", "B", "C", "D", "E", "F", "G",)
cond1DF = numb_cond1[1:4,] %>% as.data.frame() %>% 
  rownames_to_column("rep") %>% 
  mutate(rep = str_c("rep", rep),
         cond = "cond1",
         sum = A + B + C,
         A = A/sum,
         B = B/sum,
         C = C/sum) %>% 
  pivot_longer(A:C, names_to = "cluster", values_to = "prop")

colnames(numb_cond2) = c("A", "B", "C")
cond2DF = numb_cond2 %>% as.data.frame() %>% 
  rownames_to_column("rep") %>% 
  mutate(rep = str_c("rep", rep),
         cond = "cond2",
         sum = A + B + C,
         A = A/sum,
         B = B/sum,
         C = C/sum) %>% 
  pivot_longer(A:C, names_to = "cluster", values_to = "prop")

condDF = rbind(cond1DF, cond2DF)
```

```{r}
LM_plot1 = condDF %>% 
  ggplot(aes(x = rep, y = prop, fill = cluster))+
  geom_bar(stat="identity") + 
  coord_flip() + 
  facet_grid(. ~ cond)
ggsave("LM_plot1.png", plot = LM_plot1)
```

```{r}

```


```{r, eval=FALSE}
load(file_name)
simulationDF_list[[1]] %>% 
  pivot_longer(dcats_noBC:fisher_withBC,
    names_to = "statistics", 
    values_to = "pvals") %>% 
  ggplot(aes(x = statistics, y = pvals)) +
  geom_boxplot()
```

Calculate PPV NPV TNR F1 Power FOR FNR FPR FDR AUC

```{r}
evaluationDF = data.frame()
len = length(simulationDF_list)
for (j in 1:len){
  simulationDF = simulationDF_list[[j]] %>% 
  mutate(dcats_tf1 = ifelse(dcats_noBC < 0.05, "P", "N"),
         fisher_tf1 = ifelse(fisher_noBC < 0.05, "P", "N"),
         dcats_tf2 = ifelse(dcats_withBC < 0.05, "P", "N"),
         fisher_tf2 = ifelse(fisher_withBC < 0.05, "P", "N"))
  methods = colnames(simulationDF)[3:6]
  numb_mthd = length(methods)
  mcc = rep(NA, numb_mthd)
  auc = rep(NA, numb_mthd)
  recall = rep(NA, numb_mthd)
  FNR = rep(NA, numb_mthd)
  FPR = rep(NA, numb_mthd)
  specificity = rep(NA, numb_mthd)
  precision = rep(NA, numb_mthd)
  FDR = rep(NA, numb_mthd)
  FOR = rep(NA, numb_mthd)
  NPV = rep(NA, numb_mthd)
  accuracy = rep(NA, numb_mthd)
  F1 = rep(NA, numb_mthd)
  for (i in 3:6){
    auc[i-2] = roc(simulationDF$truth, simulationDF[,i])$auc
    truth = simulationDF$truth
    pred = simulationDF[, i+4]
    confu_mtr = table(pred, truth)
    TN = 0
    FN = 0
    FP = 0
    TP = 0
    if(dim(confu_mtr)[1] == 2){
      TN = confu_mtr[1,1] 
      FN = confu_mtr[1,2]
      FP = confu_mtr[2,1]
      TP = confu_mtr[2,2]
    } else {
      if (unique(pred) == "N"){
        TN = confu_mtr[1,1] 
        FN = confu_mtr[1,2]
      } else {
          FP = confu_mtr[1,1]
          TP = confu_mtr[1,2]
        }
    }
    truthN = TN + FP
    truthP = FN + TP
    predP = TP + FP
    predN = FN + TN
    mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
    recall[i-2] = TP/truthP
    FNR[i-2] = FN/truthP
    FPR[i-2] = FP/truthN
    specificity[i-2] = TN/truthN
    precision[i-2] = TP/predP
    FDR[i-2] = FP/predP
    FOR[i-2] = FN/predN
    NPV[i-2] = TN/predN
    accuracy[i-2] = (TP+TN)/(truthP+truthN)
    F1[i-2] = 2*TP/(2*TP+FP+FN)
      
  res = data.frame(trial = as.character(j), methods = methods, mcc = mcc, auc = auc, recall = recall, FNR = FNR, FPR = FPR, specificity = specificity, precision = precision, FDR = FDR, FOR = FOR, NPV = NPV, accuracy = accuracy, F1 = F1)
    }
    evaluationDF = rbind(evaluationDF, res)
}

evaluationDF %>% 
  tidyr::separate(methods, c("method", "condition"), sep = "_") %>% 
  pivot_longer(
    mcc:F1,
    names_to = "statistics", 
    values_to = "value") %>% 
  mutate(statistics = as.factor(statistics),
         statistics = fct_relevel(statistics, "mcc", "auc", "recall", "specificity", "precision", "NPV", "accuracy", "F1")) %>% 
  ggplot(aes(x = statistics, y = value, color = method)) + geom_boxplot() + facet_grid(.~condition) +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 45))
```

```{r}
aucDF = evaluationDF %>% 
  dplyr::select(trial, methods, auc) %>% 
  pivot_wider(names_from = methods, values_from = auc)

summary(aucDF$dcats_noBC)
summary(aucDF$fisher_noBC)
summary(aucDF$dcats_withBC)
summary(aucDF$fisher_withBC)
```

```{r}
mccDF = evaluationDF %>% 
  dplyr::select(trial, methods, mcc) %>% 
  pivot_wider(names_from = methods, values_from = mcc)

summary(mccDF$dcats_noBC)
summary(mccDF$fisher_noBC)
summary(mccDF$dcats_withBC)
summary(mccDF$fisher_withBC)
```

## figure 1 version 1

```{r}
source("functionsV2.r")
```

```{r}
cluster_num = 3  # numbers of clusters
concentration = 50 # indicate how simulated proportion far away from true, the larger the closer
rep1 = 6
rep2 = 4
simulation_times = 50
simulation_size = 50
sample_size1 = 1000
sample_size2 = 2000
simil_mat = matrix(c(1, 0, 0, 0, 0.8, 0.3, 0, 0.2, 0.7), ncol = 3)
```

```{r}
## more negative
if (cluster_num == 3){
  probC1 = c(1/3, 1/3, 1/3)  # True proportions
  probC2 = c(1/3, 1/2, 1/6)
  truthRes = c("N", "P", "P")
} else if (cluster_num == 7){
  probC1 = c(rep(0.1, 4), rep(0.2, 3))
  probC2 = c(0.1, 0.1, 0.1, 0.15, 0.2, 0.3, 0.05)
  truthRes = c("N", "N", "N", "P", "N", "P", "P")
} else if (cluster_num == 12) {
  probC1 = c(rep(0.1, 4), rep(0.2, 2), rep(0.05, 2), rep(0.025, 4))
  probC2 = c(0.1, 0.1, 0.1, 0.1, 0.2, 0.15, 0.05, 0.075, 0.05, 0.025, 0.025, 0.025)
  truthRes = c("N", "N", "N", "N", "N", "P", "N", "P", "P", "N", "N", "N")
}
```

```{r}
set.seed(123)
simulationDF = data.frame()
for (i in 1:simulation_size){
  ## Data generation part
  totals1 = ceiling(runif(rep1, sample_size1, sample_size2))
  totals2 = ceiling(runif(rep2, sample_size1, sample_size2))
  diri_s1 = probC1 * concentration
  diri_s2 = probC2 * concentration
  sim_dat <- DCATS::simulator_base(totals1, totals2, diri_s1, diri_s2, simil_mat)
  numb_cond1 = as.matrix(sim_dat$numb_cond1)
  numb_cond2 = as.matrix(sim_dat$numb_cond2)
    
  ## Test part 1
  ### DCATS
  dcats_res1 = betabinLRT_rw(numb_cond1, numb_cond2, bias_corr = FALSE)
  ### fisher
  fisher_pvals1 = getFisher(numb_cond1, numb_cond2)
    
  ## Bias Correction
  numb_cond1BC = numb_cond1
  numb_cond2BC = numb_cond2
  for (i in seq_len(nrow(numb_cond1))) {
    numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) *
      multinom_EM(numb_cond1[i, ], simil_mat, verbose = FALSE)$mu
    numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])
    }
  for (i in seq_len(nrow(numb_cond2))) {
    numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) *
      multinom_EM(numb_cond2[i, ], simil_mat, verbose = FALSE)$mu
    numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])
    }
  
  ## Test part 2
  ### DCATS
  dcats_res2 = betabinLRT_rw(numb_cond1BC, numb_cond2BC, bias_corr = FALSE)
  ### fisher
  fisher_pvals2 = getFisher(numb_cond1BC, numb_cond2BC)
  
  all_res = data.frame(cluster = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L")[1:cluster_num], truth = truthRes) %>% 
    mutate(dcats_noBC = dcats_res1$pvals,
           fisher_noBC = fisher_pvals1,
           dcats_withBC = dcats_res2$pvals,
           fisher_withBC = fisher_pvals2)
  simulationDF = rbind(simulationDF, all_res)
  }
```