---
title: "Figure Draft - Three plots version"
author: "Xinyi Lin"
date: "1/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width=12, fig.height=7)
```

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(MCMCpack)
library(pROC)
library(patchwork)
library(ggpubr)
```

```{r}
source("functionsV2.r")
options(future.globals.maxSize = 20000 * 1024^2) # 20G memory
```

```{r}
theme_set(theme_classic()+
            theme(panel.border = element_blank(),
          legend.key = element_blank(),
          axis.ticks = element_blank(),
          panel.grid = element_blank(),
          panel.grid.minor = element_blank(), 
          panel.grid.major = element_blank(),
          panel.background = element_blank(),
          legend.background = element_blank(),
          plot.background = element_rect(fill = "transparent",colour = NA)) + 
            theme(axis.text=element_text(size=12), axis.title=element_text(size=13))+
            theme(legend.title = element_text(size=13), #change legend title font size
                  legend.text = element_text(size=10)))
```

## Figure 1

The Distribution of cell pool

```{r}
load("D:/Data/DCATS/cells_pool8_splatter.RData")
```

```{r}
seuratObj <- CreateSeuratObject(counts = sim_mat, project="Splatter")
seuratObj <- NormalizeData(seuratObj, verbose = FALSE)
seuratObj <- FindVariableFeatures(seuratObj, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
seuratObj <- ScaleData(seuratObj)
seuratObj <- RunPCA(seuratObj, features = VariableFeatures(object = seuratObj))
seuratObj <- FindNeighbors(seuratObj, dims = 1:30, verbose = FALSE)
seuratObj <- FindClusters(seuratObj, resolution = 0.5, verbose = FALSE)
seuratObj <- RunUMAP(seuratObj, dims = 1:30, verbose = FALSE)
seuratObj[['orig.ident']] <- origLabels
DimPlot(seuratObj, reduction = "umap")
p1 = DimPlot(seuratObj, reduction = "umap", group.by = "orig.ident") + theme(legend.position="none") + ggtitle("Cell Pools (8 Cell Types)")
```

```{r}
load("D:/Data/DCATS/cells_pool10_splatter.RData")
```

```{r}
seuratObj <- CreateSeuratObject(counts = sim_mat, project="Splatter")
seuratObj <- NormalizeData(seuratObj, verbose = FALSE)
seuratObj <- FindVariableFeatures(seuratObj, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
seuratObj <- ScaleData(seuratObj)
seuratObj <- RunPCA(seuratObj, features = VariableFeatures(object = seuratObj))
seuratObj <- FindNeighbors(seuratObj, dims = 1:30, verbose = FALSE)
seuratObj <- FindClusters(seuratObj, resolution = 0.5, verbose = FALSE)
seuratObj <- RunUMAP(seuratObj, dims = 1:30, verbose = FALSE)
seuratObj[['orig.ident']] <- origLabels
DimPlot(seuratObj, reduction = "umap")
p2 = DimPlot(seuratObj, reduction = "umap", group.by = "orig.ident") + theme(legend.position="none", axis.title.y = element_blank())  + ggtitle("Cell Pools (10 Cell Types)")
```

```{r}
load("D:/Data/DCATS/cells_pool12_splatter.RData")
```

```{r}
seuratObj <- CreateSeuratObject(counts = sim_mat, project="Splatter")
seuratObj <- NormalizeData(seuratObj, verbose = FALSE)
seuratObj <- FindVariableFeatures(seuratObj, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
seuratObj <- ScaleData(seuratObj)
seuratObj <- RunPCA(seuratObj, features = VariableFeatures(object = seuratObj))
seuratObj <- FindNeighbors(seuratObj, dims = 1:30, verbose = FALSE)
seuratObj <- FindClusters(seuratObj, resolution = 0.5, verbose = FALSE)
seuratObj <- RunUMAP(seuratObj, dims = 1:30, verbose = FALSE)
seuratObj[['orig.ident']] <- origLabels
DimPlot(seuratObj, reduction = "umap")
p3 = DimPlot(seuratObj, reduction = "umap", group.by = "orig.ident") + theme(legend.position="none", axis.title.y = element_blank()) + ggtitle("Cell Pools (12 Cell Types)")
```

```{r}
p1 + p2 + p3
ggsave("./plot/sim2_cellpool.png", bg = "transparent", width = 10, height = 4)
```

## Figure 2

### Figure 2-A

```{r}
load("D:/Data/DCATS/simulation/toy_simulation.RData")
evaluationDF = data.frame()
len = length(simulationDF_list)
#for (j in 1:8){
for (j in 1:len){
  simulationDF = simulationDF_list[[j]] %>% na.omit()
  method = colnames(simulationDF)[3:dim(simulationDF)[2]]
  numb_mthd = length(method)
  sensitivity = rep(NA, numb_mthd)
  specificity = rep(NA, numb_mthd)
  mcc = rep(NA, numb_mthd)
  auc = rep(NA, numb_mthd)
  prauc = rep(NA, numb_mthd)
  F1 = rep(NA, numb_mthd)
  
  truth = simulationDF$truth
  for (i in 3:dim(simulationDF)[2]){
    pred = simulationDF[, i]
    pred_res = ifelse(pred < 0.05, "P", "N")
    TP <- sum(pred_res=="P"&truth=="P")
    TN <- sum(pred_res=="N"&truth=="N")
    FP <- sum(pred_res=="P"&truth=="N")
    FN <- sum(pred_res=="N"&truth=="P")
    truthN = TN + FP
    truthP = FN + TP
    predP = TP + FP
    predN = FN + TN
    sensitivity[i-2] = TP/truthP
    specificity[i-2] = TN/truthN
    mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
    auc[i-2] = getROC(truth, pred)$auc
    prauc[i-2] = getPRC(truth, pred)$prauc
    F1 = 2*TP/(2*TP+FP+FN)
    
    res = data.frame(trial = as.character(j), method = method, sensitivity = sensitivity, specificity = specificity, mcc = mcc, auc = auc, prauc = prauc, F1 = F1)
    }
    evaluationDF = rbind(evaluationDF, res)
}
```

```{r}
sim1_main = evaluationDF %>% 
  tidyr::separate(method, c("method", "condition"), sep = "_") %>% 
  dplyr::select(-sensitivity, -specificity) %>% 
  filter(condition != "test") %>% 
  filter(method %in% c("estPhi", "fisher")) %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method),
         method = ifelse(method == "estPhi", "DCATS", method)) %>% 
  ggplot(aes(x = condition, y = auc, color = method)) + geom_boxplot() +
  scale_color_manual(values=c("#F8766D", "#00BFC4")) +
  theme(axis.title.x = element_blank()) + 
  ylab("AUC") +
  scale_x_discrete(labels=c("null" = "no Bias Correction", "withBC" = "with Bias Correction")) 
sim1_main
ggsave("./plot/sim1_main.png", bg = "transparent")
```

Simulation 1: Supplementary Plots

```{r}
evaluationDF %>% 
  tidyr::separate(method, c("method", "condition"), sep = "_") %>% 
  dplyr::select(-sensitivity, -specificity) %>% 
  filter(condition != "test") %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method),
         method = factor(method, levels = c("wtoPhi", "adjPhi", "avrgPhi", "estPhi", "Fisher"))) %>% 
  ggplot(aes(x = condition, y = auc, color = method)) + geom_boxplot() +
  theme(axis.title.x = element_blank()) + 
  ylab("AUC") +
  scale_x_discrete(labels=c("null" = "no Bias Correction", "withBC" = "with Bias Correction"))
ggsave("./plot/sim1_allAUC.png", bg = "transparent")
```

```{r}
evaluationDF %>% 
  tidyr::separate(method, c("method", "condition"), sep = "_") %>% 
  filter(condition != "test") %>% 
  dplyr::select(-auc, -prauc) %>% 
  pivot_longer(
    sensitivity:mcc,
    names_to = "statistics", 
    values_to = "value") %>% 
  mutate(condition = ifelse(condition == "null", "noBC", condition)) %>%
  ggplot(aes(x = condition, y = value, color = method)) + geom_boxplot() + facet_grid(.~statistics) +
  ylab("Value") +
    theme(axis.title.x = element_blank())
ggsave("./plot/sim1_statistics.png", bg = "transparent")
```

```{r}
supA1 = phiDF %>% 
  ggplot(aes(x = eachPhi1, y = estPhi1)) +
  geom_point(aes(col = cluster), size = 0.5) + 
  theme(legend.position = "none") +
  xlab("eachPhi (no BC)") +
  ylab("estPhi (no BC)")
supA2 = phiDF %>% 
  ggplot(aes(x = eachPhi2, y = estPhi2)) +
  geom_point(aes(col = cluster), size = 0.5) +
  theme(legend.position = "none") +
  xlab("eachPhi (with BC)") +
  ylab("estPhi (with BC)")
supA3 = phiDF %>% 
  ggplot(aes(x = eachPhi1, y = eachPhi2)) +
  geom_point(aes(col = cluster), size = 0.5) +
  theme(legend.position = "none") +
  xlab("eachPhi (no BC)") +
  ylab("eachPhi (with BC)")
supA4 = phiDF %>% 
  ggplot(aes(x = estPhi1, y = estPhi2)) +
  geom_point(aes(col = cluster), size = 0.5) +
  theme(legend.position = "bottom") +
  xlab("estPhi (no BC)") +
  ylab("estPhi (with BC)")
(supA1 + supA2)/(supA3 + supA4)
ggsave("./plot/sim1_phi.png", bg = "transparent", width = 8, height = 5)
```

### Figure 2-B

#### Different numbers of replicates

```{r}
## cluster number = 8
filenames = list.files("D:/Data/DCATS/simulation/replicates", full.names = TRUE)
#filenames = filenames[grep("_K8_con100_splatter3000&3000", filenames)]
filenames
```

```{r}
res_all = data.frame()

for (file in filenames) {
  load(file)
  methods = colnames(oper[[1]]$clusterDF)[colnames(oper[[1]]$clusterDF) %>% str_detect("_pvals")] %>% str_remove("_pvals")
  methods = c(methods, "milo")
  numb_mthd = length(methods)
  mcc = rep(NA, numb_mthd)
  auc = rep(NA, numb_mthd)
  prauc = rep(NA, numb_mthd)
  sensitivity = rep(NA, numb_mthd)
  specificity = rep(NA, numb_mthd)
  precision = rep(NA, numb_mthd)
  F1 = rep(NA, numb_mthd)
  clusterRes = data.frame()
  nhoodRes = data.frame()
  for (idx in 1:length(oper)){
    if (!is.na(oper[[idx]])) {clusterRes = rbind(clusterRes, oper[[idx]]$clusterDF)}
    if (!is.na(oper[[idx]])) {nhoodRes = rbind(nhoodRes, oper[[idx]]$nhoodDF)}
    }
  truth = clusterRes$truth
  clusterRes = clusterRes %>% 
    mutate(milo_main = ifelse(milo_less > milo_more, milo_less, milo_more),
           milo_pct = milo_main/(milo_less + neutral + milo_more),
           milo_diff = abs(milo_less - milo_more)) %>% 
    dplyr::select(-milo_less, -milo_more, - neutral, -milo_main)
  for (i in 3:(dim(clusterRes)[2]-1)){
    pred = clusterRes[,i]
    if (colnames(clusterRes)[i] == "milo_pct") {
      pred_res = ifelse(clusterRes$milo_diff > 0, "P", "N")
      auc[i-2] = getROC(clusterRes$truth, 1-pred)$auc
      prauc[i-2] = getPRC(clusterRes$truth, 1-pred)$prauc}
    else {
      pred_res = ifelse(pred < 0.1, "P", "N")
      auc[i-2] = getROC(clusterRes$truth, pred)$auc
      prauc[i-2] = getPRC(clusterRes$truth, pred)$prauc}
    TP <- sum(pred_res=="P"&truth=="P")
    TN <- sum(pred_res=="N"&truth=="N")
    FP <- sum(pred_res=="P"&truth=="N")
    FN <- sum(pred_res=="N"&truth=="P")
    truthN = TN + FP
    truthP = FN + TP
    predP = TP + FP
    predN = FN + TN
    sensitivity[i-2] = TP/truthP
    specificity[i-2] = TN/truthN
    precision[i-2] = TP/predP
    #mcc[i-2] = sqrt(sensitivity[i]*specificity[i]*precision[i]*(TN/(TN+FN))) - sqrt((1-sensitivity[i])*(1-specificity[i])*(FN/predN)*(FP/predP))
    mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
    F1[i-2] = 2*TP/(2*TP+FP+FN)
    }
  res = data.frame(method = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision, F1 = F1) %>% 
    arrange(desc(prauc)) %>% 
    mutate(replicates = str_extract(file, "\\d&\\d"))
  res_all = rbind(res_all, res)
  }

res_all %>% 
  filter(method %in% c("estPhi_null", "estPhi_emK", "fisher", "speckle", "diffcyt", "betabin_null", "wtoPhi_emK", "scDC", "milo")) %>% 
  arrange(replicates, desc(prauc)) %>% 
  dplyr::select(method, mcc, auc, sensitivity, specificity, F1, replicates) %>% 
  mutate(mcc = round(mcc, 3),
         prauc = round(auc, 3),
         sensitivity = round(sensitivity, 3),
         specificity = round(specificity, 3),
         F1 = round(F1, 3))
```

```{r, warning=FALSE}
sim2_mainAUC1 = res_all %>% 
  filter(method %in% c("speckle", "diffcyt", "fisher", "scDC", "estPhi_emK", "milo")) %>%
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = ifelse(method == "estPhi_emK", "DCTAS", method)) %>% 
  mutate(method = factor(method, level = c("DCTAS", "speckle", "diffcyt", "Fisher", "milo", "scDC"))) %>% 
  ggplot(aes(x = replicates, y = auc, color = method, group = method)) + 
  geom_point(shape = 0) +
  geom_line()+
  xlab("# of Replicates") +
  theme(legend.position = "none") + 
  ylab("AUC")
sim2_mainAUC1
```

```{r, warning=FALSE}
sim2_mainMCC1 = res_all %>% 
  filter(method %in% c("speckle", "diffcyt", "fisher", "scDC", "estPhi_emK", "milo")) %>%
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = ifelse(method == "estPhi_emK", "DCTAS", method)) %>% 
  mutate(method = factor(method, level = c("DCTAS", "speckle", "diffcyt", "Fisher", "milo", "scDC"))) %>% 
  ggplot(aes(x = replicates, y = mcc, color = method, group = method)) + 
  geom_point(shape = 0) +
  geom_line()+
  xlab("# of Replicates") +
  theme(legend.position = "none") + 
  ylab("MCC")
sim2_mainMCC1
```

Simulation 2: Supplementary Plots

```{r}
p1 = res_all %>% 
  filter(method %in% c("scDC", "milo", "wtoPhi_emK", "betabin_null", "speckle", "diffcyt", "Fisher", "estPhi_emK", "estPhi_null")) %>%
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("milo", "scDC", "wtoPhi_emK", "betabin_null", "speckle", "diffcyt", "Fisher", "estPhi_emK", "estPhi_null"))) %>% 
  dplyr::select(method, auc, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = auc)) + 
    geom_text(aes(label = round(auc, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0.7,1)) +
  xlab("# of Replicates") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank())

nhoodsH1_mcc = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, mcc, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = mcc)) + 
    geom_text(aes(label = ifelse(is.na(mcc), "N.A.", as.character(round(mcc, 3))))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0,0.5)) +
  xlab("# of Replicates") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

nhoodsH1_sensitivity = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, sensitivity, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = sensitivity)) + 
    geom_text(aes(label = round(sensitivity, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0,0.6)) +
  xlab("# of Replicates")

nhoodsH1_specificity = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, specificity, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = specificity)) + 
    geom_text(aes(label = round(specificity, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0.8,1)) +
  xlab("# of Replicates") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank())

nhoodsH1_auc + nhoodsH1_mcc + nhoodsH1_sensitivity + nhoodsH1_specificity
ggsave("./plot/sim2_nhood1.png", bg = "transparent", width = 10, height = 6)
```

```{r}
res_all %>% 
  filter(method %in% c("scDC", "milo", "wtoPhi_emK", "betabin_null", "speckle", "diffcyt", "Fisher", "estPhi_emK", "estPhi_null")) %>%
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("scDC", "milo", "wtoPhi_emK", "betabin_null", "speckle", "diffcyt", "Fisher", "estPhi_emK", "estPhi_null"))) %>% 
  dplyr::select(method, auc, mcc, sensitivity, specificity, replicates) %>% 
  pivot_longer(auc:specificity, names_to = "statistics", values_to = "value") %>% 
  group_by(replicates, statistics) %>% 
  mutate(value_order = order(order(value))) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = value_order)) + 
    geom_text(aes(label = round(value, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(1,8)) +
  xlab("# of Replicates") +
  theme(axis.title.y = element_blank()) +
  facet_grid(.~statistics) + labs(fill='rank')
ggsave("./plot/sim2_statistics_replicates.png", bg = "transparent")
```

Details of statistics value

```{r}
res_all %>% 
  filter(method %in% c("speckle", "diffcyt", "fisher", "scDC", "betabin_null", "estPhi_null", "wtoPhi_emK", "estPhi_emK", "milo")) %>%
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("scDC", "milo", "wtoPhi_emK", "betabin_null", "speckle", "diffcyt", "Fisher", "estPhi_emK", "estPhi_null"))) %>% 
  mutate(mcc = round(mcc, 3),
         auc = round(auc, 3),
         sensitivity = round(sensitivity, 3),
         specificity = round(specificity, 3),
         F1 = round(F1, 3)) %>% 
  arrange(replicates, desc(auc)) %>% 
  knitr::kable()
```

nhoods level

```{r, eval=FALSE}
nhoodsRes_all = data.frame()

for (file in filenames) {
  load(file)
  nhoodRes = data.frame()
  for (idx in 1:length(oper)){
    if (!is.na(oper[[idx]])) {nhoodRes = rbind(nhoodRes, oper[[idx]]$nhoodDF)}
  }
  nhoodRes = nhoodRes %>% 
  dplyr::rename(milo_pvals = SpatialFDR) %>% 
  filter(ident_fraction > 0.8)  # get nhoods mainly contains one cell type -> 90%
  methods = colnames(nhoodRes)[colnames(nhoodRes) %>% str_detect("_pvals")] %>% str_remove("_pvals")
  numb_mthd = length(methods)
  mcc = rep(NA, numb_mthd)
  auc = rep(NA, numb_mthd)
  prauc = rep(NA, numb_mthd)
  sensitivity = rep(NA, numb_mthd)
  specificity = rep(NA, numb_mthd)
  precision = rep(NA, numb_mthd)
  F1 = rep(NA, numb_mthd)
  truth = nhoodRes$truth
  select_col = colnames(nhoodRes)[colnames(nhoodRes) %>% str_detect("_pvals")]
  for (i in 1:length(select_col)){
    pred = nhoodRes[,select_col[i]]
    auc[i] = getROC(truth[!is.na(pred)], pred[!is.na(pred)])$auc
    if (i == 1) {pred_res = ifelse(pred < 0.30, "P", "N")}
    else {pred_res = ifelse(pred < 0.10, "P", "N")}
    TP <- sum(pred_res[!is.na(pred_res)]=="P"&truth[!is.na(pred_res)]=="P")
    TN <- sum(pred_res[!is.na(pred_res)]=="N"&truth[!is.na(pred_res)]=="N")
    FP <- sum(pred_res[!is.na(pred_res)]=="P"&truth[!is.na(pred_res)]=="N")
    FN <- sum(pred_res[!is.na(pred_res)]=="N"&truth[!is.na(pred_res)]=="P")
    truthN = TN + FP
    truthP = FN + TP
    predP = TP + FP
    predN = FN + TN
    sensitivity[i] = TP/truthP
    specificity[i] = TN/truthN
    precision[i] = TP/predP
    mcc[i] = sqrt(sensitivity[i]*specificity[i]*precision[i]*(TN/(TN+FN))) - sqrt((1-sensitivity[i])*(1-specificity[i])*(FN/predN)*(FP/predP))
    #mcc[i] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
    F1[i] = 2*TP/(2*TP+FP+FN)
    prauc[i] = getPRC(truth[!is.na(pred)], pred[!is.na(pred)])$prauc
  }
  res = data.frame(method = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision, F1 = F1) %>% 
    arrange(desc(prauc)) %>% 
    mutate(replicates = str_extract(file, "\\d&\\d"))
  nhoodsRes_all = rbind(nhoodsRes_all, res)
}
save(nhoodsRes_all, file = "D:/Data/DCATS/simulation/nhoodsRes_all_replicates.RData")
```

```{r}
load("D:/Data/DCATS/simulation/nhoodsRes_all_replicates.RData")
nhoodsRes_all %>% 
  arrange(replicates, desc(auc)) %>% 
  dplyr::select(method, mcc, auc, sensitivity, specificity, F1, replicates) %>% 
  mutate(mcc = round(mcc, 3),
         prauc = round(auc, 3),
         sensitivity = round(sensitivity, 3),
         specificity = round(specificity, 3),
         F1 = round(F1, 3))
```

```{r}
nhoodsH1_auc = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, auc, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = auc)) + 
    geom_text(aes(label = round(auc, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0.6,0.8)) +
  xlab("# of Replicates") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank())

nhoodsH1_mcc = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, mcc, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = mcc)) + 
    geom_text(aes(label = ifelse(is.na(mcc), "N.A.", as.character(round(mcc, 3))))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0,0.5)) +
  xlab("# of Replicates") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

nhoodsH1_sensitivity = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, sensitivity, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = sensitivity)) + 
    geom_text(aes(label = round(sensitivity, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0,0.6)) +
  xlab("# of Replicates")

nhoodsH1_specificity = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, specificity, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = specificity)) + 
    geom_text(aes(label = round(specificity, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0.8,1)) +
  xlab("# of Replicates") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank())

nhoodsH1_precision = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, precision, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = precision)) + 
    geom_text(aes(label = round(precision, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0.7,1)) +
  xlab("# of Replicates") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank())

nhoodsH1_F1 = nhoodsRes_all %>% 
  mutate(method = ifelse(method == "fisher", "Fisher", method)) %>% 
  mutate(method = factor(method, level = c("speckle", "estPhi_emU", "estPhi_null", "wtoPhi_emU", "betabin_null", "milo", "Fisher"))) %>% 
  dplyr::select(method, F1, replicates) %>% 
  ggplot(aes(replicates, method)) +
    geom_tile(aes(fill = F1)) + 
    geom_text(aes(label = round(F1, 3))) +
    scale_fill_gradient(low = "white", high = "red", limits = c(0,0.7)) +
  xlab("# of Replicates") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank())

nhoodsH1_auc + nhoodsH1_mcc + nhoodsH1_F1 + nhoodsH1_sensitivity + nhoodsH1_specificity + nhoodsH1_precision
ggsave("./plot/sim2_nhood1.png", bg = "transparent", width = 10, height = 6)
```