---
title: "Figures Draft"
author: "Xinyi Lin"
date: "3/26/2021"
output: html_document
---

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(MCMCpack)
library(pROC)
```

```{r}
source("functionsV2.r")
options(future.globals.maxSize = 20000 * 1024^2) # 20G memory
```

```{r}
theme_set(theme_minimal())
```

```{r}
cluster_num = 3  # numbers of clusters
concentration = 70 # indicate how simulated proportion far away from true, the larger the closer
rep1 = 2
rep2 = 3
simulation_times = 50
simulation_size = 50
sample_size1 = 1000
sample_size2 = 2000
```

```{r}
probC1 = c(1/3, 1/3, 1/3)  # True proportions
probC2 = c(1/3, 1/2, 1/6)
truthRes = c("N", "P", "P")
```

## Figure A

```{r, warning=FALSE}
set.seed(123)
simulationDF = data.frame()
for (i in 1:simulation_size){
  ## create confusion matrix that is not uniformly distributed
  #simil_mat = get_similarity_mat(cluster_num, confuse_rate=0)
  simil_mat = matrix(c(1, 0, 0, 0, 0.7, 0.3, 0, 0.3, 0.7), ncol = 3)
  #simil_mat[5,5] = 0.6
  #simil_mat[5,3] = 0.4
  #simil_mat[3,5] = 0.4
  #simil_mat[3,3] = 0.6
  ## Data generation part
  totals1 = ceiling(runif(rep1, sample_size1, sample_size2))
  totals2 = ceiling(runif(rep2, sample_size1, sample_size2))
  diri_s1 = probC1 * concentration
  diri_s2 = probC2 * concentration
  sim_dat <- DCATS::simulator_base(totals1, totals2, diri_s1, diri_s2, simil_mat)
  numb_cond1 = as.matrix(sim_dat$numb_cond1)
  numb_cond2 = as.matrix(sim_dat$numb_cond2)
  
  ## Test part 1
  ### DCATS
  dcats_res1 = betabinLRT_rw(numb_cond1, numb_cond2, bias_corr = FALSE)
  ### fisher
  fisher_pvals1 = getFisher(numb_cond1, numb_cond2)
  
  ## Bias Correction
  numb_cond1BC = numb_cond1
  numb_cond2BC = numb_cond2
  for (i in seq_len(nrow(numb_cond1))) {
    numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) * multinom_EM(numb_cond1[i, ], simil_mat, verbose = FALSE)$mu
    numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])}
  for (i in seq_len(nrow(numb_cond2))) {
    numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) * multinom_EM(numb_cond2[i, ], simil_mat, verbose = FALSE)$mu
    numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])}
  
  ## Test part 2
  ### DCATS
  dcats_res2 = betabinLRT_rw(numb_cond1BC, numb_cond2BC, bias_corr = FALSE)
  ### fisher
  fisher_pvals2 = getFisher(numb_cond1BC, numb_cond2BC)
  
  all_res = data.frame(cluster = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L")[1:cluster_num], truth = truthRes) %>%
    mutate(dcats_noBC = dcats_res1$pvals,
           fisher_noBC = fisher_pvals1,
           dcats_withBC = dcats_res2$pvals,
           fisher_withBC = fisher_pvals2)
  
  simulationDF = rbind(simulationDF, all_res)}
```

### plot

```{r}
dcats_noBC_ROCobj = getROC(simulationDF$truth, simulationDF$dcats_noBC)
fisher_noBC_ROCobj = getROC(simulationDF$truth, simulationDF$fisher_noBC)
dcats_withBC_ROCobj = getROC(simulationDF$truth, simulationDF$dcats_withBC)
fisher_withBC_ROCobj = getROC(simulationDF$truth, simulationDF$fisher_withBC)

size = nrow(dcats_noBC_ROCobj$df)
res = rbind(dcats_noBC_ROCobj$df, fisher_noBC_ROCobj$df, dcats_withBC_ROCobj$df, fisher_withBC_ROCobj$df) %>% 
  mutate(method = c(rep("dcats_noBC", size), rep("fisher_noBC", size), rep("dcats_withBC", size), rep("fisher_withBC", size)),
         index = rep(1:size, 4)) %>% 
  tidyr::separate(method, c("method", "condition"), sep = "_")

plotF1 =  res %>% 
  ggplot(aes(x = x, y = sensitivity, color = method)) + 
  geom_line(orientation = "y") + 
  facet_grid(.~condition) +
  geom_abline(slope=1, color="gray", linetype="dashed") +
  ylab("Sensitivity") +
  xlab("1-Specificity")
ggsave(str_c("./data/figure1_cluster", as.character(cluster_num), ".png"), plot = plotF1)
print(plotF1)
```

## Figure B

## Different number of replicates

```{r}
## cluster number = 8
simulationDF_all = data.frame()
load("./data/simulationRES/replicates3&2_K8_con90_splatter1000&1500.RData")
simulationDF_all = 
```

