---
title: "Real word data"
author: "Xinyi Lin"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
```

```{r}
source("functions.r")
```

## Experiment 3

TIP is the one Hepheas used

```{r}
exp3_GFP <- read.delim("./data/real_word/Farbehi_2019/GFP_tSNE_cluster_ID_table.txt") %>% 
  mutate(cluster = as.factor(cluster),
         experiment = as.factor(experiment))
exp3_TIP <- read.delim("./data/real_word/Farbehi_2019/TIP_tSNE_cluster_ID_table.txt") %>% 
  mutate(cluster = as.factor(cluster),
         experiment = as.factor(experiment))
head(exp3_GFP)
head(exp3_TIP)
summary(exp3_GFP)
summary(exp3_TIP)
```

Fisher's exact test

```{r}
get_fisherP = function(data = data, sumL = sumL){
  data_sum = data %>% 
    group_by(conditions) %>% 
    summarise(n = n())
  
  data_count = data %>% 
    group_by(cluster, conditions) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "cluster", values_from = "n")

  fisher_pvals = rep(NA,ncol(data_count)-1)
  cluster_name = colnames(data_count)[-1]
  for (i in 2:ncol(data_count)) {
    cot_table = cbind(data_count[, i], data_sum$n-data_count[, i])
    fisher_pvals[i-1] = fisher.test(cot_table)$p.value
    }
  
  fisherP = data.frame(cluster = cluster_name, fisher_pvals = fisher_pvals)
  return(fisherP)
}
```

diffcyt cannot works without batch

```{r, eval=FALSE}
cell_numberL = exp3_TIP_37_sum$n
# Function to create random data (one sample)
d_random <- function(cell_number, mean = 0, sd = 1, ncol = 20, cofactor = 5) {
  d <- sinh(matrix(rnorm(cell_number*20, mean, sd), ncol = ncol)) * cofactor
  colnames(d) <- paste0("marker", sprintf("%02d", 1:ncol))
  return(d)
}
# Create random data (without differential signal)
set.seed(123)
d_input <- list(
  sample1 = d_random(cell_number = cell_numberL[1]), 
  sample2 = d_random(cell_number = cell_numberL[2])
)
experiment_info <- data.frame(
  sample_id = factor(exp3_TIP_37_sum$experiment), 
  stringsAsFactors = FALSE
)
marker_info <- data.frame(
  channel_name = paste0("channel", sprintf("%03d", 1:20)), 
  marker_name = paste0("marker", sprintf("%02d", 1:20)), 
  marker_class = factor(c(rep("type", 10), rep("state", 10)), 
                          levels = c("type", "state", "none")), 
  stringsAsFactors = FALSE
)
# Prepare data
d_se <- prepareData(d_input, experiment_info, marker_info)
# Transform data
d_se <- transformData(d_se)
# Generate clusters
d_se <- generateClusters(d_se)
# Replace with our simulated data info
d_se@elementMetadata$sample_id = exp3_TIP_37$experiment
d_se@elementMetadata$cluster_id = exp3_TIP_37$cluster
# Calculate counts
d_counts <- calcCounts(d_se)
# Create design matrix
design <- createDesignMatrix(experiment_info, cols_design = "sample_id")
# Create contrast matrix
contrast <- createContrast(c(0, 1))
# Test for differential abundance (DA) of clusters
res_DA <- testDA_edgeR(d_counts, design, contrast)
diffcytP = topTable(res_DA, format_vals = TRUE) %>% 
  as.data.frame() %>% 
  rownames_to_column("cluster") %>% 
  dplyr::rename(diffcyt_pvals = p_adj) %>% 
  select(cluster, diffcyt_pvals)
```

```{r}
## MI-Day3 vs MI-Day7
exp3_TIP_37 = exp3_TIP %>% 
  filter(experiment != "Sham") %>% 
  dplyr::rename(conditions = experiment)
fisherP = get_fisherP(exp3_TIP_37)
print(fisherP)

## Sham vs MI-Day7
exp3_TIP_S3 = exp3_TIP %>% 
  filter(experiment != "MI-Day 7") %>% 
  dplyr::rename(conditions = experiment)
fisherP = get_fisherP(exp3_TIP_S3)
print(fisherP)

## Sham vs MI-Day3
exp3_TIP_S7 = exp3_TIP %>% 
  filter(experiment != "MI-Day 3") %>% 
  dplyr::rename(conditions = experiment)
fisherP = get_fisherP(exp3_TIP_S7)
print(fisherP)
```

## Experiment 5

Don't know which data is used in exp5

```{r}

```

## Experiment 6

Don't know which data is used in exp6

```{r}

```

## Experiment 7

The 'group' column started with 'B' is not useful here.

```{r}
exp7_data <- read.csv("./data/real_word/Adam_2017/celltypelabels_Haber.txt", sep="") %>% 
  rownames_to_column("cell") %>% 
  separate(cell, c("group", "barcode", "condition", "cluster"), sep = "_") %>% 
  mutate(group = as.factor(group),
         condition = as.factor(condition),
         cluster = as.factor(cluster))

head(exp7_data)
summary(exp7_data)

exp7_data %>% 
  group_by(group, condition) %>% 
  summarise(n = n())
```

```{r}

```



## Codes

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```
