---
title: "Simulation9"
author: "Xinyi Lin"
date: "2/13/2021"
output: html_document
---

In this file, try to add rf and svm matrices to see whether the result will be improved.

## Simulation with transcriptome information

```{r, message=FALSE, warning=FALSE}
library(splatter)
library(Seurat)
library(SeuratWrappers)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
library(MCMCpack)
library(scdney)
library(pROC)
```

```{r, message=FALSE, warning=FALSE}
source("functionsV2.r")
source("glm.R")     # for scDC
options(future.globals.maxSize = 15000 * 1024^2)
```

```{r}
cell_pool = "realWorld"  # cell pool used, can be selected from ("mis1", "discrete", "realWorld")
cluster_num = 7  # numbers of clusters
concentration = 50 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.2
rep1 = 6
rep2 = 4
simulation_times = 10
sample_size1 = 1000
sample_size2 = 2000
more_negative = "_pN"
```

```{r}
if (is.na(more_negative)){
  if (cluster_num == 3){
  probC1 = c(1/3, 1/3, 1/3)  # True proportions
  probC2 = c(1/3, 1/2, 1/6)
  truthRes = c("N", "P", "P")
  } else if (cluster_num == 7){
    probC1 = c(rep(0.1, 4), rep(0.2, 3))
    probC2 = c(0.1, 0.1, 0.2, 0.05, 0.2, 0.3, 0.05)
    truthRes = c("N", "N", "P", "P", "N", "P", "P")
    } else if (cluster_num == 12) {
      probC1 = c(rep(0.1, 4), rep(0.2, 2), rep(0.05, 2), rep(0.025, 4))
      probC2 = c(0.1, 0.1, 0.15, 0.05, 0.2, 0.1, 0.05, 0.1, 0.025, 0.025, 0.05, 0.05)
      truthRes = c("N", "N", "P", "P", "N", "P", "N", "P", "N", "N", "P", "P")
    }
  }
```

```{r}
if (more_negative == "_pN"){
  if (cluster_num == 3){
    probC1 = c(1/3, 1/3, 1/3)  # True proportions
    probC2 = c(1/3, 1/2, 1/6)
    truthRes = c("N", "P", "P")
    } else if (cluster_num == 7){
      probC1 = c(rep(0.1, 4), rep(0.2, 3))
      probC2 = c(0.1, 0.1, 0.1, 0.15, 0.2, 0.3, 0.05)
      truthRes = c("N", "N", "N", "P", "N", "P", "P")
      } else if (cluster_num == 12) {
        probC1 = c(rep(0.1, 4), rep(0.2, 2), rep(0.05, 2), rep(0.025, 4))
        probC2 = c(0.1, 0.1, 0.1, 0.1, 0.2, 0.15, 0.05, 0.075, 0.05, 0.025, 0.025, 0.025)
        truthRes = c("N", "N", "N", "N", "N", "P", "N", "P", "P", "N", "N", "N")
      }
  }
```

```{r}
if (cell_pool == "discrete"){
  load(str_c("./data/cells_pool", as.character(cluster_num), ".RData"))
} else if (cell_pool == "mis1") {
    load(str_c("./data/cells_pool", as.character(cluster_num), "_close.RData"))
} else if (cell_pool == "realWorld") {
    load(str_c("./data/cells_pool", as.character(cluster_num), "_realWorld.RData"))
}
```

```{r, message=FALSE, warning=FALSE}
## output data
simulationDF = data.frame()  # data frame to store test result
time = matrix(NA, nrow = simulation_times, ncol = 6) # matrix contains time for each test need in each simulation
true_countL = vector(mode = "list", length = simulation_times) # list contains the count table of each true cluster
seurat_countL = vector(mode = "list", length = simulation_times) # list contains the count table of each cluster defined by seurat
knn_matrixL = vector(mode = "list", length = simulation_times) # list contains the knn matrix getting from each simulation
true_matrixL = vector(mode = "list", length = simulation_times) # list contains the true similarity matrix getting from each simulation

set.seed(123)
for (i in 1:simulation_times){
  print(i)
  timeL = rep(NA, 6) # DCATS w/wto simularity matrix, fisher, speckle, diffcyt, scDC
  ## simulation
  simulation = simulator_fastMNN(totals1 = runif(rep1, sample_size1, sample_size2), totals2 = runif(rep2, sample_size1, sample_size2), probC1, probC2, setresolu, sim_mat)
  if (is.na(simulation)[1] == FALSE){
    true_countL[[i]] = list(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2)
    ## data convert
    numb_cond1 = simulation$dfRes %>% 
      filter(condition == "Cond1") %>%
      group_by(clusterRes, batch) %>% 
      summarise(n = n()) %>% 
      pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
      column_to_rownames(var = "batch")
    numb_cond2 = simulation$dfRes %>% 
      filter(condition == "Cond2") %>%
      group_by(clusterRes, batch) %>% 
      summarise(n = n()) %>% 
      pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
      column_to_rownames(var = "batch")
    numb_cond1[is.na(numb_cond1)] <- 0
    numb_cond2[is.na(numb_cond2)] <- 0
    conf.mat<-table(simulation$trueLabels, Idents(simulation$integratedSamples))
    true.conf<-t(t(conf.mat)/apply(conf.mat,2,sum))
    library(clue)
    order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
    L_sum1 = colSums(numb_cond1)
    L_sum2 = colSums(numb_cond2)
    decider = sum(L_sum1 > 10)+sum(L_sum2 > 10)
    if (decider == cluster_num*2) {   # if one cluster has least than 10 cells in one condition, then won't continue
      seurat_countL[[i]] = list(cond1 = numb_cond1[,order2], cond2 = numb_cond2[,order2])
      ## Get matrices
      ### KNN matrix
      graphs = simulation$integratedSamples@graphs$RNA_snn
      labels = Idents(simulation$integratedSamples)
      knn_mat = KNN_transition(graphs, labels)
      order1 = colnames(numb_cond1)
      simil_matK = knn_mat[order1, order1]
      knn_matrixL[[i]] = simil_matK
      ### Uniform matrix
      simil_matU = get_similarity_mat(cluster_num, confuse_rate=0.1)
      ### True matrix
      simil_matT = true.conf[,order2]
      true_matrixL[[i]] = simil_matT
      ### svm&rf
      mlDF = simulation$integratedSamples@reductions$pca@cell.embeddings %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("cellID") %>% 
        merge(simulation$dfRes, by = "cellID") %>% 
        dplyr::select(-cellID)
      set.seed(123)
      simil_matRF = get_similarity_matRW(method = "rf", df = mlDF)
      simil_matSVM = get_similarity_matRW(method = "svm", df = mlDF)
      ## Test
      ### DCATS---betabinLRT
      t1start = Sys.time()
      betabin_noBC = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = FALSE)
      timeL[1] = Sys.time() - t1start
      ###  DCATS---betabinLRT with Bias correction from similarity matrix
      betabin_wBC_K = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matK)
      betabin_wBC_U = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matU)
      betabin_wBC_T = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matT)
      betabin_wBC_RF = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matRF)
      betabin_wBC_SVM = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matSVM)
      ## DCATS---betabin with similarity matrix (backward-forward)
      t2start = Sys.time()
      betabin_wMK = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matK, n_samples = 50, binom_only = FALSE)
      timeL[2] = Sys.time() - t2start
      betabin_wMU = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 50, binom_only = FALSE)
      betabin_wMT = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matT, n_samples = 50, binom_only = FALSE)
      betabin_wMRF = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matRF, n_samples = 50, binom_only = FALSE)
      timeL[2] = Sys.time() - t2start
      betabin_wMSVM = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matSVM, n_samples = 50, binom_only = FALSE)
      bin_wMK = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matK, n_samples = 50)
      bin_wMU = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 50)
      bin_wMT = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matT, n_samples = 50)
      bin_wMRF = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matRF, n_samples = 50)
      bin_wMSVM = dcats_betabinRW(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matSVM, n_samples = 50)
      ## Fisher's exact test
      t3start = Sys.time()
      fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
      timeL[3] = Sys.time() - t3start
      ## speckle
      t4start = Sys.time()
      speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
        dplyr::rename(cluster = BaselineProp.clusters,
                      speckle_pvals = FDR) %>%
        dplyr::select(cluster, speckle_pvals)
      timeL[4] = Sys.time() - t4start
      ## diffcyt
      t5start = Sys.time()
      diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$dfRes)
      timeL[5] = Sys.time() - t5start
      ## scDC
      t6start = Sys.time()
      res_scDC <- scDC_noClustering(cellTypes = simulation$dfRes$clusterRes, simulation$dfRes$batch, calCI = TRUE, calCI_method = c("percentile", "BCa", "multinom"),nboot = 1000, verbose = FALSE)
      res_GLM <- fitGLM(res_scDC, c(rep("cond1",rep1*cluster_num),rep("cond2",rep2*cluster_num)), pairwise = FALSE, fixed_only = TRUE, verbose = FALSE)
      timeL[6] = Sys.time() - t6start
      scDCRes_temp = summary(res_GLM$pool_res_fixed)
      scDCRes = scDCRes_temp[c(cluster_num+1,(dim(scDCRes_temp)[1]-cluster_num+2):dim(scDCRes_temp)[1]),]
      ## results
      cluster_map = data.frame(originLab = order2, cluster = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L")[1:cluster_num]) %>% 
        arrange(originLab) %>% 
        mutate(truth = truthRes) %>% 
        arrange(cluster) %>% 
        dplyr::select(-originLab)
      all_res = cluster_map %>% 
        mutate(betabin_noBC_pvals = betabin_noBC$pvals,
               betabin_wBCK_pvals = betabin_wBC_K$pvals,
               betabin_wBCU_pvals = betabin_wBC_U$pvals,
               betabin_wBCT_pvals = betabin_wBC_T$pvals,
               betabin_wBCRF_pvals = betabin_wBC_RF$pvals,
               betabin_wBCSVM_pvals = betabin_wBC_SVM$pvals,
               betabin_wMK_pvals = betabin_wMK$pvals,
               betabin_wMU_pvals = betabin_wMU$pvals,
               betabin_wMT_pvals = betabin_wMT$pvals,
               betabin_wMRF_pvals = betabin_wMRF$pvals,
               betabin_wMSVM_pvals = betabin_wMSVM$pvals,
               bin_wMK_pvals = bin_wMK$pvals,
               bin_wMU_pvals = bin_wMU$pvals,
               bin_wMT_pvals = bin_wMT$pvals,
               bin_wMRF_pvals = bin_wMRF$pvals,
               bin_wMSVM_pvals = bin_wMSVM$pvals,
               fisher_pvals = fisher_pvals,
               scDC_pvals = scDCRes$p.value) %>%
        merge(speckleRes, by = "cluster") %>% 
        merge(diffcytP, by = "cluster")
      simulationDF = rbind(simulationDF, all_res)
      time[i,] = timeL
    }
  }
}

## send email after finishing
sendEmail("Simulation is done!!")

file_name = str_c("./data/simulationRES/repplicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, ".RData")
colnames(time) = c("DCATS_wtoM", "DCATS_wM", "fisher", "speckle", "diffcyt", "scDC")
save(simulationDF, time, true_countL, seurat_countL, knn_matrixL, true_matrixL, file = file_name)
head(simulationDF)
```

```{r, message=FALSE}
library(pROC)
numb_res = dim(simulationDF)[2]-2
aucRes = rep(NA, numb_res)
for (i in 1:numb_res){
  roc = roc(simulationDF$truth, simulationDF[,i+2])
  aucRes[i] = roc$auc
}
methods = colnames(simulationDF)[3:(numb_res+2)]
aucDF = data.frame(methods = methods, auc = aucRes) %>% 
  arrange(desc(auc))
print(aucDF)
```

```{r}
file_name = str_c("./data/simulationRES/repplicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, ".RData")
load(file_name)
set.seed(123)
for (i in 1:simulation_times){
  
  seurat_countL[[i]] = list(cond1 = numb_cond1[,order2], cond2 = numb_cond2[,order2])
```


```{r, message=FALSE}
roc_rose <- plot(roc(simulationDF$truth, simulationDF[,3]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7, print.auc.x = .5, col = 1)
numb_res = dim(simulationDF)[2]-2
methodsL = colnames(simulationDF)[3:(numb_res+2)]
graphics::text(0.1, 0.69, paste(methodsL[1]), col=1)
for (i in 1:numb_res){
  roc_rose <- plot(roc(simulationDF$truth, simulationDF[,i+2]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7-(i-1)*0.05, print.auc.x = .5, col = i, add = TRUE)
  graphics::text(0.1, 0.69-(i-1)*0.05, paste(methodsL[i]), col=i)
}

print("Time")
apply(na.omit(time), 2, mean)
```