---
title: "Simulation_plus6"
output: html_document
---

This is the version create more than one duplicate in each sample.

Questions:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE)
```

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(SeuratWrappers)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
library(MCMCpack)
```

```{r,warning=FALSE, message=FALSE}
library(future)
# check the current active plan
plan()
# change the current plan to access parallelization
plan("multiprocess", workers = 6)
plan()
options(future.globals.maxSize = 2000 * 1024^2)
```

```{r}
source("functionsV2.r")
```

## get seed files

```{r, eval=FALSE}
## read seed files and convert to required format
## Kang's data
exp6_cond1 = read.delim("./data/real_word/Exp6_Kang/GSE96583_batch1.total.tsne.df.tsv")
exp6_cond2 = read.delim("./data/real_word/Exp6_Kang/GSE96583_batch2.total.tsne.df.tsv")
exp6_totals = list(totals1 = table(exp6_cond1$batch), totals2 = table(exp6_cond2$stim))
saveRDS(exp6_totals, "./data/real_word/exp6_totals.rds")
exp6_totals = readRDS("./data/real_word/exp6_totals.rds")
print(exp6_totals)

##AML data
exp5_AML <- read.delim("./data/real_word/Exp5_Galen/GSM3587924_AML1012-D0.anno.txt")
exp5_BM1 <- read.delim("./data/real_word/Exp5_Galen/GSM3587996_BM1.anno.txt")
exp5_BM2 <- read.delim("./data/real_word/Exp5_Galen/GSM3587997_BM2.anno.txt")
exp5_BM3 <- read.delim("./data/real_word/Exp5_Galen/GSM3587999_BM3.anno.txt")
exp5_BM4 <- read.delim("./data/real_word/Exp5_Galen/GSM3588001_BM4.anno.txt")
exp5_totals = list(totals1 = nrow(exp5_AML), totals2 = c(nrow(exp5_BM1), nrow(exp5_BM2), nrow(exp5_BM3), nrow(exp5_BM4)))
saveRDS(exp5_totals, "./data/real_word/exp5_totals.rds")
exp5_totals = readRDS("./data/real_word/exp5_totals.rds")
print(exp5_totals)
```

```{r, eval=FALSE}
## input seed file
exp6_totals = readRDS("./data/real_word/exp6_totals.rds")
print(exp6_totals)
exp5_totals = readRDS("./data/real_word/exp5_totals.rds")
print(exp5_totals)
```

```{r}
cluster_num = 3
probC1 = c(1/3, 1/3, 1/3)
probC2 = c(1/3, 1/2, 1/6)
magnitude = 30 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.2
```

## Simulate cells pool

```{r,eval=FALSE}
## simulate cells pool setting
set.seed(123)
prob = c(1/3, 1/3, 1/3)
batch_size = 10000
de_prob = runif(3, 0.2, 0.6)
setresolu = 0.2
sample_size = 1000
```

```{r,eval=FALSE}
## simulate cells pool process
set.seed(123)
params = readRDS("./data/ovarian_params.rds")
#params = readRDS("./data/mnnCT7params.rds")
param.groups <- setParams(params, batchCells = batch_size, nGenes = 1000)
sim <- splatSimulateGroups(param.groups, group.prob = prob, de.prob = de_prob, de.facLoc = 0.01, verbose = FALSE)
sim_mat <- counts(sim)
origLabels = sim@colData@listData$Group
# Save multiple objects
save(sim_mat, origLabels, file = "./data/cells_pool.RData")
```

```{r}
load("./data/cells_pool.RData")
```

## simulate proportions

```{r, eval=FALSE}
## test for function simulator_fastMNN
totals1 = exp6_totals[[1]]
totals2 = exp6_totals[[2]]

K = length(probC1)
n_rep1 = length(totals1)
n_rep2 = length(totals2)

prop_cond1 = matrix(0, n_rep1, K)
prop_cond2 = matrix(0, n_rep2, K)
numb_cond1 <- matrix(0, n_rep1, K)
numb_cond2 <- matrix(0, n_rep2, K)

slt_sim_matC1 = matrix(NA, ncol = 0, nrow = 1000)
slt_origLabelsC1 = vector()
slt_batchesC1 = character()
for (i in seq_len(n_rep1)) {
  prop_cond1[i, ] <- MCMCpack::rdirichlet(1, probC1 * magnitude)
  numb_cond1[i, ] <- rmultinom(1, totals1[i], prop_cond1[i, ])
  #numb_cond1[i, ] = (totals1[i] * prop_cond1[i, ]) %>% ceiling()
  cell_slt = cell_slt_dup(numb_cond1[i,], sim_mat, origLabels)
  slt_sim_matC1 = cbind(slt_sim_matC1, cell_slt$sub_sim_mat)
  slt_origLabelsC1 = c(slt_origLabelsC1, cell_slt$sub_origLabels)
  slt_batchesC1 = c(slt_batchesC1, rep(str_c("cond1s", as.character(i)), length(cell_slt$sub_origLabels)))
}

slt_sim_matC2 = matrix(NA, ncol = 0, nrow = 1000)
slt_origLabelsC2 = factor()
slt_batchesC2 = character()
for (i in seq_len(n_rep2)) {
  prop_cond2[i, ] <- MCMCpack::rdirichlet(1, probC2 * magnitude)
  numb_cond2[i, ] <- rmultinom(1, totals2[i], prop_cond2[i, ])
  cell_slt = cell_slt_dup(numb_cond2[i,], sim_mat, origLabels)
  slt_sim_matC2 = cbind(slt_sim_matC2, cell_slt$sub_sim_mat)
  slt_origLabelsC2 = c(slt_origLabelsC2, cell_slt$sub_origLabels)
  slt_batchesC2 = c(slt_batchesC2, rep(str_c("cond2s", as.character(i)), length(cell_slt$sub_origLabels)))
}

#time1 = Sys.time() # need around 5 minutes
integratedSamples = fastMNN(slt_sim_matC1, slt_sim_matC2, slt_batchesC1, slt_batchesC2, setresolu)
#print(Sys.time() - time1)
plot = DimPlot(integratedSamples, reduction = "umap", split.by = "batch", ncol = 3) + ggtitle("Cluster Results of Different Clusters in Different Samples")
print(plot)
conf.mat<-table(Idents(integratedSamples), c(slt_origLabelsC1, slt_origLabelsC2))
print(conf.mat)

dfRes = data.frame(clusterRes = integratedSamples@active.ident, batch = integratedSamples$batch, condition = integratedSamples$condition) %>% 
    tibble::rownames_to_column("cellID")

numb_out_cond1 = dfRes %>% 
  filter(condition == "Cond1") %>% 
  group_by(clusterRes, batch) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = "clusterRes", values_from = "n")
numb_out_cond2 = dfRes %>% 
  filter(condition == "Cond2") %>% 
  group_by(clusterRes, batch) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = "clusterRes", values_from = "n")

```

```{r, message=FALSE, echo=FALSE, eval=FALSE}
set.seed(123)
simulation = simulator_fastMNN(totals1 = runif(3, 500, 2500), totals2 = runif(2, 2000, 3000), probC1, probC2, setresolu)
plot = DimPlot(simulation$integratedSamples, reduction = "umap", split.by = "batch", ncol = 3) + ggtitle("Cluster Results of Different Clusters in Different Samples")
print(plot)
conf.mat<-table(Idents(simulation$integratedSamples), simulation$trueLabels) 
print(conf.mat)
```

```{r, echo=FALSE, eval=FALSE}
numb_cond1 = simulation$dfRes %>% 
  filter(condition == "Cond1") %>% 
  group_by(clusterRes, batch) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
  column_to_rownames(var = "batch")
numb_cond2 = simulation$dfRes %>% 
  filter(condition == "Cond2") %>% 
  group_by(clusterRes, batch) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
  column_to_rownames(var = "batch")
```

```{r, echo=FALSE, eval=FALSE}
## DCATS---betabinLRT
betabin_noBC = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = FALSE)
print(betabin_noBC)
##  DCATS---betabinLRT with Bias correction from similarity matrix
simil_matI = get_similarity_mat(cluster_num, confuse_rate=0)
simil_matU = get_similarity_mat(cluster_num, confuse_rate=0.1)
betabin_wBC_I = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matI)
print(betabin_wBC_I)
betabin_wBC_U = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matU)
print(betabin_wBC_U)
## DCATS---betabin with similarity matrix (backward-forward)
betabin_wMI = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matI, n_samples = 100, binom_only = FALSE)
print(betabin_wMI)
betabin_wMU = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 100, binom_only = FALSE)
print(betabin_wMU)
bin_wMI = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matI, n_samples = 100)
print(bin_wMI)
bin_wMU = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 100)
print(bin_wMU)
```

```{r, echo=FALSE, eval=FALSE}
fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
print(fisher_pvals)
```
```{r, echo=FALSE, eval=FALSE}
## speckle
speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
  dplyr::rename(cluster = BaselineProp.clusters,
                speckle_pvals = FDR) %>% 
  dplyr::select(cluster, speckle_pvals)
print(speckleRes)
```

```{r, echo=FALSE, eval=FALSE}
## diffcyt
diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$integratedSamples)
diffcytP
```

```{r, echo=FALSE, eval=FALSE}
## results
cluster_map = apply(conf.mat, 2, which.max) %>% 
  plyr::mapvalues(from = c(1:cluster_num), to = c("A", "B", "C", "D", "E", "F")[1:cluster_num]) %>% 
  as_tibble() %>% 
  mutate(truth = c("N", "P", "P")) %>% 
  dplyr::rename(cluster = value) %>% 
  arrange(cluster)
cluster_map %>% 
  mutate(betabin_noBC_pvals = betabin_noBC$pvals,
         betabin_wBCI_pvals = betabin_wBC_I$pvals,
         betabin_wBCU_pvals = betabin_wBC_U$pvals,
         betabin_wMI_pvals = betabin_wMI$pvals,
         betabin_wMU_pvals = betabin_wMU$pvals,
         bin_wMI_pvals = bin_wMI$pvals,
         bin_wMU_pvals = bin_wMU$pvals,
         fisher_pvals = fisher_pvals) %>% 
  merge(speckleRes, by = "cluster") %>% 
  merge(diffcytP, by = "cluster")
```

```{r}
## do 50 times
simulation_times = 50
set.seed(123)
simulationDF = data.frame()
for (i in 1:simulation_times){
  ## simulation
  simulation = simulator_fastMNN(totals1 = runif(3, 500, 2500), totals2 = runif(2, 2000, 3000), probC1, probC2, setresolu)
  ## data convert
  numb_cond1 = simulation$dfRes %>% 
    filter(condition == "Cond1") %>% 
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond2 = simulation$dfRes %>% 
    filter(condition == "Cond2") %>% 
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  conf.mat<-table(Idents(simulation$integratedSamples), simulation$trueLabels)
  ## test
  ## DCATS---betabinLRT
  betabin_noBC = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = FALSE)
  ##  DCATS---betabinLRT with Bias correction from similarity matrix
  simil_matI = get_similarity_mat(cluster_num, confuse_rate=0)
  simil_matU = get_similarity_mat(cluster_num, confuse_rate=0.1)
  betabin_wBC_I = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matI)
  betabin_wBC_U = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matU)
  ## DCATS---betabin with similarity matrix (backward-forward)
  betabin_wMI = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matI, n_samples = 100, binom_only = FALSE)
  betabin_wMU = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 100, binom_only = FALSE)
  bin_wMI = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matI, n_samples = 100)
  bin_wMU = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 100)
  ## Fisher's exact test
  fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
  ## speckle
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
    dplyr::rename(cluster = BaselineProp.clusters,
                speckle_pvals = FDR) %>% 
    dplyr::select(cluster, speckle_pvals)
  ## diffcyt
  diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$integratedSamples)
  ## results
  cluster_map = apply(conf.mat, 2, which.max) %>% 
    plyr::mapvalues(from = c(1:cluster_num), to = c("A", "B", "C", "D", "E", "F")[1:cluster_num]) %>% 
    as_tibble() %>% 
    mutate(truth = c("N", "P", "P")) %>% 
    dplyr::rename(cluster = value) %>% 
    arrange(cluster)
  all_res = cluster_map %>% 
    mutate(betabin_noBC_pvals = betabin_noBC$pvals,
           betabin_wBCI_pvals = betabin_wBC_I$pvals,
           betabin_wBCU_pvals = betabin_wBC_U$pvals,
           betabin_wMI_pvals = betabin_wMI$pvals,
           betabin_wMU_pvals = betabin_wMU$pvals,
           bin_wMI_pvals = bin_wMI$pvals,
           bin_wMU_pvals = bin_wMU$pvals,
           fisher_pvals = fisher_pvals) %>% 
    merge(speckleRes, by = "cluster") %>% 
    merge(diffcytP, by = "cluster")
  simulationDF = rbind(simulationDF, all_res)
}

## send email after finishing
sendEmail("Simulation is done!!")

head(simulationDF)
```

```{r}
library(pROC)
methods = colnames(simulationDF)[3:12]
roc_rose <- plot(roc(simulationDF$truth, simulationDF[,3]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .8, print.auc.x = .6, col = 1)
graphics::text(0.2, 0.79, paste(methods[1]), col=1)
for (i in 2:10){
  roc_rose <- plot(roc(simulationDF$truth, simulationDF[,i+2]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .8-(i-1)*0.07, print.auc.x = .6, col = i, add = TRUE)
  graphics::text(0.2, 0.79-(i-1)*0.07, paste(methods[i]), col=i)
}
#par(xpd=TRUE)
#legend("topright", inset=c(-0.2,0), #legend=colnames(simulationDF)[3:12], box.lty = 0, box.lwd)
#par(pty = "m")
```

