---
title: "Simulation in Different Scenario"
author: "Xinyi Lin"
date: "9/17/2020"
output:
  pdf_document: default
  html_document: default
---

Problems need to solve:

1. DCATS: label problems

2. scDC: functions don't work

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
```

```{r}
source("functions.r")
```

## Different batch size

Batch sizes are 500, 1000, 1500, 2000.

```{r}
set.seed(123)
probNor = c(1/3,1/3,1/3)
probMut = c(1/2,1/6,1/3)
de_prob = c(0.1,0.1,0.5)

batch_size_list = seq(500,2000,500)
setresolu_list = c(0.5, 0.3, 0.3, 0.3)
```

```{r,warning=FALSE,message=FALSE}
for (i in 1:4) {
  batch_size = batch_size_list[i]
  setresolu = setresolu_list[i]
  
  sim_list = simualtion(probNor, probMut, resolution, de_prob, batch_size)
  integratedSamples = runSeurat(sim_list, batch_size)
  time = rep(NA,3)
  plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
  print(plot)
  dfRes = data.frame(clusterRes = integratedSamples@active.ident, batch = integratedSamples$batch, condition = integratedSamples$condition) %>% 
    tibble::rownames_to_column("cellID")
  ## Fisher's exact test
  dfCount = dfRes %>% 
    group_by(condition, clusterRes) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    mutate(nonA = B + C,
           nonB = A + C,
           nonC = A + B) %>% 
    select(A, B, C:nonC)
  t1start = Sys.time()
  fisher_pvals = rep(NA,3)
  for (i in 1:3){
    fisher_pvals[i] = fisher.test(dfCount[,c(i+1,i+4)])$p.value
    }
  time[1] = Sys.time() - t1start
  ## speckle
  t2start = Sys.time()
  speckleRes = propeller(clusters = dfRes$clusterRes, sample = dfRes$batch, group = dfRes$condition)
  time[2] = Sys.time() - t2start
  #print(speckleRes)
  speckleP = data.frame(cluster = speckleRes$BaselineProp.clusters, speckle_pvals = speckleRes$FDR)
  ## DCATS
  celllabels_orig = sim_list$origLabels
  conf.mat<-table(Idents(integratedSamples), celllabels_orig)
  true.conf<-t(t(conf.mat)/apply(conf.mat,2,sum))
  condition = integratedSamples@meta.data$condition
  condNor<-Idents(integratedSamples)[condition == "Normal"]
  condMut<-Idents(integratedSamples)[condition == "Mutate"]
  countNor = table(sim_list$batchNor, relevel(condNor, "A"))
  countMut = table(sim_list$batchMut, relevel(condMut, "A"))
  t3start = Sys.time()
  dcatsRes = dcats_fit(countNor, countMut, true.conf)
  time[3] = Sys.time() - t3start
  #print(dcatsRes)
  dcatsP = data.frame(cluster = rownames(dcatsRes), dcats_pvals = dcatsRes$pvals)
  Res_df = merge(dcatsP, speckleP, by = "cluster") %>% 
    mutate(fisher_pvals = fisher_pvals)
  time_df = data.frame(methods = c("fisher", "sepckle", "dcats"), time = time)
  print(list(Res_df = Res_df, time_df = time_df))
}
```

## Different de.prob

The de.prob of cluster B, C are 0.02, 0.04, 0.06, 0.08.

When de.prob equals to 0.04, only the fisher's exact test give the "correct" result.

```{r}
set.seed(123)
probNor = c(1/3,1/3,1/3)
probMut = c(1/2,1/6,1/3)
batch_size = 600

de_prob_list = seq(0.02, 0.08, 0.02)
setresolu_list = c(0.4, 0.4, 0.4, 0.3)
```

```{r,warning=FALSE,message=FALSE}
for (i in 1:4) {
  de_prob = c(de_prob_list[i], de_prob_list[i], 0.5)
  setresolu = setresolu_list[i]
  
  sim_list = simualtion(probNor, probMut, resolution, de_prob, batch_size)
  integratedSamples = runSeurat(sim_list, batch_size)
  time = rep(NA,3)
  plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
  print(plot)
  dfRes = data.frame(clusterRes = integratedSamples@active.ident, batch = integratedSamples$batch, condition = integratedSamples$condition) %>% 
    tibble::rownames_to_column("cellID")
  ## Fisher's exact test
  dfCount = dfRes %>% 
    group_by(condition, clusterRes) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    mutate(nonA = B + C,
           nonB = A + C,
           nonC = A + B) %>% 
    select(A, B, C:nonC)
  t1start = Sys.time()
  fisher_pvals = rep(NA,3)
  for (i in 1:3){
    fisher_pvals[i] = fisher.test(dfCount[,c(i+1,i+4)])$p.value
    }
  time[1] = Sys.time() - t1start
  ## speckle
  t2start = Sys.time()
  speckleRes = propeller(clusters = dfRes$clusterRes, sample = dfRes$batch, group = dfRes$condition)
  time[2] = Sys.time() - t2start
  #print(speckleRes)
  speckleP = data.frame(cluster = speckleRes$BaselineProp.clusters, speckle_pvals = speckleRes$FDR)
  ## DCATS
  celllabels_orig = sim_list$origLabels
  conf.mat<-table(Idents(integratedSamples), celllabels_orig)
  true.conf<-t(t(conf.mat)/apply(conf.mat,2,sum))
  condition = integratedSamples@meta.data$condition
  condNor<-Idents(integratedSamples)[condition == "Normal"]
  condMut<-Idents(integratedSamples)[condition == "Mutate"]
  countNor = table(sim_list$batchNor, relevel(condNor, "A"))
  countMut = table(sim_list$batchMut, relevel(condMut, "A"))
  t3start = Sys.time()
  dcatsRes = dcats_fit(countNor, countMut, true.conf)
  time[3] = Sys.time() - t3start
  #print(dcatsRes)
  dcatsP = data.frame(cluster = rownames(dcatsRes), dcats_pvals = dcatsRes$pvals)
  Res_df = merge(dcatsP, speckleP, by = "cluster") %>% 
    mutate(fisher_pvals = fisher_pvals)
  time_df = data.frame(methods = c("fisher", "sepckle", "dcats"), time = time)
  print(list(Res_df = Res_df, time_df = time_df))
}
```

## Different composition 

```{r}
set.seed(123)
probNor = c(0.4, 0.4, 0.2)
batch_size = 600
de_prob = c(0.06,0.06,0.5)

probMut_list = c(0.2, 0.3, 0.5, 0.6)
setresolu_list = c(0.3, 0.3, 0.3, 0.3)
```

```{r,warning=FALSE,message=FALSE}
for (i in 1:4) {
  probMut = c(probMut_list[i], 0.8 - probMut_list[i], 0.2)
  setresolu = setresolu_list[i]
  
  sim_list = simualtion(probNor, probMut, resolution, de_prob, batch_size)
  integratedSamples = runSeurat(sim_list, batch_size)
  time = rep(NA,3)
  plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
  print(plot)
  dfRes = data.frame(clusterRes = integratedSamples@active.ident, batch = integratedSamples$batch, condition = integratedSamples$condition) %>% 
    tibble::rownames_to_column("cellID")
  ## Fisher's exact test
  dfCount = dfRes %>% 
    group_by(condition, clusterRes) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    mutate(nonA = B + C,
           nonB = A + C,
           nonC = A + B) %>% 
    select(A, B, C:nonC)
  t1start = Sys.time()
  fisher_pvals = rep(NA,3)
  for (i in 1:3){
    fisher_pvals[i] = fisher.test(dfCount[,c(i+1,i+4)])$p.value
    }
  time[1] = Sys.time() - t1start
  ## speckle
  t2start = Sys.time()
  speckleRes = propeller(clusters = dfRes$clusterRes, sample = dfRes$batch, group = dfRes$condition)
  time[2] = Sys.time() - t2start
  #print(speckleRes)
  speckleP = data.frame(cluster = speckleRes$BaselineProp.clusters, speckle_pvals = speckleRes$FDR)
  ## DCATS
  celllabels_orig = sim_list$origLabels
  conf.mat<-table(Idents(integratedSamples), celllabels_orig)
  true.conf<-t(t(conf.mat)/apply(conf.mat,2,sum))
  #print(true.conf)
  condition = integratedSamples@meta.data$condition
  condNor<-Idents(integratedSamples)[condition == "Normal"]
  condMut<-Idents(integratedSamples)[condition == "Mutate"]
  countNor = table(sim_list$batchNor, relevel(condNor, "A"))
  countMut = table(sim_list$batchMut, relevel(condMut, "A"))
  t3start = Sys.time()
  dcatsRes = dcats_fit(countNor, countMut, true.conf)
  time[3] = Sys.time() - t3start
  #print(dcatsRes)
  dcatsP = data.frame(cluster = rownames(dcatsRes), dcats_pvals = dcatsRes$pvals)
  Res_df = merge(dcatsP, speckleP, by = "cluster") %>% 
    mutate(fisher_pvals = fisher_pvals)
  time_df = data.frame(methods = c("fisher", "sepckle", "dcats"), time = time)
  print(list(Res_df = Res_df, time_df = time_df))
}
```

## Codes

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```