---
title: "Figure1 Draft"
output: html_document
---

```{r,message=FALSE,warning=FALSE}
#library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(MCMCpack)
library(pROC)
```

```{r}
source("functionsV2.r")
options(future.globals.maxSize = 20000 * 1024^2) # 20G memory
```

```{r}
theme_set(theme_classic()+
    theme(panel.border = element_blank(),
          legend.key = element_blank(),
          axis.ticks = element_blank(),
          panel.grid = element_blank(),
          panel.grid.minor = element_blank(), 
          panel.grid.major = element_blank(),
          panel.background = element_blank(),
          legend.background = element_blank(),
          plot.background = element_rect(fill = "transparent",colour = NA))+
      theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14)))
```

```{r}
cluster_num = 3  # numbers of clusters
simulator_propM = 70 # indicate how simulated proportion far away from true, the larger the closer
#rep1 = 3
rep1 = 2
rep2 = 3
#rep2 = 4
simulation_times = 50
simulation_size = 50
sample_size1 = 2000
sample_size2 = 2000

probC1 = c(1/3, 1/3, 1/3)  # True proportions
probC2 = c(1/3, 1/2, 1/6)
truthRes = c("N", "P", "P")
```

Function use to calculate fisher with boostrap

Try used the complete version of dcats without fixed phi

```{r}
set.seed(123)

numb_cond1M = matrix(ncol = 3)
numb_cond2M = matrix(ncol = 3)
numb_cond1BCM = matrix(ncol = 3)
numb_cond2BCM = matrix(ncol = 3)
true_cond1M = matrix(ncol = 3)
true_cond2M = matrix(ncol = 3)
simulationDF_list = vector(mode = "list", length = simulation_times)
phiDF = data.frame()
for (sim in 1:simulation_times) {
  simulationDF = data.frame()
  for (simsim in 1:simulation_size){
    print(str_c("sim: ", as.character(sim), ", simsim: ", as.character(simsim)))
    ## create confusion matrix that is not uniformly distributed
    simil_mat = matrix(c(1, 0, 0, 0, 0.7, 0.3, 0, 0.3, 0.7), ncol = 3)
    
    ## Data generation part
    totals1 = ceiling(runif(rep1, sample_size1, sample_size2))
    totals2 = ceiling(runif(rep2, sample_size1, sample_size2))
    diri_s1 = probC1 * concentration
    diri_s2 = probC2 * concentration
    sim_dat <- DCATS::simulator_base(totals1, totals2, diri_s1, diri_s2, simil_mat)
    numb_cond1 = as.matrix(sim_dat$numb_cond1)
    numb_cond2 = as.matrix(sim_dat$numb_cond2)
    numb_cond1M = rbind(numb_cond1M, numb_cond1)
    numb_cond2M = rbind(numb_cond2M, numb_cond2)
    true_cond1M = rbind(true_cond1M, as.matrix(sim_dat$true_cond1))
    true_cond2M = rbind(true_cond2M, as.matrix(sim_dat$true_cond2))
    
    ## Test part 1
    ### DCATS
    count_mat = rbind(numb_cond1, numb_cond2)
    design_df = data.frame(condition = c(rep("c1", rep1), rep("c2", rep2)))
    estphi1 = getPhi(count_mat, design_df)
    #avrgPhi = getPhi2(count_mat, design_df)$avrgPhi
    #adjPhi = getPhi2(count_mat, design_df)$adjPhiV
    wtoPhi_res1 = dcats_GLM(count_mat, design_df)
    estPhi_res1 = dcats_GLM(count_mat, design_df, fix_phi = estphi1)
    eachPhi1 = eachPhi(count_mat, design_df)$fm0_phi %>% rowMeans()
    #estPhi_res1 = dcats_GLM(count_mat, design_df, phi = rep(phi, cluster_num))
    #avrgPhi_res1 = dcats_GLM(count_mat, design_df, phi = rep(avrgPhi, cluster_num))
    #adjPhi_res1 = dcats_GLM(count_mat, design_df, phi = adjPhi)
    ### fisher
    fisher_pvals1 = getFisher(numb_cond1, numb_cond2)
    
    ## Test part 2 - only use EM
    ## Bias Correction
    numb_cond1BC = numb_cond1
    numb_cond2BC = numb_cond2
    for (i in seq_len(nrow(numb_cond1))) {
      numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) * multinom_EM(numb_cond1[i, ], simil_mat, verbose = FALSE)$mu
      numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])}
    for (i in seq_len(nrow(numb_cond2))) {
      numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) * multinom_EM(numb_cond2[i, ], simil_mat, verbose = FALSE)$mu
      numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])}
    numb_cond1BCM = rbind(numb_cond1BCM, numb_cond1BC)
    numb_cond2BCM = rbind(numb_cond2BCM, numb_cond2BC)
    
    ### DCATS
    countBC_mat = rbind(numb_cond1BC, numb_cond2BC)
    estphi2 = getPhi(countBC_mat, design_df)
    wtoPhi_res2 = dcats_GLM(countBC_mat, design_df)
    estPhi_res2 = dcats_GLM(countBC_mat, design_df, fix_phi = estphi2)
    eachPhi2 = eachPhi(countBC_mat, design_df)$fm0_phi %>% rowMeans()
    #estPhi_res2 = dcats_GLM(countBC_mat, design_df, phi = rep(phi, cluster_num))
    #avrgPhi_res2 = dcats_GLM(countBC_mat, design_df, phi = rep(avrgPhi, cluster_num))
    #adjPhi_res2 = dcats_GLM(countBC_mat, design_df, phi = adjPhi)
    ### fisher
    fisher_pvals2 = getFisher(numb_cond1BC, numb_cond2BC)
    
    ## use estPhi2 and numb_cond
    estPhi_res3 = dcats_GLM(count_mat, design_df, fix_phi = estphi2)
    
    all_res = data.frame(cluster = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L")[1:cluster_num], truth = truthRes) %>%
      mutate(wtoPhi_null = as.vector(wtoPhi_res1$LRT_pvals),
             estPhi_null = as.vector(estPhi_res1$LRT_pvals),
             #avrgPhi_null = avrgPhi_res1$LRT_pvals,
             #adjPhi_null = adjPhi_res1$LRT_pvals,
             fisher_null = fisher_pvals1,
             wtoPhi_withBC = as.vector(wtoPhi_res2$LRT_pvals),
             estPhi_withBC = as.vector(estPhi_res2$LRT_pvals),
             #avrgPhi_withBC = avrgPhi_res2$LRT_pvals,
             #adjPhi_withBC = adjPhi_res2$LRT_pvals,
             fisher_withBC = fisher_pvals2,
             estPhi_test = as.vector(estPhi_res3$LRT_pvals))
    
    simulationDF = rbind(simulationDF, all_res)
    
    sub_phiDF = data.frame(sim = str_c(as.character(sim), "_", as.character(simsim)), cluster = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L")[1:cluster_num], truth = truthRes, estPhi1 = estphi1, eachPhi1 = eachPhi1, estPhi2 = estphi2, eachPhi2 = eachPhi2)
    
    phiDF = rbind(phiDF, sub_phiDF)
    }
  simulationDF_list[[sim]] = simulationDF
}
#save(simulationDF_list, phiDF, numb_cond1M, numb_cond2M, numb_cond1BCM, numb_cond2BCM, file = "D:/Data/DCATS/simulation/toy_simulation0117.RData")
save(simulationDF_list, phiDF, numb_cond1M, numb_cond2M, numb_cond1BCM, numb_cond2BCM, true_cond1M, true_cond2M, file = "/storage/holab/linxy/DCATS/simulation/toy_simulation0209.RData")
```

```{r}
#load("D:/Data/DCATS/simulation/simulationDF_list.RData")
evaluationDF = data.frame()
len = length(simulationDF_list)
#for (j in 1:8){
for (j in 1:len){
  simulationDF = simulationDF_list[[j]] %>% na.omit()
  method = colnames(simulationDF)[3:dim(simulationDF)[2]]
  numb_mthd = length(method)
  sensitivity = rep(NA, numb_mthd)
  specificity = rep(NA, numb_mthd)
  mcc = rep(NA, numb_mthd)
  auc = rep(NA, numb_mthd)
  prauc = rep(NA, numb_mthd)
  F1 = rep(NA, numb_mthd)
  
  truth = simulationDF$truth
  for (i in 3:dim(simulationDF)[2]){
    pred = simulationDF[, i]
    pred_res = ifelse(pred < 0.05, "P", "N")
    TP <- sum(pred_res=="P"&truth=="P")
    TN <- sum(pred_res=="N"&truth=="N")
    FP <- sum(pred_res=="P"&truth=="N")
    FN <- sum(pred_res=="N"&truth=="P")
    truthN = TN + FP
    truthP = FN + TP
    predP = TP + FP
    predN = FN + TN
    sensitivity[i-2] = TP/truthP
    specificity[i-2] = TN/truthN
    mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
    auc[i-2] = getROC(truth, pred)$auc
    prauc[i-2] = getPRC(truth, pred)$prauc
    F1 = 2*TP/(2*TP+FP+FN)
    
    res = data.frame(trial = as.character(j), method = method, sensitivity = sensitivity, specificity = specificity, mcc = mcc, auc = auc, prauc = prauc, F1 = F1)
    }
    evaluationDF = rbind(evaluationDF, res)
}
```

Plots

```{r}
evaluationDF %>% 
  tidyr::separate(method, c("method", "condition"), sep = "_") %>% 
  filter(condition != "full") %>% 
  pivot_longer(
    sensitivity:specificity,
    names_to = "statistics", 
    values_to = "value") %>% 
  #mutate(condition = ifelse(condition == "withBC", "with Bias Correction", "without Bias Correction"),
         #condition = factor(condition, levels = c("without Bias Correction", "with Bias Correction"))) %>%
  #mutate(method = ifelse(method == "dcats", "DCATS", "Fisher")) %>% 
  ggplot(aes(x = statistics, y = value, color = method)) + geom_boxplot() + facet_grid(.~condition) +
    theme(axis.title.x = element_blank())
  #ggplot(aes(x = statistics, y = value, color = method)) + geom_boxplot()
#ggsave("./plot/figureA2.png", bg = "transparent")
```

```{r}
evaluationDF %>% 
  tidyr::separate(method, c("method", "condition"), sep = "_") %>% 
  dplyr::select(-sensitivity, -specificity) %>% 
  filter(condition != "full") %>% 
  #mutate(method = ifelse(method == "dcats", "DCATS", "Fisher")) %>% 
  #mutate(condition = factor(condition, levels = c("wtoBC", "withBC"))) %>% 
  ggplot(aes(x = condition, y = auc, color = method)) + geom_boxplot() +
  theme(axis.title.x = element_blank(),
        legend.position = "top")
#ggsave("C:/#Code/R/slides/image/RPG_discussion/dcats_result1.png", bg = "transparent")
```

```{r}
evaluationDF %>% 
  tidyr::separate(method, c("method", "condition"), sep = "_") %>% 
  filter(condition != "full") %>% 
  #mutate(method = ifelse(method == "dcats", "DCATS", "Fisher")) %>% 
  #mutate(condition = factor(condition, levels = c("wtoBC", "withBC"))) %>% 
  ggplot(aes(x = condition, y = prauc, color = method)) + geom_boxplot() +
  theme(axis.title.x = element_blank(),
        legend.position = "top")
#ggsave("C:/#Code/R/slides/image/RPG_discussion/dcats_result1.png", bg = "transparent")
```

```{r}
phiDF %>% 
  ggplot(aes(x = eachPhi1, y = estPhi1)) +
  geom_point(aes(col = cluster))
phiDF %>% 
  ggplot(aes(x = eachPhi2, y = estPhi2)) +
  geom_point(aes(col = cluster))
phiDF %>% 
  ggplot(aes(x = eachPhi1, y = eachPhi2)) +
  geom_point(aes(col = cluster))
phiDF %>% 
  ggplot(aes(x = estPhi1, y = estPhi2)) +
  geom_point(aes(col = cluster))
```

## Add simple gene expression information

```{r, message=FALSE, warning=FALSE}
library(Seurat)
library(SeuratWrappers)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
library(MCMCpack)
#library(scdney)
library(scDC)
library(tidymodels)  ## for DCATS
library(miloR)
library(SingleCellExperiment)
```

```{r}
cluster_num = 8  # numbers of clusters
concentration = 100 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.6
rep1 = 2
rep2 = 2
simulation_times = 30
sample_size1 = 3000
sample_size2 = 3000
cell_pool = "splatter"  # cell pool used, can be selected from ("SPAR", "splatter", "realWorld")
more_negative = ""
```

```{r}
if(cluster_num == 8){
  probC1 = c(rep(0.1, 6), 0.2, 0.2)  # True proportions
  #probC2 = c(rep(0.1, 3), 0.05, 0.15, 0.2, 0.2, 0.1)
  #truthRes = c(rep("N", 3), rep("P", 3), "N", "P")
  probC2 = c(0.05, 0.15, rep(0.1, 3), 0.2, 0.2, 0.1)
  truthRes = c("P", "P", "N", "N", "N", "P", "N", "P")
} else if (cluster_num == 10){
  probC1 = c(0.05, 0.05, rep(0.1, 5), 0.05, 0.2, 0.15)  # True proportions
  probC2 = c(rep(0.1, 10))
  truthRes = c("P", "P", rep("N", 5), rep("P", 3))
} else if (cluster_num == 12){
  #probC1 = c(rep(0.1, 3), 0.05, 0.05, 0.05, 0.15, 0.1, 0.05, 0.05, 0.1, 0.1)  # True proportions
  probC1 = c(rep(0.1, 4), 0.05, 0.05, 0.05, 0.15, 0.05, 0.05, 0.1, 0.1)  # True proportions
  probC2 = c(rep(0.1, 8), rep(0.05, 4))
  #truthRes = c(rep("N", 3), rep("P", 4), "N", "N", "N", "P", "P")
  truthRes = c(rep("N", 4), rep("P", 4), "N", "N", "P", "P")
} else if (cluster_num == 6){
  probC1 = c(0.1, 0.1, 0.15, 0.15, 0.25, 0.25)  # True proportions
  probC2 = c(0.1, 0.15, 0.15, 0.2, 0.15, 0.25)
  truthRes = c("N", "P", "N", "P", "P", "N")
} else {
  print("Not pre-set clutser number")
}
```

```{r, message=FALSE, warning=FALSE}
source("functionsV2.r")
source("glm.R")     # for scDC
options(future.globals.maxSize = 15000 * 1024^2)
```

```{r}
if (cell_pool == "splatter"){
  #load(str_c("D:/#Data/DCATS/cells_pool", as.character(cluster_num), "_splatter.RData"))
  load(str_c("/storage/holab/linxy/DCATS/cells_pool", as.character(cluster_num), "_splatter.RData"))
} else if (cell_pool == "SPAR") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_SPARSim.RData"))
  
} else if (cell_pool == "realWorld") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_realWorld.RData"))
}
```

## Use foreach for simulation

```{r, eval=FALSE}
library(foreach)
library(doParallel)

# Create class which holds multiple results for each loop iteration.
# Each loop iteration populates nine properties: $clusterDF and $nhoodDF......
# For a great tutorial on S3 classes, see: 
# http://www.cyclismo.org/tutorial/R/s3Classes.html#creating-an-s3-class
multiResultClass <- function(clusterDF=NULL,nhoodDF=NULL,time=NULL,true_count=NULL,nhood_count=NULL,seurat_count=NULL,knn_matrix=NULL,true_matrix=NULL,svm_matrix=NULL)
{
  me <- list(
    clusterDF=clusterDF,
    nhoodDF=nhoodDF,
    time=time,
    true_count=true_count,
    nhood_count=nhood_count,
    seurat_count=seurat_count,
    knn_matrix=knn_matrix,
    true_matrix=true_matrix,
    svm_matrix=svm_matrix
  )

  ## Set the name for the class
  class(me) <- append(class(me),"multiResultClass")
  return(me)
}

unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}

#oper <- foreach(i=1:10) %dopar% {
#   result <- multiResultClass()
#   result$result1 <- i+1
#   result$result2 <- i+2
#   return(result)
#}
#oper1 <- oper[[1]]$result1
#oper2 <- oper[[1]]$result2
```

```{r, eval=FALSE}
#setup parallel backend to use many processors
cores=detectCores()
cl <- makeCluster(8) #not to overload your computer
registerDoParallel(cl)
startTime = Sys.time()
set.seed(1)
oper <- foreach(sim = 1:simulation_times, .packages=c("tidyverse", "Seurat", "DCATS", "speckle", "diffcyt", "scDC", "tidymodels", "miloR", "SingleCellExperiment"), .verbose = TRUE) %dopar% {
  result <- multiResultClass()  # where to save output
  timeL = rep(NA, 8) # DCATS w/wto similarity matrix, fisher, speckle, diffcyt, scDC
  ## simulation
  simulation = simulator_noInt(totals1 = runif(rep1, sample_size1, sample_size2), totals2 = runif(rep2, sample_size1, sample_size2), probC1, probC2, setresolu, sim_mat)
  if (is.na(simulation)[1] == TRUE){
    return(NA)
  }
  result$true_count = rbind(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2)
  ## data convert
  numb_cond1 = simulation$dfRes %>% 
    filter(condition == "Cond1") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond2 = simulation$dfRes %>% 
    filter(condition == "Cond2") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond1[is.na(numb_cond1)] <- 0
  numb_cond2[is.na(numb_cond2)] <- 0
  conf.mat <- table(simulation$trueLabels, Idents(simulation$integratedSamples))
  true.conf <- conf.mat/rowSums(conf.mat)
  library(clue)
  order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
  L_sum1 = colSums(numb_cond1)
  L_sum2 = colSums(numb_cond2)
  decider = sum(L_sum1 > 10)+sum(L_sum2 > 10)
  if (decider != cluster_num*2){
    return(NA)
  } # if one cluster has least than 10 cells in one condition, then won't continue
  result$seurat_count = list(cond1 = numb_cond1[,order2], cond2 = numb_cond2[,order2])
  ## Get matrices
  ### KNN matrix
  graphs = simulation$integratedSamples@graphs$RNA_snn
  labels = Idents(simulation$integratedSamples)
  knn_mat = knn_simMat(graphs, labels)
  order1 = colnames(numb_cond1)
  simil_matK = knn_mat[order1, order1]
  result$knn_matrix = simil_matK
  ### True matrix
  simil_matT = true.conf[,order2]
  result$true_matrix = simil_matT
  ### Uniform matrix
  simil_matU = create_simMat(cluster_num, confuse_rate=0.1)
  ### svm&rf
  mlDF = simulation$integratedSamples@reductions$pca@cell.embeddings %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column("cellID") %>% 
    merge(simulation$dfRes, by = "cellID") %>% 
    dplyr::select(-cellID)
  set.seed(123)
  simil_matSVM = svm_simMat(mlDF)
  result$svm_matrix = simil_matSVM
      
  ## Test
  ### DCATS---betabinLRT
  sim_count = rbind(numb_cond1, numb_cond2) %>% as.matrix()
  sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
  t1start = Sys.time()
  betabin_null = dcats_GLM(sim_count, sim_design)
  timeL[1] = Sys.time() - t1start
  ###  DCATS---betabinLRT with Bias correction from similarity matrix
  phi = getPhi(sim_count, sim_design)
  t2start = Sys.time()
  estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi)
  timeL[2] = Sys.time() - t2start
  ## KNN
  wtoPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK)
  t3start = Sys.time()
  estPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK, fix_phi = phi)
  timeL[3] = Sys.time() - t3start
  ## Uniform
  wtoPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU)
  estPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU, fix_phi = phi)
  ## True
  wtoPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT)
  estPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT, fix_phi = phi)
  ## svm
  wtoPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM)
  estPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM, fix_phi = phi)
      
  ## Fisher's exact test
  t4start = Sys.time()
  fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
  timeL[4] = Sys.time() - t4start
  ## speckle
  t5start = Sys.time()
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
    dplyr::rename(cluster = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(cluster, speckle_pvals)
  timeL[5] = Sys.time() - t5start
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
    dplyr::rename(cluster = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(cluster, speckle_pvals)
  ## diffcyt
  t6start = Sys.time()
  diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$dfRes)
  timeL[6] = Sys.time() - t6start
  ## scDC
  t7start = Sys.time()
  res_scDC <- scDC_noClustering(cellTypes = simulation$dfRes$clusterRes, simulation$dfRes$batch, calCI = TRUE, calCI_method = c("percentile", "BCa", "multinom"),nboot = 1000, verbose = FALSE)
  res_GLM <- fitGLM(res_scDC, c(rep("cond1",rep1*cluster_num),rep("cond2",rep2*cluster_num)), pairwise = FALSE, fixed_only = TRUE, verbose = FALSE)
  timeL[7] = Sys.time() - t7start
  scDCRes_temp = summary(res_GLM$pool_res_fixed)
  scDCRes = scDCRes_temp[c(cluster_num+1,(dim(scDCRes_temp)[1]-cluster_num+2):dim(scDCRes_temp)[1]),]
  ## milo
  t8start = Sys.time()
  milo_res = getMilo(simulation$integratedSamples)
  timeL[8] = Sys.time() - t8start
  miloDF_temp = milo_res$da_results %>% 
    filter(ident_fraction > 0.8) %>%
    mutate(direct = ifelse( logFC > 0  & SpatialFDR < 0.1, "milo_more", "neutral"),
           direct = ifelse( logFC < 0  & SpatialFDR < 0.1, "milo_less", direct)) %>% 
    group_by(ident, direct) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = direct, values_from = n) %>% 
    replace(is.na(.), 0) %>% 
    dplyr::rename(cluster = ident)
  if ("milo_less" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_less = rep(0, nrow(miloDF_temp))}
  if ("milo_more" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_more = rep(0, nrow(miloDF_temp))}
  miloDF = miloDF_temp %>% 
    dplyr::select(cluster, milo_less, neutral, milo_more)
  ## results
  cluster_map = data.frame(cluster = colnames(numb_cond1[,order2]), truth = truthRes) %>% 
    arrange(cluster)
  clusterDF = cluster_map %>% 
    mutate(betabin_null_pvals = as.vector(betabin_null$LRT_pvals),
           estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals),
           wtoPhi_emSVM_pvals = as.vector(wtoPhi_emSVM$LRT_pvals),
           estPhi_emSVM_pvals = as.vector(estPhi_emSVM$LRT_pvals),
           wtoPhi_emT_pvals = as.vector(wtoPhi_emT$LRT_pvals),
           estPhi_emT_pvals = as.vector(estPhi_emT$LRT_pvals),
           wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals),
           estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals),
           wtoPhi_emK_pvals = as.vector(wtoPhi_emK$LRT_pvals),
           estPhi_emK_pvals = as.vector(estPhi_emK$LRT_pvals),
           fisher_pvals = fisher_pvals,
           scDC_pvals = scDCRes$p.value) %>%
    merge(speckleRes, by = "cluster") %>% 
    merge(diffcytP, by = "cluster") %>% 
    left_join(miloDF, by = "cluster") %>% 
    replace(is.na(.), 0)
  result$clusterDF = clusterDF

  ## subset data
  posCluster = clusterDF %>% filter(truth == "P") %>% .$cluster
  subsetSamples = subset(simulation$integratedSamples, cells = names(milo_res$nhoodsID))
  subsetSamples = AddMetaData(object = subsetSamples, metadata = milo_res$nhoodsID[Cells(subsetSamples)], col.name = 'nhoods')
  ### Uniform matrix
  simil_matU = create_simMat(nrow(milo_res$da_results), confuse_rate=0.15)
  ## Test
  ### DCATS---betabinLRT
  sim_count = milo_res$counts %>% as.matrix() %>% t()
  result$nhood_count = sim_count
  sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
  betabin_null = dcats_GLM(sim_count, sim_design)
  ###  DCATS---betabinLRT with Bias correction from similarity matrix
  phi = getPhi(sim_count[,sample(1:ncol(sim_count), 20)], sim_design)
  estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi)
  wtoPhi_emU = dcats_GLM(sim_count, sim_design, similarity_mat = simil_matU)
  estPhi_emU = dcats_GLM(sim_count, sim_design, similarity_mat = simil_matU, fix_phi = phi)
  ## Fisher's exact test
  fisher_pvals = getFisher(sim_count[1:rep1,], sim_count[(rep1+1):(rep1+rep2),])
  ## speckle
  speckleRes = propeller(clusters = subsetSamples$nhoods, sample = subsetSamples$batch, group = subsetSamples$condition) %>%
    dplyr::rename(Nhood = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(Nhood, speckle_pvals)
  
  nhoodDF = milo_res$da_results %>% 
    mutate(truth = ifelse(ident %in% posCluster, "P", "N"),
           betabin_null_pvals = as.vector(betabin_null$LRT_pvals),
           estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals),
           wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals),
           estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals),
           fisher_pvals = fisher_pvals,
           Nhood = str_c("hoods", Nhood)) %>%
    merge(speckleRes, by = "Nhood")
  result$nhoodDF = nhoodDF
  result$time = timeL
  return(result)
}
stopCluster(cl) 
foreachtime = Sys.time() - startTime
```

```{r, eval=FALSE}
#file_name = str_c("D:/Data/DCATS/simulation/replicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, "para.RData")
file_name = str_c("/storage/holab/linxy/DCATS/simulation/replicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, "para.RData")
save(oper, file = file_name)
```

```{r}
clusterRes = data.frame()
seurat_count = data_frame()
true_count = data.frame()
for (idx in 1:length(oper)){
    if (!is.na(oper[[idx]])) {
      clusterRes = rbind(clusterRes, oper[[idx]]$clusterDF)
      oper[[idx]]$seurat_count$cond1 = oper[[idx]]$seurat_count$cond1 %>% 
        mutate(condition = "Condition 1")
      oper[[idx]]$seurat_count$cond2 = oper[[idx]]$seurat_count$cond2 %>% 
        mutate(condition = "Condition 2")
      seurat_count = rbind(seurat_count, oper[[idx]]$seurat_count$cond1)
      seurat_count = rbind(seurat_count, oper[[idx]]$seurat_count$cond2)
      oper[[idx]]$true_count = oper[[idx]]$true_count %>% as.data.frame() %>% mutate(condition = c(rep("Condition 1", rep1), rep("Condition 2", rep2)))
      true_count = rbind(true_count, oper[[idx]]$true_count)
      }
}
colnames(seurat_count) = c("P1", "P2", "N1", "N2", "N3", "P3", "N4", "P4", "condition")
colnames(true_count) = c("P1", "P2", "N1", "N2", "N3", "P3", "N4", "P4", "condition")
```

```{r}
sim2_prop = true_count %>% 
  pivot_longer(P1:P4, names_to = "cellType", values_to = "count") %>% 
  mutate(proportion = count/3000) %>% 
  ggplot(aes(cellType, proportion)) +
  geom_boxplot(aes(col = condition)) +
  theme(legend.position = "top") + 
  xlab("Cell type")
sim2_prop
```

```{r}
sim2_prop = seurat_count %>% 
  pivot_longer(P1:P4, names_to = "cellType", values_to = "count") %>% 
  mutate(proportion = count/3000) %>% 
  ggplot(aes(cellType, proportion)) +
  geom_boxplot(aes(col = condition)) +
  theme(legend.position = "top") + 
  xlab("Cell type")
sim2_prop
```

```{r}
clusterRes = clusterRes %>% 
    mutate(milo_main = ifelse(milo_less > milo_more, milo_less, milo_more),
           milo_pct = milo_main/(milo_less + neutral + milo_more),
           milo_diff = abs(milo_less - milo_more)) %>% 
    dplyr::select(-milo_less, -milo_more, - neutral, -milo_main)
methods = colnames(oper[[1]]$clusterDF)[colnames(oper[[1]]$clusterDF) %>% str_detect("_pvals")] %>% str_remove("_pvals")
  methods = c(methods, "milo")
  numb_mthd = length(methods)
  mcc = rep(NA, numb_mthd)
  auc = rep(NA, numb_mthd)
  prauc = rep(NA, numb_mthd)
  sensitivity = rep(NA, numb_mthd)
  specificity = rep(NA, numb_mthd)
  precision = rep(NA, numb_mthd)
  F1 = rep(NA, numb_mthd)

  truth = clusterRes$truth
  for (i in 3:(dim(clusterRes)[2]-1)){
    pred = clusterRes[,i]
    if (colnames(clusterRes)[i] == "milo_pct") {
      pred_res = ifelse(clusterRes$milo_diff > 0, "P", "N")
      auc[i-2] = getROC(clusterRes$truth, 1-pred)$auc
      prauc[i-2] = getPRC(clusterRes$truth, 1-pred)$prauc}
    else {
      pred_res = ifelse(pred < 0.1, "P", "N")
      auc[i-2] = getROC(clusterRes$truth, pred)$auc
      prauc[i-2] = getPRC(clusterRes$truth, pred)$prauc}
    TP <- sum(pred_res=="P"&truth=="P")
    TN <- sum(pred_res=="N"&truth=="N")
    FP <- sum(pred_res=="P"&truth=="N")
    FN <- sum(pred_res=="N"&truth=="P")
    truthN = TN + FP
    truthP = FN + TP
    predP = TP + FP
    predN = FN + TN
    sensitivity[i-2] = TP/truthP
    specificity[i-2] = TN/truthN
    precision[i-2] = TP/predP
    #mcc[i-2] = sqrt(sensitivity[i]*specificity[i]*precision[i]*(TN/(TN+FN))) - sqrt((1-sensitivity[i])*(1-specificity[i])*(FN/predN)*(FP/predP))
    mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
    F1[i-2] = 2*TP/(2*TP+FP+FN)
    }
  data.frame(method = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision, F1 = F1) %>% 
    arrange(desc(auc))
```


## Use for loop for simulation

```{r}
set.seed(1)
true_countDF = data.frame()
seurat_countDF = data.frame()
knn_matrixL = list()
true_matrixL = list()
svm_matrixL = list()
clusterRes = data.frame()
nhood_countL = list()
nhoodRes = data.frame()
timeDF = data.frame()
for (idx in 1:simulation_times) {
  print(str_c("idx: ", as.character(idx)))
  timeL = rep(NA, 8) # DCATS w/wto similarity matrix, fisher, speckle, diffcyt, scDC
  ## simulation
  simulation = simulator_noInt(totals1 = runif(rep1, sample_size1, sample_size2), totals2 = runif(rep2, sample_size1, sample_size2), probC1, probC2, setresolu, sim_mat)
  if (is.na(simulation)[1] == TRUE){
    next
  }
  true_count = rbind(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2) %>% as.data.frame() %>% mutate(sim = idx)
  true_countDF = rbind(true_countDF, true_count)
  numb_cond1 = simulation$dfRes %>% 
    filter(condition == "Cond1") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond2 = simulation$dfRes %>% 
    filter(condition == "Cond2") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond1[is.na(numb_cond1)] <- 0
  numb_cond2[is.na(numb_cond2)] <- 0
  conf.mat <- table(simulation$trueLabels, Idents(simulation$integratedSamples))
  true.conf <- conf.mat/rowSums(conf.mat)
  library(clue)
  order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
  L_sum1 = colSums(numb_cond1)
  L_sum2 = colSums(numb_cond2)
  decider = sum(L_sum1 > 10)+sum(L_sum2 > 10)
  if (decider != cluster_num*2){
    next
  } # if one cluster has least than 10 cells in one condition, then won't continue
  seurat_count = rbind(numb_cond1[,order2], numb_cond2[,order2]) %>% mutate(sim = idx)
  seurat_countDF = rbind(seurat_countDF, seurat_count)
  ## Get matrices
  ### KNN matrix
  graphs = simulation$integratedSamples@graphs$RNA_snn
  labels = Idents(simulation$integratedSamples)
  knn_mat = knn_simMat(graphs, labels)
  order1 = colnames(numb_cond1)
  simil_matK = knn_mat[order1, order1]
  knn_matrixL[[idx]] = simil_matK
  ### True matrix
  simil_matT = true.conf[,order2]
  true_matrixL[[idx]] = simil_matT
  ### Uniform matrix
  simil_matU = create_simMat(cluster_num, confuse_rate=0.1)
  ### svm&rf
  mlDF = simulation$integratedSamples@reductions$pca@cell.embeddings %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column("cellID") %>% 
    merge(simulation$dfRes, by = "cellID") %>% 
    dplyr::select(-cellID)
  set.seed(123)
  simil_matSVM = svm_simMat(mlDF)
  svm_matrixL[[idx]] = simil_matSVM
  
  ## Test
  ### DCATS---betabinLRT
  sim_count = rbind(numb_cond1, numb_cond2) %>% as.matrix()
  sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
  t1start = Sys.time()
  betabin_null = dcats_GLM(sim_count, sim_design)
  timeL[1] = Sys.time() - t1start
  ###  DCATS---betabinLRT with Bias correction from similarity matrix
  phi = getPhi(sim_count, sim_design)
  t2start = Sys.time()
  estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi)
  timeL[2] = Sys.time() - t2start
  ## KNN
  wtoPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK)
  t3start = Sys.time()
  estPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK, fix_phi = phi)
  timeL[3] = Sys.time() - t3start
  ## Uniform
  wtoPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU)
  estPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU, fix_phi = phi)
  ## True
  wtoPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT)
  estPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT, fix_phi = phi)
  ## svm
  wtoPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM)
  estPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM, fix_phi = phi)
      
  ## Fisher's exact test
  t4start = Sys.time()
  fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
  timeL[4] = Sys.time() - t4start
  ## speckle
  t5start = Sys.time()
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
    dplyr::rename(cluster = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(cluster, speckle_pvals)
  timeL[5] = Sys.time() - t5start
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
    dplyr::rename(cluster = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(cluster, speckle_pvals)
  ## diffcyt
  t6start = Sys.time()
  diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$dfRes)
  timeL[6] = Sys.time() - t6start
  ## scDC
  t7start = Sys.time()
  res_scDC <- scDC_noClustering(cellTypes = simulation$dfRes$clusterRes, simulation$dfRes$batch, calCI = TRUE, calCI_method = c("percentile", "BCa", "multinom"),nboot = 1000, verbose = FALSE)
  res_GLM <- fitGLM(res_scDC, c(rep("cond1",rep1*cluster_num),rep("cond2",rep2*cluster_num)), pairwise = FALSE, fixed_only = TRUE, verbose = FALSE)
  timeL[7] = Sys.time() - t7start
  scDCRes_temp = summary(res_GLM$pool_res_fixed)
  scDCRes = scDCRes_temp[c(cluster_num+1,(dim(scDCRes_temp)[1]-cluster_num+2):dim(scDCRes_temp)[1]),]
  ## milo
  t8start = Sys.time()
  milo_res = getMilo(simulation$integratedSamples)
  timeL[8] = Sys.time() - t8start
  miloDF_temp = milo_res$da_results %>% 
    filter(ident_fraction > 0.8) %>%
    mutate(direct = ifelse( logFC > 0  & SpatialFDR < 0.1, "milo_more", "neutral"),
           direct = ifelse( logFC < 0  & SpatialFDR < 0.1, "milo_less", direct)) %>% 
    group_by(ident, direct) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = direct, values_from = n) %>% 
    replace(is.na(.), 0) %>% 
    dplyr::rename(cluster = ident)
  if ("milo_less" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_less = rep(0, nrow(miloDF_temp))}
  if ("milo_more" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_more = rep(0, nrow(miloDF_temp))}
  miloDF = miloDF_temp %>% 
    dplyr::select(cluster, milo_less, neutral, milo_more)
  ## results
  cluster_map = data.frame(cluster = colnames(numb_cond1[,order2]), truth = truthRes) %>% 
    arrange(cluster)
  clusterDF = cluster_map %>% 
    mutate(betabin_null_pvals = as.vector(betabin_null$LRT_pvals),
           estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals),
           wtoPhi_emSVM_pvals = as.vector(wtoPhi_emSVM$LRT_pvals),
           estPhi_emSVM_pvals = as.vector(estPhi_emSVM$LRT_pvals),
           wtoPhi_emT_pvals = as.vector(wtoPhi_emT$LRT_pvals),
           estPhi_emT_pvals = as.vector(estPhi_emT$LRT_pvals),
           wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals),
           estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals),
           wtoPhi_emK_pvals = as.vector(wtoPhi_emK$LRT_pvals),
           estPhi_emK_pvals = as.vector(estPhi_emK$LRT_pvals),
           fisher_pvals = fisher_pvals,
           scDC_pvals = scDCRes$p.value) %>%
    merge(speckleRes, by = "cluster") %>% 
    merge(diffcytP, by = "cluster") %>% 
    left_join(miloDF, by = "cluster") %>% 
    replace(is.na(.), 0)
  clusterRes = rbind(clusterRes, clusterDF)
  
  ## subset data
  posCluster = clusterDF %>% filter(truth == "P") %>% .$cluster
  subsetSamples = subset(simulation$integratedSamples, cells = names(milo_res$nhoodsID))
  subsetSamples = AddMetaData(object = subsetSamples, metadata = milo_res$nhoodsID[Cells(subsetSamples)], col.name = 'nhoods')
  ### Uniform matrix
  simil_matU = create_simMat(nrow(milo_res$da_results), confuse_rate=0.15)
  ## Test
  ### DCATS---betabinLRT
  sim_count = milo_res$counts %>% as.matrix() %>% t()
  nhood_countL[[idx]] = sim_count
  sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
  betabin_null = dcats_GLM(sim_count, sim_design)
  ###  DCATS---betabinLRT with Bias correction from similarity matrix
  phi = getPhi(sim_count[,sample(1:ncol(sim_count), 20)], sim_design)
  estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi)
  wtoPhi_emU = dcats_GLM(sim_count, sim_design, similarity_mat = simil_matU)
  estPhi_emU = dcats_GLM(sim_count, sim_design, similarity_mat = simil_matU, fix_phi = phi)
  ## Fisher's exact test
  fisher_pvals = getFisher(sim_count[1:rep1,], sim_count[(rep1+1):(rep1+rep2),])
  ## speckle
  speckleRes = propeller(clusters = subsetSamples$nhoods, sample = subsetSamples$batch, group = subsetSamples$condition) %>%
    dplyr::rename(Nhood = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(Nhood, speckle_pvals)
  
  nhoodDF = milo_res$da_results %>% 
    mutate(truth = ifelse(ident %in% posCluster, "P", "N"),
           betabin_null_pvals = as.vector(betabin_null$LRT_pvals),
           estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals),
           wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals),
           estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals),
           fisher_pvals = fisher_pvals,
           Nhood = str_c("hoods", Nhood)) %>%
    merge(speckleRes, by = "Nhood")
  nhoodRes = rbind(nhoodRes, nhoodDF)
  timeDF = rbind(timeDF, timeL)
}
```

```{r}
#file_name = str_c("D:/Data/DCATS/simulation/replicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, "para.RData")
file_name = str_c("/storage/holab/linxy/DCATS/simulation/replicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, ".RData")
save(true_countDF, seurat_countDF, knn_matrixL, true_matrixL, svm_matrixL, clusterRes, nhood_countL, nhoodRes, timeDF, file = file_name)
```

```{r}
colnames(true_countDF) = c("P1", "P2", "N1", "N2", "N3", "P3", "N4", "P4", "sim")
true_countDF %>% 
  group_by(sim) %>% 
  mutate(condition = c(rep("Condition 1", rep1), rep("Condition 2", rep2))) %>% 
  pivot_longer(P1:P4, names_to = "cellType", values_to = "count") %>% 
  mutate(proportion = count/3000) %>% 
  ggplot(aes(cellType, proportion)) +
  geom_boxplot(aes(col = condition)) +
  theme(legend.position = "top") + 
  xlab("Cell type")
```

```{r}
colnames(seurat_countDF) = c("P1", "P2", "N1", "N2", "N3", "P3", "N4", "P4", "sim")
seurat_countDF %>% 
  group_by(sim) %>% 
  mutate(condition = c(rep("Condition 1", rep1), rep("Condition 2", rep2))) %>% 
  pivot_longer(P1:P4, names_to = "cellType", values_to = "count") %>% 
  mutate(proportion = count/3000) %>% 
  ggplot(aes(cellType, proportion)) +
  geom_boxplot(aes(col = condition)) +
  theme(legend.position = "top") + 
  xlab("Cell type")
```

cluster level

```{r}
file_name = str_c("D:/Data/DCATS/simulation/replicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, "para.RData")
load(file_name)
methods = colnames(oper[[1]]$clusterDF)[colnames(oper[[1]]$clusterDF) %>% str_detect("_pvals")] %>% str_remove("_pvals")
#methods = colnames(clusterRes)[colnames(clusterRes) %>% str_detect("_pvals")] %>% str_remove("_pvals")
methods = c(methods, "milo")
numb_mthd = length(methods)
mcc = rep(NA, numb_mthd)
auc = rep(NA, numb_mthd)
prauc = rep(NA, numb_mthd)
sensitivity = rep(NA, numb_mthd)
specificity = rep(NA, numb_mthd)
precision = rep(NA, numb_mthd)
F1 = rep(NA, numb_mthd)
clusterRes = data.frame()
nhoodRes = data.frame()
for (idx in 1:length(oper)){
  if (!is.na(oper[[idx]])) {clusterRes = rbind(clusterRes, oper[[idx]]$clusterDF)}
  if (!is.na(oper[[idx]])) {nhoodRes = rbind(nhoodRes, oper[[idx]]$nhoodDF)}
}
truth = clusterRes$truth
clusterRes = clusterRes %>% 
  mutate(milo_main = ifelse(milo_less > milo_more, milo_less, milo_more),
         milo_pct = milo_main/(milo_less + neutral + milo_more),
         milo_diff = abs(milo_less - milo_more)) %>% 
  dplyr::select(-milo_less, -milo_more, - neutral, -milo_main)
for (i in 3:(dim(clusterRes)[2]-1)){
  pred = clusterRes[,i]
  if (colnames(clusterRes)[i] == "milo_pct") {
    pred_res = ifelse(clusterRes$milo_diff > 0, "P", "N")
    auc[i-2] = getROC(clusterRes$truth, 1-pred)$auc
    prauc[i-2] = getPRC(clusterRes$truth, 1-pred)$prauc}
  else {
    pred_res = ifelse(pred < 0.1, "P", "N")
    auc[i-2] = getROC(clusterRes$truth, pred)$auc
    prauc[i-2] = getPRC(clusterRes$truth, pred)$prauc}
  TP <- sum(pred_res=="P"&truth=="P")
  TN <- sum(pred_res=="N"&truth=="N")
  FP <- sum(pred_res=="P"&truth=="N")
  FN <- sum(pred_res=="N"&truth=="P")
  truthN = TN + FP
  truthP = FN + TP
  predP = TP + FP
  predN = FN + TN
  sensitivity[i-2] = TP/truthP
  specificity[i-2] = TN/truthN
  precision[i-2] = TP/predP
  #mcc[i-2] = sqrt(sensitivity[i]*specificity[i]*precision[i]*(TN/(TN+FN))) - sqrt((1-sensitivity[i])*(1-specificity[i])*(FN/predN)*(FP/predP))
  mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
  F1[i-2] = 2*TP/(2*TP+FP+FN)
}
res = data.frame(methods = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision, F1 = F1) %>% 
  arrange(desc(auc)) %>% 
  #filter(methods == "wtoPhi_fullK" | methods == "diffcyt" | methods == "speckle" | methods == "fisher" | methods == "scDC")
print(res)
```

nhoods level

```{r}
load(file_name)
nhoodDF = nhoodDF %>% na.omit() %>% 
  dplyr::rename(milo_pvals = SpatialFDR) %>% 
  filter(ident_fraction > 0.8)  # get nhoods mainly contains one cell type -> 90%
methods = colnames(nhoodDF)[colnames(nhoodDF) %>% str_detect("_pvals")] %>% str_remove("_pvals")
numb_mthd = length(methods)
mcc = rep(NA, numb_mthd)
auc = rep(NA, numb_mthd)
prauc = rep(NA, numb_mthd)
sensitivity = rep(NA, numb_mthd)
specificity = rep(NA, numb_mthd)
precision = rep(NA, numb_mthd)
F1 = rep(NA, numb_mthd)
truth = nhoodDF$truth
select_col = colnames(nhoodDF)[colnames(nhoodDF) %>% str_detect("_pvals")]
for (i in 1:length(select_col)){
  auc[i] = getROC(nhoodDF$truth, nhoodDF[,select_col[i]])$auc
  pred = nhoodDF[,select_col[i]]
  if (i == 1) {pred_res = ifelse(pred < 0.1, "P", "N")}
  else {pred_res = ifelse(pred < 0.1, "P", "N")}
  TP <- sum(pred_res=="P"&truth=="P")
  TN <- sum(pred_res=="N"&truth=="N")
  FP <- sum(pred_res=="P"&truth=="N")
  FN <- sum(pred_res=="N"&truth=="P")
  truthN = TN + FP
  truthP = FN + TP
  predP = TP + FP
  predN = FN + TN
  sensitivity[i] = TP/truthP
  specificity[i] = TN/truthN
  precision[i] = TP/predP
  mcc[i] = sqrt(sensitivity[i]*specificity[i]*precision[i]*(TN/(TN+FN))) - sqrt((1-sensitivity[i])*(1-specificity[i])*(FN/predN)*(FP/predP))
  #mcc[i] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
  F1[i] = 2*TP/(2*TP+FP+FN)
  prauc[i] = getPRC(nhoodDF$truth, nhoodDF[,select_col[i]])$prauc
  
}
res = data.frame(methods = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision, F1 = F1) %>% 
  arrange(desc(auc)) %>% 
  #filter(methods == "wtoPhi_fullK" | methods == "diffcyt" | methods == "speckle" | methods == "fisher" | methods == "scDC")
print(res)
```


```{r}
load(file_name)
nhoodDF_res = nhoodDF %>% 
  na.omit() %>% 
  filter(ident_fraction > 0.8) %>% 
  mutate(milo_res = ifelse(SpatialFDR < 0.1, "P", "N"),
         betabin_null_res = ifelse(betabin_null_pvals < 0.1, "P", "N"),
         estPhi_null_res = ifelse(estPhi_null_pvals < 0.1, "P", "N"),
         wtoPhi_emU_res = ifelse(wtoPhi_emU_pvals < 0.1, "P", "N"),
         estPhi_emU_res = ifelse(estPhi_emU_pvals < 0.1, "P", "N"),
         fisher_res = ifelse(fisher_pvals < 0.1, "P", "N"),
         speckle_res = ifelse(speckle_pvals < 0.1, "P", "N")) %>% 
  pivot_longer(contains("_res"), names_to = "method", values_to = "res") %>% 
  group_by(truth, method, res) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n)) %>%
  dplyr::select(-n) %>% 
  pivot_wider(names_from = res, values_from = freq) %>% 
  mutate()
nhoodDF_res
```


## Simulation with covariate

```{r}
## numbers of replicates for each condition: 15
condition = c(rep("cond1", 10), rep("cond2", 10))
gender = sample(c("female", "male"), 20, replace = TRUE)
age = sample(15:45, 20, replace = TRUE)
design_mat = data.frame(condition, gender, age)
## proportion contribution
prop_cond1 = rep(8,8)
prop_cond2 = c(6, 6, 10, 10, 8, 8, 8, 8)
prop_gender = rep(c(-2, 2, 0, 0), 2)
#prop_age = c(-0.05, rep(0, 2), 0.05, 0.05, rep(0, 2), -0.05)
prop_age = rep(c(-0.05, 0.05, 0, 0), 2)
cond_mat = matrix(c(rep(prop_cond1, 10), rep(prop_cond2, 10)), nrow = 8) %>% t()
gender_mat = matrix(as.numeric(as.factor(gender))-1, ncol = 1) %*% prop_gender
age_mat = matrix(age-15, ncol = 1) %*% prop_age
add_mat = cond_mat + gender_mat + age_mat
prop_mat = add_mat/rowSums(add_mat)
prop_mat
```

```{r, eval=FALSE}
lm = design_mat %>% 
  mutate(y = prop_mat[,5]) %>% 
  lm(y~., data = .)
summary(lm)
lm = design_mat %>% 
  mutate(y = prop_mat[,4]) %>% 
  lm(y~., data = .)
summary(lm)
```

```{r}
cluster_num = 8  # numbers of clusters
concentration = 100 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.6
simulation_times = 30
sample_size1 = 3000
sample_size2 = 3000
cell_pool = "splatter"  # cell pool used, can be selected from ("SPAR", "splatter", "realWorld")
more_negative = ""
truthRes = c(rep("P", 4), rep("N", 4))
```

```{r, message=FALSE, warning=FALSE}
source("functionsV2.r")
source("glm.R")     # for scDC
options(future.globals.maxSize = 15000 * 1024^2)
```

```{r}
if (cell_pool == "splatter"){
  load(str_c("/storage/holab/linxy/DCATS/cells_pool", as.character(cluster_num), "_splatter.RData"))
  #load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_splatter_test.RData"))
} else if (cell_pool == "SPAR") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_SPARSim.RData"))
  
} else if (cell_pool == "realWorld") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_realWorld.RData"))
}
```

```{r}
library(foreach)
library(doParallel)

# Create class which holds multiple results for each loop iteration.
# Each loop iteration populates nine properties: $clusterDF and $nhoodDF......
# For a great tutorial on S3 classes, see: 
# http://www.cyclismo.org/tutorial/R/s3Classes.html#creating-an-s3-class
multiResultClass <- function(conditionDF=NULL,genderDF=NULL,ageDF=NULL,time=NULL,true_count=NULL,nhood_count=NULL,seurat_count=NULL,knn_matrix=NULL,true_matrix=NULL,svm_matrix=NULL)
{
  me <- list(
    conditionDF=conditionDF,
    genderDF=genderDF,
    ageDF=ageDF,
    time=time,
    true_count=true_count,
    nhood_count=nhood_count,
    seurat_count=seurat_count,
    knn_matrix=knn_matrix,
    true_matrix=true_matrix,
    svm_matrix=svm_matrix
  )

  ## Set the name for the class
  class(me) <- append(class(me),"multiResultClass")
  return(me)
}

unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}

#oper <- foreach(i=1:10) %dopar% {
#   result <- multiResultClass()
#   result$result1 <- i+1
#   result$result2 <- i+2
#   return(result)
#}
#oper1 <- oper[[1]]$result1
#oper2 <- oper[[1]]$result2
```

```{r}
#setup parallel backend to use many processors
#cores=detectCores()
cl <- makeCluster(8) #not to overload your computer
registerDoParallel(cl)
startTime = Sys.time()
set.seed(1)
oper <- foreach(sim = 1:simulation_times, .packages=c("tidyverse", "Seurat", "DCATS", "speckle", "diffcyt", "scDC", "tidymodels", "miloR", "SingleCellExperiment"), .verbose = TRUE) %dopar% {
  result <- multiResultClass()  # where to save output
  timeL = rep(NA, 8) # DCATS w/wto similarity matrix, fisher, speckle, diffcyt, scDC
  ## simulation
  simulation = simulator_propM(totalV = sample(sample_size1:sample_size2, nrow(prop_mat)), prop_mat, setresolu, sim_mat, design_mat)
  if (is.na(simulation)[1] == TRUE){
    return(NA)
  }
  result$true_count = c(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2)
  ## data convert
  numb_cond = simulation$dfRes %>% 
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    mutate(batch = str_remove(batch, "rep") %>% as.numeric()) %>% 
    arrange(batch) %>% 
    column_to_rownames(var = "batch")
  numb_cond[is.na(numb_cond)] <- 0
  conf.mat <- table(simulation$trueLabels, Idents(simulation$integratedSamples))
  true.conf <- conf.mat/rowSums(conf.mat)
  library(clue)
  order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
  L_sum = colSums(numb_cond)
  decider = sum(L_sum > nrow(prop_mat))
  if (decider != cluster_num){
    return(NA)
  } # if one cluster has least than 10 cells in one condition, then won't continue
  result$seurat_count = numb_cond[,order2]
  ## Get matrices
  ### KNN matrix
  graphs = simulation$integratedSamples@graphs$RNA_snn
  labels = Idents(simulation$integratedSamples)
  knn_mat = knn_simMat(graphs, labels)
  order1 = colnames(numb_cond)
  simil_matK = knn_mat[order1, order1]
  result$knn_matrix = simil_matK
  ### True matrix
  simil_matT = true.conf[,order2]
  result$true_matrix = simil_matT
  ### Uniform matrix
  simil_matU = create_simMat(cluster_num, confuse_rate=0.1)
  ### svm&rf
  mlDF = simulation$integratedSamples@reductions$pca@cell.embeddings %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column("cellID") %>% 
    merge(simulation$dfRes, by = "cellID") %>% 
    dplyr::select(-cellID)
  set.seed(123)
  simil_matSVM = svm_simMat(mlDF)
  result$svm_matrix = simil_matSVM
      
  ## Test
  ### DCATS---betabinLRT
  sim_count = numb_cond %>% as.matrix()
  sim_design = design_mat
  t1start = Sys.time()
  betabin_null = dcats_GLM(sim_count, sim_design, base_model = "FULL")
  timeL[1] = Sys.time() - t1start
  ###  DCATS---betabinLRT with Bias correction from similarity matrix
  phi = getPhi(sim_count, sim_design)
  t2start = Sys.time()
  estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi, base_model = "FULL")
  timeL[2] = Sys.time() - t2start
  ## KNN
  wtoPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK, base_model = "FULL")
  t3start = Sys.time()
  estPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK, fix_phi = phi, base_model = "FULL")
  timeL[3] = Sys.time() - t3start
  ## Uniform
  wtoPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU, base_model = "FULL")
  estPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU, fix_phi = phi, base_model = "FULL")
  ## True
  wtoPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT, base_model = "FULL")
  estPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT, fix_phi = phi, base_model = "FULL")
  ## svm
  wtoPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM, base_model = "FULL")
  estPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM, fix_phi = phi, base_model = "FULL")
  ## Fisher's exact test
  numb_cond1 = numb_cond[which(design_mat$condition == 'cond1'),]
  numb_cond2 = numb_cond[which(design_mat$condition == 'cond2'),]
  t4start = Sys.time()
  fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
  timeL[4] = Sys.time() - t4start
  ## speckle
  t5start = Sys.time()
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% dplyr::rename(cluster = BaselineProp.clusters,speckle_pvals = FDR) %>%
    dplyr::select(cluster, speckle_pvals)
  timeL[5] = Sys.time() - t5start
  ## diffcyt
  t6start = Sys.time()
  diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$dfRes)
  timeL[6] = Sys.time() - t6start
  ## scDC
  t7start = Sys.time()
  res_scDC <- scDC_noClustering(cellTypes = simulation$dfRes$clusterRes, simulation$dfRes$batch, calCI = TRUE, calCI_method = c("percentile", "BCa", "multinom"),nboot = 1000, verbose = FALSE)
  res_GLM <- fitGLM(res_scDC, c(rep("cond1",10*cluster_num),rep("cond2",10*cluster_num)), pairwise = FALSE, fixed_only = TRUE, verbose = FALSE)
  timeL[7] = Sys.time() - t7start
  scDCRes_temp = summary(res_GLM$pool_res_fixed)
  scDCRes = scDCRes_temp[c(cluster_num+1,(dim(scDCRes_temp)[1]-cluster_num+2):dim(scDCRes_temp)[1]),]
  ## milo
  t8start = Sys.time()
  milo_res = getMilo(simulation$integratedSamples)
  timeL[8] = Sys.time() - t8start
  miloDF_temp = milo_res$da_results %>% 
    filter(ident_fraction > 0.8) %>%
    mutate(direct = ifelse( logFC > 0  & FDR < 0.1, "milo_more", "neutral"),
           direct = ifelse( logFC < 0  & FDR < 0.1, "milo_less", direct)) %>% 
    group_by(ident, direct) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = direct, values_from = n) %>% 
    replace(is.na(.), 0) %>% 
    dplyr::rename(cluster = ident)
  if ("milo_less" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_less = rep(0, nrow(miloDF_temp))}
  if ("milo_more" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_more = rep(0, nrow(miloDF_temp))}
  miloDF = miloDF_temp %>% 
    dplyr::select(cluster, milo_less, neutral, milo_more)
  ## results
  cluster_map = data.frame(cluster = colnames(numb_cond1[,order2]), truth = truthRes) %>% 
        arrange(cluster)
      conditionDF = cluster_map %>% 
        mutate(betabin_null_pvals = as.vector(betabin_null$LRT_pvals[,1]),
               estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals[,1]),
               wtoPhi_emSVM_pvals = as.vector(wtoPhi_emSVM$LRT_pvals[,1]),
               estPhi_emSVM_pvals = as.vector(estPhi_emSVM$LRT_pvals[,1]),
               wtoPhi_emT_pvals = as.vector(wtoPhi_emT$LRT_pvals[,1]),
               estPhi_emT_pvals = as.vector(estPhi_emT$LRT_pvals[,1]),
               wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals[,1]),
               estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals[,1]),
               wtoPhi_emK_pvals = as.vector(wtoPhi_emK$LRT_pvals[,1]),
               estPhi_emK_pvals = as.vector(estPhi_emK$LRT_pvals[,1]),
               fisher_pvals = fisher_pvals,
               scDC_pvals = scDCRes$p.value) %>%
        merge(speckleRes, by = "cluster") %>% 
        merge(diffcytP, by = "cluster") %>% 
        left_join(miloDF, by = "cluster") %>% 
        replace(is.na(.), 0)
      result$conditionDF = conditionDF
      genderDF = data.frame(cluster = colnames(numb_cond1[,order2]), truth = rep(c("P", "P", "N", "N"), 2)) %>%
        arrange(cluster) %>% 
        mutate(betabin_null_pvals = as.vector(betabin_null$LRT_pvals[,2]),
               estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals[,2]),
               wtoPhi_emSVM_pvals = as.vector(wtoPhi_emSVM$LRT_pvals[,2]),
               estPhi_emSVM_pvals = as.vector(estPhi_emSVM$LRT_pvals[,2]),
               wtoPhi_emT_pvals = as.vector(wtoPhi_emT$LRT_pvals[,2]),
               estPhi_emT_pvals = as.vector(estPhi_emT$LRT_pvals[,2]),
               wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals[,2]),
               estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals[,2]),
               wtoPhi_emK_pvals = as.vector(wtoPhi_emK$LRT_pvals[,2]),
               estPhi_emK_pvals = as.vector(estPhi_emK$LRT_pvals[,2]))
      result$genderDF = genderDF
      
      ageDF = data.frame(cluster = colnames(numb_cond1[,order2]), truth = rep(c("P", "P", "N", "N"), 2)) %>%
        arrange(cluster) %>% 
        mutate(betabin_null_pvals = as.vector(betabin_null$LRT_pvals[,3]),
               estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals[,3]),
               wtoPhi_emSVM_pvals = as.vector(wtoPhi_emSVM$LRT_pvals[,3]),
               estPhi_emSVM_pvals = as.vector(estPhi_emSVM$LRT_pvals[,3]),
               wtoPhi_emT_pvals = as.vector(wtoPhi_emT$LRT_pvals[,3]),
               estPhi_emT_pvals = as.vector(estPhi_emT$LRT_pvals[,3]),
               wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals[,3]),
               estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals[,3]),
               wtoPhi_emK_pvals = as.vector(wtoPhi_emK$LRT_pvals[,3]),
               estPhi_emK_pvals = as.vector(estPhi_emK$LRT_pvals[,3]))
      result$ageDF = ageDF
      result$time = timeL
  return(result)
      }
stopCluster(cl) 
foreachtime = Sys.time() - startTime
```

```{r}
#file_name = str_c("D:/Data/DCATS/simulation/replicates10&10_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, "_para.RData")
file_name = str_c("/storage/holab/linxy/DCATS/simulation/replicates10&10_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, "_para.RData")
save(oper, file = file_name)
```

```{r}
load(file_name)
simulationDF = simulationDF %>% na.omit()
methods = colnames(simulationDF)[3:dim(simulationDF)[2]] %>% str_remove("_pvals")
numb_mthd = length(methods)
mcc = rep(NA, numb_mthd)
auc = rep(NA, numb_mthd)
prauc = rep(NA, numb_mthd)
sensitivity = rep(NA, numb_mthd)
specificity = rep(NA, numb_mthd)
precision = rep(NA, numb_mthd)
truth = simulationDF$truth
for (i in 3:dim(simulationDF)[2]){
  auc[i-2] = getROC(simulationDF$truth, simulationDF[,i])$auc
  pred = simulationDF[, i]
  pred_res = ifelse(pred < 0.05, "P", "N")
  TP <- sum(pred_res=="P"&truth=="P")
  TN <- sum(pred_res=="N"&truth=="N")
  FP <- sum(pred_res=="P"&truth=="N")
  FN <- sum(pred_res=="N"&truth=="P")
  truthN = TN + FP
  truthP = FN + TP
  predP = TP + FP
  predN = FN + TN
  mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
  prauc[i-2] = getPRC(simulationDF$truth, simulationDF[,i])$prauc
  sensitivity[i-2] = TP/truthP
  specificity[i-2] = TN/truthN
  precision[i-2] = TP/predP
}
res = data.frame(methods = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision) %>% 
  arrange(desc(auc)) %>% 
  #filter(methods == "wtoPhi_fullK" | methods == "diffcyt" | methods == "speckle" | methods == "fisher" | methods == "scDC")
print(res)
```

## Simulation with all differential abundance cell type increase

```{r, message=FALSE, warning=FALSE}
library(Seurat)
library(SeuratWrappers)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
library(MCMCpack)
#library(scdney)
library(scDC)
library(tidymodels)  ## for DCATS
library(miloR)
library(SingleCellExperiment)
```

```{r}
cluster_num = 8  # numbers of clusters
setresolu = 0.6
rep1 = 3
rep2 = 3
simulation_times = 30
concentration = 30
sample_size1 = 3000
sample_size2 = 3000
cell_pool = "splatter"  # cell pool used, can be selected from ("SPAR", "splatter", "realWorld")
more_negative = ""
```

```{r}
countC1 = rep(8,8)
countC2 = c(8, 8, 12, 12, 10, 10, 8, 8)
probC1 = countC1/sum(countC1)
probC2 = countC2/sum(countC2)
truthRes = c("F", "F", "T", "T", "T", "T", "F", "F")
```

```{r, message=FALSE, warning=FALSE}
source("functionsV2.r")
source("glm.R")     # for scDC
options(future.globals.maxSize = 15000 * 1024^2)
```

```{r}
if (cell_pool == "splatter"){
  #load(str_c("D:/#Data/DCATS/cells_pool", as.character(cluster_num), "_splatter.RData"))
  load(str_c("/storage/holab/linxy/DCATS/cells_pool", as.character(cluster_num), "_splatter.RData"))
} else if (cell_pool == "SPAR") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_SPARSim.RData"))
  
} else if (cell_pool == "realWorld") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_realWorld.RData"))
}
```

```{r}
simulation = simulator_base(rep(3000,3), rep(3000,3), probC1*1, probC2*1, diag(nrow = 8, ncol = 8))
sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
print(simulation$numb_cond1/rowSums(simulation$numb_cond1))
print(simulation$numb_cond2/rowSums(simulation$numb_cond2))
res = dcats_new(rbind(simulation$numb_cond1, simulation$numb_cond2), sim_design, reference = c(1,7,8))
res$LRT_pvals
```
```{r}
set.seed(123)
  K <- 3
  totals1 = rep(300, 4)
  totals2 = rep(300, 3)
  diri_s1 = rep(1/K, K) * 200
  diri_s2 = c(1/3, 1/2, 1/6) * 200
  simil_mat = create_simMat(K, confuse_rate=0.1)
  sim_dat <- DCATS::simulator_base(totals1, totals2, diri_s1, diri_s2, simil_mat)
  sim_count = rbind(sim_dat$numb_cond1, sim_dat$numb_cond2)
  sim_design = matrix(c("g1", "g1", "g1", "g1", "g2", "g2", "g2"), ncol = 1)
  res = dcats_GLM(sim_count, sim_design)
  res$LRT_pvals
```


```{r}
simulation = simulator_noInt(totals1 = runif(rep1, sample_size1, sample_size2), totals2 = runif(rep2, sample_size1, sample_size2), probC1, probC2, setresolu, sim_mat)
result$true_count = rbind(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2)
conf.mat <- table(simulation$trueLabels, Idents(simulation$integratedSamples))
true.conf <- conf.mat/rowSums(conf.mat)
library(clue)
order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
simil_matT = true.conf[,order2]
simil_matT
sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
res = dcats_new(result$true_count, sim_design, reference = c(1,7,8))
res$LRT_pvals
```


```{r}
result = list()
timeL = rep(NA, 8) # DCATS w/wto similarity matrix, fisher, speckle, diffcyt, scDC
  ## simulation
  simulation = simulator_noInt(totals1 = runif(rep1, sample_size1, sample_size2), totals2 = runif(rep2, sample_size1, sample_size2), probC1, probC2, setresolu, sim_mat)
  if (is.na(simulation)[1] == TRUE){
    return(NA)
  }
  result$true_count = rbind(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2)
  ## data convert
  numb_cond1 = simulation$dfRes %>% 
    filter(condition == "Cond1") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond2 = simulation$dfRes %>% 
    filter(condition == "Cond2") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond1[is.na(numb_cond1)] <- 0
  numb_cond2[is.na(numb_cond2)] <- 0
  conf.mat <- table(simulation$trueLabels, Idents(simulation$integratedSamples))
  true.conf <- conf.mat/rowSums(conf.mat)
  library(clue)
  order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
  L_sum1 = colSums(numb_cond1)
  L_sum2 = colSums(numb_cond2)
  decider = sum(L_sum1 > 10)+sum(L_sum2 > 10)
  if (decider != cluster_num*2){
    return(NA)
  } # if one cluster has least than 10 cells in one condition, then won't continue
  result$seurat_count = list(cond1 = numb_cond1[,order2], cond2 = numb_cond2[,order2])
  ## Get matrices
  ### KNN matrix
  graphs = simulation$integratedSamples@graphs$RNA_snn
  labels = Idents(simulation$integratedSamples)
  knn_mat = knn_simMat(graphs, labels)
  order1 = colnames(numb_cond1)
  simil_matK = knn_mat[order1, order1]
  result$knn_matrix = simil_matK
  ### True matrix
  simil_matT = true.conf[,order2]
  result$true_matrix = simil_matT
  ### Uniform matrix
  simil_matU = create_simMat(cluster_num, confuse_rate=0.1)
  ### svm&rf
  mlDF = simulation$integratedSamples@reductions$pca@cell.embeddings %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column("cellID") %>% 
    merge(simulation$dfRes, by = "cellID") %>% 
    dplyr::select(-cellID)
  set.seed(123)
  simil_matSVM = svm_simMat(mlDF)
  result$svm_matrix = simil_matSVM
      
  ## Test
  ### DCATS---betabinLRT
  sim_count = rbind(numb_cond1, numb_cond2) %>% as.matrix()
  sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
  t1start = Sys.time()
  betabin_null = dcats_GLM(sim_count, sim_design)
  betabin_null_ref = dcats_GLM(sim_count, sim_design, reference = "G")
  timeL[1] = Sys.time() - t1start
  ###  DCATS---betabinLRT with Bias correction from similarity matrix
  phi = getPhi(sim_count, sim_design)
  t2start = Sys.time()
  estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi)
  timeL[2] = Sys.time() - t2start
  ## KNN
  wtoPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK)
  t3start = Sys.time()
  estPhi_emK = dcats_GLM(sim_count, sim_design, simil_matK, fix_phi = phi)
  timeL[3] = Sys.time() - t3start
  ## Uniform
  wtoPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU)
  estPhi_emU = dcats_GLM(sim_count, sim_design, simil_matU, fix_phi = phi)
  ## True
  wtoPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT)
  estPhi_emT = dcats_GLM(sim_count, sim_design, simil_matT, fix_phi = phi)
  wtoPhi_emT_ref1 = dcats_GLM(sim_count, sim_design, simil_matT, reference = c("E"))
  estPhi_emT_ref1 = dcats_GLM(sim_count, sim_design, simil_matT, fix_phi = phi, reference = c("E"))
  wtoPhi_emT_ref2 = dcats_new(sim_count, sim_design, simil_matT, reference = c("E", "H"))
  estPhi_emT_ref2 = dcats_new(sim_count, sim_design, simil_matT, fix_phi = phi, reference = c("E", "H"))
  ## svm
  wtoPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM)
  estPhi_emSVM = dcats_GLM(sim_count, sim_design, simil_matSVM, fix_phi = phi)
      
  ## Fisher's exact test
  t4start = Sys.time()
  fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
  timeL[4] = Sys.time() - t4start
  ## speckle
  t5start = Sys.time()
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
    dplyr::rename(cluster = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(cluster, speckle_pvals)
  timeL[5] = Sys.time() - t5start
  speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
    dplyr::rename(cluster = BaselineProp.clusters, speckle_pvals = FDR) %>%
    dplyr::select(cluster, speckle_pvals)
  ## diffcyt
  t6start = Sys.time()
  diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$dfRes)
  timeL[6] = Sys.time() - t6start
  ## scDC
  t7start = Sys.time()
  res_scDC <- scDC_noClustering(cellTypes = simulation$dfRes$clusterRes, simulation$dfRes$batch, calCI = TRUE, calCI_method = c("percentile", "BCa", "multinom"),nboot = 1000, verbose = FALSE)
   res_GLM <- fitGLM(res_scDC, c(rep("cond1",rep1*cluster_num),rep("cond2",rep2*cluster_num)), pairwise = FALSE, fixed_only = TRUE, verbose = FALSE)
  timeL[7] = Sys.time() - t7start
  scDCRes_temp = summary(res_GLM$pool_res_fixed)
  scDCRes = scDCRes_temp[c(cluster_num+1,(dim(scDCRes_temp)[1]-cluster_num+2):dim(scDCRes_temp)[1]),]
  ## milo
  t8start = Sys.time()
  milo_res = getMilo(simulation$integratedSamples)
  timeL[8] = Sys.time() - t8start
  miloDF_temp = milo_res$da_results %>% 
    filter(ident_fraction > 0.8) %>%
    mutate(direct = ifelse( logFC > 0  & SpatialFDR < 0.1, "milo_more", "neutral"),
           direct = ifelse( logFC < 0  & SpatialFDR < 0.1, "milo_less", direct)) %>% 
    group_by(ident, direct) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = direct, values_from = n) %>% 
    replace(is.na(.), 0) %>% 
    dplyr::rename(cluster = ident)
  if ("milo_less" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_less = rep(0, nrow(miloDF_temp))}
  if ("milo_more" %!in% colnames(miloDF_temp)) {miloDF_temp$milo_more = rep(0, nrow(miloDF_temp))}
  miloDF = miloDF_temp %>% 
    dplyr::select(cluster, milo_less, neutral, milo_more)
  ## results
  cluster_map = data.frame(cluster = colnames(numb_cond1[,order2]), truth = truthRes) %>% 
    arrange(cluster)
  clusterDF = cluster_map %>% 
    left_join(miloDF, by = "cluster") %>% 
    mutate(betabin_null_pvals = as.vector(betabin_null$LRT_pvals),
           estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals),
           wtoPhi_emSVM_pvals = as.vector(wtoPhi_emSVM$LRT_pvals),
           estPhi_emSVM_pvals = as.vector(estPhi_emSVM$LRT_pvals),
           wtoPhi_emT_pvals = as.vector(wtoPhi_emT$LRT_pvals),
           estPhi_emT_pvals = as.vector(estPhi_emT$LRT_pvals),
           wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals),
           estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals),
           wtoPhi_emK_pvals = as.vector(wtoPhi_emK$LRT_pvals),
           estPhi_emK_pvals = as.vector(estPhi_emK$LRT_pvals),
           wtoPhi_emT_ref1_pvals = as.vector(wtoPhi_emT_ref1$LRT_pvals),
           estPhi_emT_ref1_pvals = as.vector(estPhi_emT_ref1$LRT_pvals),
           wtoPhi_emT_ref2_pvals = as.vector(wtoPhi_emT_ref2$LRT_pvals),
           estPhi_emT_ref2_pvals = as.vector(estPhi_emT_ref2$LRT_pvals),
           fisher_pvals = fisher_pvals,
           scDC_pvals = scDCRes$p.value) %>%
    merge(speckleRes, by = "cluster") %>% 
    merge(diffcytP, by = "cluster") %>% 
    replace(is.na(.), 0)
  result$clusterDF = clusterDF


```

```{r}
clusterDF = clusterDF %>% 
    mutate(milo_main = ifelse(milo_less > milo_more, milo_less, milo_more),
           milo_pct = milo_main/(milo_less + neutral + milo_more),
           milo_diff = abs(milo_less - milo_more)) %>% 
    dplyr::select(-milo_less, -milo_more, - neutral, -milo_main)
methods = colnames(clusterDF)[colnames(clusterDF) %>% str_detect("_pvals")] %>% str_remove("_pvals")
  methods = c(methods, "milo")
  numb_mthd = length(methods)
  mcc = rep(NA, numb_mthd)
  auc = rep(NA, numb_mthd)
  prauc = rep(NA, numb_mthd)
  sensitivity = rep(NA, numb_mthd)
  specificity = rep(NA, numb_mthd)
  precision = rep(NA, numb_mthd)
  F1 = rep(NA, numb_mthd)

  truth = clusterDF$truth
  for (i in 3:(dim(clusterDF)[2]-1)){
    pred = clusterDF[,i]
    if (colnames(clusterDF)[i] == "milo_pct") {
      pred_res = ifelse(clusterDF$milo_diff > 0, "P", "N")
      auc[i-2] = getROC(clusterDF$truth, 1-pred)$auc
      prauc[i-2] = getPRC(clusterDF$truth, 1-pred)$prauc}
    else {
      pred_res = ifelse(pred < 0.1, "P", "N")
      auc[i-2] = getROC(clusterDF$truth, pred)$auc
      prauc[i-2] = getPRC(clusterDF$truth, pred)$prauc}
    TP <- sum(pred_res=="P"&truth=="P")
    TN <- sum(pred_res=="N"&truth=="N")
    FP <- sum(pred_res=="P"&truth=="N")
    FN <- sum(pred_res=="N"&truth=="P")
    truthN = TN + FP
    truthP = FN + TP
    predP = TP + FP
    predN = FN + TN
    sensitivity[i-2] = TP/truthP
    specificity[i-2] = TN/truthN
    precision[i-2] = TP/predP
    #mcc[i-2] = sqrt(sensitivity[i]*specificity[i]*precision[i]*(TN/(TN+FN))) - sqrt((1-sensitivity[i])*(1-specificity[i])*(FN/predN)*(FP/predP))
    mcc[i-2] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
    F1[i-2] = 2*TP/(2*TP+FP+FN)
    }
  data.frame(method = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision, F1 = F1) %>% 
    arrange(desc(auc))
```

```{r}
count_mat = sim_count
design_mat = sim_design
similarity_mat = simil_matT
```






