---
title: "Simulation in Different Scenario(6 clusters)"
author: "Xinyi Lin"
date: "9/27/2020"
output: html_document
---

Problems need to solve:

1. DCATS: label problems

2. scDC: functions don't work

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
```

```{r}
source("functions.r")
```

## Different batch size

Batch sizes are 500, 1000, 1500, 2000.

```{r}
set.seed(123)
probNor = c(0.1, 0.2, 0.1, 0.2, 0.2, 0.2)
probMut = c(0.1, 0.2, 0.05, 0.1, 0.25, 0.3)
de_prob = c(0.5,0.5,0.1, 0.1, 0.1, 0.1)

batch_size_list = seq(1000,2500,500)
setresolu_list = c(0.5, 0.3, 0.3, 0.4)
```

```{r,warning=FALSE,message=FALSE}
for (i in 1:4) {
  batch_size = batch_size_list[i]
  setresolu = setresolu_list[i]
  
  sim_list = simualtion(probNor, probMut, de_prob, batch_size)
  integratedSamples = runSeurat(sim_list, batch_size, setresolu)
  conf.mat<-table(Idents(integratedSamples), sim_list$origLabels)
  print(conf.mat)
  plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
  print(plot)
  Res = getPandTime(integratedSamples, sim_list)
  print(Res)
}
```

## Different de.prob

The de.prob of cluster B, C are 0.02, 0.04, 0.06, 0.08.

When de.prob equals to 0.04, only the fisher's exact test give the "correct" result.

```{r}
set.seed(123)
probNor = c(0.1, 0.2, 0.1, 0.2, 0.2, 0.2)
probMut = c(0.1, 0.2, 0.05, 0.1, 0.25, 0.3)
batch_size = 1000

de_prob_list = seq(0.02, 0.10, 0.02)
setresolu_list = c(0.4, 0.4, 0.4, 0.3, 0.3)
```

```{r,warning=FALSE,message=FALSE}
for (i in 1:5) {
  de_prob = c(0.5,0.5,0.1, 0.1, de_prob_list[i], de_prob_list[i])
  setresolu = setresolu_list[i]
  
  sim_list = simualtion(probNor, probMut, de_prob, batch_size)
  integratedSamples = runSeurat(sim_list, batch_size, setresolu)
  conf.mat<-table(Idents(integratedSamples), sim_list$origLabels)
  print(conf.mat)
  plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
  print(plot)
  Res = getPandTime(integratedSamples, sim_list)
  print(Res)
}
```

## negative 

```{r}
probNor = c(0.1, 0.2, 0.1, 0.2, 0.2, 0.2)
probMut = c(0.1, 0.2, 0.1, 0.2, 0.2, 0.2)
setresolu = 0.5
batch_size = 1000
de_prob = c(0.5,0.5,0.1, 0.1, 0.05, 0.05)
```

```{r,warning=FALSE,message=FALSE}
sim_list = simualtion(probNor, probMut, de_prob, batch_size)
integratedSamples = runSeurat(sim_list, batch_size, setresolu)
conf.mat<-table(Idents(integratedSamples), sim_list$origLabels)
print(conf.mat)
plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
print(plot)
Res = getPandTime(integratedSamples, sim_list)
print(Res)
```

## Codes

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```