---
title: "Simulation Codes"
output: html_document
---

## Theoretical Simulation

In the following simulation, 1) the cluster numbers(K) is 3; 2) number of replicates is 7 and 6 in condition 1 and 2; 3) sample sizes of each replicates follow a uniform distribution with range from 500 to 2000.

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
library(MCMCpack)
```

```{r}
source("functionsV2.r")
```

```{r}
K = 3  # number of cluster
totals1 = ceiling(runif(7, 500, 2000))  # number of replicates + sample size in each replicate
totals2 = ceiling(runif(6, 500, 2000))
diri_s1 = c(1/3, 1/3, 1/3) * 20  # True proportions + concentration
diri_s2 = c(1/3, 1/2, 1/6) * 20
simil_mat = get_similarity_mat(K, confuse_rate=0.2)  # similarity matrix used in simulator to introduce misclassification
```

```{r}
set.seed(123)
simulationDF = data.frame()
for (i in 1:50){
  sim_dat <- DCATS::simulator_base(totals1, totals2, diri_s1, diri_s2, simil_mat)
  ## introduce more misclassification manually
  rate1 = runif(dim(sim_dat$numb_cond1)[1], -0.2, 0.2)
  change_num = (sim_dat$numb_cond1[,1]*rate1) %>% round()
  sim_dat$numb_cond1[,1] = sim_dat$numb_cond1[,1] - change_num
  sim_dat$numb_cond1[,3] = sim_dat$numb_cond1[,3] + change_num
  
  rate2 = runif(dim(sim_dat$numb_cond2)[1], -0.2, 0.2)
  change_num = (sim_dat$numb_cond2[,1]*rate2) %>% round()
  sim_dat$numb_cond2[,1] = sim_dat$numb_cond2[,1] - change_num
  sim_dat$numb_cond2[,3] = sim_dat$numb_cond2[,3] + change_num
  ## calculate true matrix
  change_rate = (sum(rate1*sim_dat$numb_cond1[,1]) + sum(rate2*sim_dat$numb_cond2[,2]))/(sum(sim_dat$numb_cond1[,1]) + sum(sim_dat$numb_cond2[,1]))
  if (change_rate > 0){
    simil_matT = rbind(c(1-change_rate, 0, change_rate), c(0, 1, 0), c(0, 0, 1))
} else {
  simil_matT = rbind(c(1, 0, 0), c(0, 1, 0), c(-change_rate, 0, 1+change_rate))
}
  ## DCATS---betabinLRT
  betabin_noBC = betabinLRT_rw(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), bias_corr = FALSE)
  ##  DCATS---betabinLRT with Bias correction from similarity matrix
  simil_matI = get_similarity_mat(K, confuse_rate=0)
  simil_matU = get_similarity_mat(K, confuse_rate=0.1)
  betabin_wBC_I = betabinLRT_rw(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), bias_corr = TRUE, similarity_mat = simil_matI)
  betabin_wBC_U = betabinLRT_rw(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), bias_corr = TRUE, similarity_mat = simil_matU)
  betabin_wBC_T = betabinLRT_rw(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), bias_corr = TRUE, similarity_mat = simil_matT)
  ## DCATS---betabin with similarity matrix (backward-forward)
  betabin_wMI = dcats_betabin(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), similarity_mat = simil_matI, n_samples = 100, binom_only = FALSE)
  betabin_wMU = dcats_betabin(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), similarity_mat = simil_matU, n_samples = 100, binom_only = FALSE)
  betabin_wMT = dcats_betabin(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), similarity_mat = simil_matT, n_samples = 100, binom_only = FALSE)
  bin_wMI = dcats_betabin(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), similarity_mat = simil_matI, n_samples = 100)
  bin_wMU = dcats_betabin(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), similarity_mat = simil_matU, n_samples = 100)
  bin_wMT = dcats_betabin(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2), similarity_mat = simil_matT, n_samples = 100)
  ## Fisher's exact test
  fisher_pvals = getFisher(as.matrix(sim_dat$numb_cond1), as.matrix(sim_dat$numb_cond2))
  all_res = data.frame(cluster = c("A", "B", "C"), truth = c("N", "P", "P")) %>% 
    mutate(betabin_noBC_pvals = betabin_noBC$pvals,
           betabin_wBCI_pvals = betabin_wBC_I$pvals,
           betabin_wBCU_pvals = betabin_wBC_U$pvals,
           betabin_wBCT_pvals = betabin_wBC_T$pvals,
           betabin_wMI_pvals = betabin_wMI$pvals,
           betabin_wMU_pvals = betabin_wMU$pvals,
           betabin_wMT_pvals = betabin_wMT$pvals,
           bin_wMI_pvals = bin_wMI$pvals,
           bin_wMU_pvals = bin_wMU$pvals,
           bin_wMT_pvals = bin_wMT$pvals,
           fisher_pvals = fisher_pvals)
  simulationDF = rbind(simulationDF, all_res)
}
head(simulationDF)
```

```{r}
library(pROC)
methods = colnames(simulationDF)[3:13]
roc_rose <- plot(roc(simulationDF$truth, simulationDF[,3]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .73, print.auc.x = .7, col = 1)
graphics::text(0.1, 0.7, paste(methods[1]), col=1)
for (i in 2:11){
  roc_rose <- plot(roc(simulationDF$truth, simulationDF[,i+2]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .73-(i-1)*0.07, print.auc.x = .7, col = i, add = TRUE)
  graphics::text(0.1, 0.7-(i-1)*0.07, paste(methods[i]), col=i)
}
```

## Simulation with transcriptome information

```{r, message=FALSE, warning=FALSE}
library(splatter)
library(Seurat)
library(SeuratWrappers)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
library(MCMCpack)
library(scdney)
```

```{r, message=FALSE, warning=FALSE}
source("functionsV2.r")
source("glm.R")     # for scDC
```

```{r}
cell_pool = "mis1"  # cell pool used
cluster_num = 3  # numbers of clusters
probC1 = c(1/3, 1/3, 1/3)  # True proportions
probC2 = c(1/3, 1/2, 1/6)
concentration = 50 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.2
rep1 = 7
rep2 = 6
simulation_times = 50
```

```{r}
if (cell_pool == "discrete"){
  load("./data/cells_pool3.RData")
} else if (cell_pool == "mis1") {
    load("./data/cells_pool3_close.RData")
}
```

```{r, message=FALSE, warning=FALSE}
## output data
simulationDF = data.frame()  # data frame to store test result
time = matrix(NA, nrow = simulation_times, ncol = 6) # matrix contains time for each test need in each simulation
true_countL = vector(mode = "list", length = simulation_times) # list contains the count table of each true cluster
seurat_countL = vector(mode = "list", length = simulation_times) # list contains the count table of each cluster defined by seurat
knn_matrixL = vector(mode = "list", length = simulation_times) # list contains the knn matrix getting from each simulation

set.seed(123)
for (i in 1:simulation_times){
  timeL = rep(NA, 6) # DCATS w/wto simularity matrix, fisher, speckle, diffcyt, scDC
  ## simulation
  simulation = simulator_fastMNN(totals1 = runif(rep1, 1000, 1500), totals2 = runif(rep2, 1000, 1500), probC1, probC2, setresolu, sim_mat)
  true_countL[[i]] = list(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2)
  ## data convert
  numb_cond1 = simulation$dfRes %>% 
    filter(condition == "Cond1") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond2 = simulation$dfRes %>% 
    filter(condition == "Cond2") %>%
    group_by(clusterRes, batch) %>% 
    summarise(n = n()) %>% 
    pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
    column_to_rownames(var = "batch")
  numb_cond1[is.na(numb_cond1)] <- 0
  numb_cond2[is.na(numb_cond2)] <- 0
  conf.mat<-table(Idents(simulation$integratedSamples), simulation$trueLabels)
  true.conf<-t(t(conf.mat)/apply(conf.mat,2,sum))
  library(clue)
  order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
  seurat_countL[[i]] = list(cond1 = numb_cond1[,order2], cond2 = numb_cond2[,order2])
  L_sum1 = colSums(numb_cond1)
  L_sum2 = colSums(numb_cond2)
  decider = sum(L_sum1 > 10)+sum(L_sum2 > 10)
  if (decider == cluster_num*2) {   # if one cluster has least than 10 cells in one condition, then won't continue
    ## test
    ## DCATS---betabinLRT
    t1start = Sys.time()
    betabin_noBC = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = FALSE)
    timeL[1] = Sys.time() - t1start
    ##  DCATS---betabinLRT with Bias correction from similarity matrix
    ## KNN matrix
    graphs = simulation$integratedSamples@graphs$RNA_snn
    labels = Idents(simulation$integratedSamples)
    knn_mat = KNN_transition(graphs, labels)
    order1 = colnames(numb_cond1)
    simil_matK = knn_mat[order1, order1]
    simil_matU = get_similarity_mat(cluster_num, confuse_rate=0.1)
    betabin_wBC_K = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matK)
    betabin_wBC_U = betabinLRT_rw(as.matrix(numb_cond1), as.matrix(numb_cond2), bias_corr = TRUE, similarity_mat = simil_matU)
    ## DCATS---betabin with similarity matrix (backward-forward)
    t2start = Sys.time()
    betabin_wMK = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matK, n_samples = 100, binom_only = FALSE)
    timeL[2] = Sys.time() - t2start
    betabin_wMU = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 100, binom_only = FALSE)
    bin_wMK = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matK, n_samples = 100)
    bin_wMU = dcats_betabin(as.matrix(numb_cond1), as.matrix(numb_cond2), similarity_mat = simil_matU, n_samples = 100)
    ## Fisher's exact test
    t3start = Sys.time()
    fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
    timeL[3] = Sys.time() - t3start
    ## speckle
    t4start = Sys.time()
    speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
      dplyr::rename(cluster = BaselineProp.clusters,
                    speckle_pvals = FDR) %>%
      dplyr::select(cluster, speckle_pvals)
    timeL[4] = Sys.time() - t4start
    ## diffcyt
    t5start = Sys.time()
    diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$integratedSamples)
    timeL[5] = Sys.time() - t5start
    ## scDC
    t6start = Sys.time()
    res_scDC <- scDC_noClustering(cellTypes = simulation$dfRes$clusterRes, simulation$dfRes$batch, calCI = TRUE, calCI_method = c("percentile", "BCa", "multinom"),nboot = 1000, verbose = FALSE)
    res_GLM <- fitGLM(res_scDC, c(rep("cond1",rep1*cluster_num),rep("cond2",rep2*cluster_num)), pairwise = FALSE, fixed_only = TRUE, verbose = FALSE)
    timeL[6] = Sys.time() - t6start
    scDCRes_temp = summary(res_GLM$pool_res_fixed)
    scDCRes = scDCRes_temp[c(cluster_num+1,(dim(scDCRes_temp)[1]-cluster_num+2):dim(scDCRes_temp)[1]),]
    ## results
    cluster_map = data.frame(originLab = order2, cluster = c("A", "B", "C")) %>% 
      arrange(originLab) %>% 
      mutate(truth = c("N", "P", "P")) %>% 
      arrange(cluster) %>% 
      dplyr::select(-originLab)
    all_res = cluster_map %>% 
      mutate(betabin_noBC_pvals = betabin_noBC$pvals,
             betabin_wBCK_pvals = betabin_wBC_K$pvals,
             betabin_wBCU_pvals = betabin_wBC_U$pvals,
             betabin_wMK_pvals = betabin_wMK$pvals,
             betabin_wMU_pvals = betabin_wMU$pvals,
             bin_wMK_pvals = bin_wMK$pvals,
             bin_wMU_pvals = bin_wMU$pvals,
             fisher_pvals = fisher_pvals,
             scDC_pvals = scDCRes$p.value) %>%
      merge(speckleRes, by = "cluster") %>% 
      merge(diffcytP, by = "cluster")
    simulationDF = rbind(simulationDF, all_res)
    time[i,] = timeL
  }
}

## send email after finishing
sendEmail("Simulation is done!!")

colnames(time) = c("DCATS_wtoM", "DCATS_wM", "fisher", "speckle", "diffcyt", "scDC")
save(simulationDF, time, file = "./data/simulationDF/repplicates3&2_con50K_mis1.RData")
load("./data/simulationDF/repplicates3&2_con50K_mis1.RData")
head(simulationDF)
```

```{r, message=FALSE}
library(pROC)
methods = colnames(simulationDF)[3:13]
roc_rose <- plot(roc(simulationDF$truth, simulationDF[,3]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7, print.auc.x = .6, col = 1)
graphics::text(0.1, 0.69, paste(methods[1]), col=1)
for (i in 2:11){
  roc_rose <- plot(roc(simulationDF$truth, simulationDF[,i+2]), legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7-(i-1)*0.07, print.auc.x = .6, col = i, add = TRUE)
  graphics::text(0.1, 0.69-(i-1)*0.07, paste(methods[i]), col=i)
}

print("Time")
apply(na.omit(time), 2, mean)
```

```{r}
simulationRes = simulationDF %>% 
  mutate(truth = ifelse(truth == "P", 1, 0),
         betabin_noBC_Res = ifelse(betabin_noBC_pvals < 0.05, 1, 0),
         betabin_wBCK_Res = ifelse(betabin_wBCK_pvals < 0.05, 1, 0),
         betabin_wBCU_Res = ifelse(betabin_wBCU_pvals < 0.05, 1, 0),
         betabin_wMK_Res = ifelse(betabin_wMK_pvals < 0.05, 1, 0),
         betabin_wMU_Res = ifelse(betabin_wMU_pvals < 0.05, 1, 0),
         bin_wMK_Res = ifelse(bin_wMK_pvals < 0.05, 1, 0),
         bin_wMU_Res = ifelse(bin_wMU_pvals < 0.05, 1, 0),
         fisher_Res = ifelse(fisher_pvals < 0.05, 1, 0),
         scDC_Res = ifelse(scDC_pvals < 0.05, 1, 0),
         speckle_Res = ifelse(speckle_pvals < 0.05, 1, 0),
         diffcyt_Res = ifelse(diffcyt_pvals < 0.05, 1, 0))

for (i in 14:24){
  simulationRes[,i] = (simulationRes[,i] - simulationRes$truth) %>% 
    abs()
}

print("errorRate0.05")
errorRate = colSums(simulationRes[,14:24])/dim(simulationRes[,14:24])[1]
errorRate[order(errorRate)]
```

