---
title: "Test Seurat"
author: "Xinyi Lin"
date: "10/19/2020"
output: html_document
---

When simulate negative senario, we find out that Seurat tend to mark 'batch' and 'normal' with equal cell pattern. In this file, I want to test whether it is true and how to avoid it.

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
```

```{r}
source("functions.r")
```

Example:

```{r}
set.seed(123)
probNor = c(0.52, 0.11, 0.20, 0.01, 0.01, 0.15)
probMut = c(0.52, 0.11, 0.20, 0.01, 0.01, 0.15)
setresolu = 0.15
batch_size = 10000
de_prob = c(0.15, 0.40, 0.02, 0.14, 0.02, 0.17)
```

```{r}
HCCparams = readRDS("./data/HCCparams.rds")
sim_list = simualtionRWD(probNor, probMut, de_prob, batch_size, params = HCCparams)
#integratedSamples = runSeurat(sim_list, batch_size, setresolu)
#saveRDS(integratedSamples, "./data/integratedSamples_HCC6.rds")
#sendEmail("Seurat is done!")
integratedSamples = readRDS("./data/integratedSamples_HCC6.rds")
conf.mat<-table(Idents(integratedSamples), sim_list$origLabels)
print(conf.mat)
plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
print(plot)
```

```{r,warning=FALSE, message=FALSE}
library(future)
# check the current active plan
plan()
```

```{r}
# change the current plan to access parallelization
plan("multiprocess", workers = 4)
plan()
options(future.globals.maxSize = 2000 * 1024^2)
```

## Trail 1

Use HCC params with 6 clusters and change the order and name of Mut1, Mut2, Mut3, Nor1, Nor2, Nor3.

```{r}
set.seed(123)
probNor = c(0.57, 0.11, 0.31, 0.01)
probMut = c(0.57, 0.11, 0.31, 0.01)
setresolu = 0.08
batch_size = 1000
de_prob = c(0.15, 0.40, 0.02, 0.14)
```

```{r,eval=FALSE}
HCCparams = readRDS("./data/HCCparams.rds")
sim_list = simualtionRWD(probNor, probMut, de_prob, batch_size, params = HCCparams)

# set input
simNor_mat = sim_list$simNor_mat
simMut_mat = sim_list$simMut_mat
batchNor = sim_list$batchNor %>% 
  plyr::mapvalues(from = c("Nor1", "Nor2", "Nor3"), to = c("Sa", "Sc", "Sb")) # change name
batchMut = sim_list$batchMut%>% 
  plyr::mapvalues(from = c("Mut1", "Mut2", "Mut3"), to = c("Se", "Sf", "Sg"))
  
# pre-process
seuratNor <- CreateSeuratObject(counts = simNor_mat, project="Splatter")
seuratNor <- AddMetaData(object = seuratNor, metadata = batchNor, col.name = 'batch')
seuratNor <- AddMetaData(object = seuratNor, metadata = rep("Normal", batch_size*3), col.name = 'condition')
seuratMut <- CreateSeuratObject(counts = simMut_mat, project="Splatter")
seuratMut <- AddMetaData(object = seuratMut, metadata = batchMut, col.name = 'batch')
seuratMut <- AddMetaData(object = seuratMut, metadata = rep("Mutate", batch_size*3), col.name = 'condition')
  
listNor = SplitObject(seuratNor, split.by = "batch")
listMut = SplitObject(seuratMut, split.by = "batch")
listSamples = c(listNor, listMut)
listSamples = listSamples[c("Sa", "Sb", "Sc", "Se", "Sf", "Sg")] # change order


# log-normalization and identify variable features
for (i in 1:length(listSamples)) {
  listSamples[[i]]@meta.data$condition = NULL
  listSamples[[i]] <- NormalizeData(listSamples[[i]], verbose = FALSE)
  listSamples[[i]] <- FindVariableFeatures(listSamples[[i]], selection.method = "vst", 
                                             nfeatures = 2000, verbose = FALSE)
}
  
# integrate all batches
anchors <- FindIntegrationAnchors(object.list = listSamples, dims = 1:30, verbose = FALSE)
integratedSamples <- IntegrateData(anchorset = anchors, dims = 1:30, verbose = FALSE)
DefaultAssay(integratedSamples) <- "integrated"

# clustering
integratedSamples <- ScaleData(integratedSamples, verbose = FALSE)
integratedSamples <- RunPCA(integratedSamples, npcs = 30, verbose = FALSE)
integratedSamples <- FindNeighbors(integratedSamples, dims = 1:5, verbose = FALSE)
integratedSamples <- FindClusters(integratedSamples, resolution = setresolu, algorithm=2, verbose = FALSE)
integratedSamples <- RunUMAP(integratedSamples, reduction = "pca", dims = 1:30, verbose = FALSE)
  
# change labels to A, B, C
integratedSamples@active.ident = integratedSamples@active.ident %>% 
  plyr::mapvalues(from = c("0", "1", "2", "3", "4", "5"), to = c("A", "B", "C", "D", "E", "F"))


saveRDS(integratedSamples, "./data/integratedSamples_HCC6_test.rds")
sendEmail("Seurat is done!")
```

```{r}
integratedSamples = readRDS("./data/integratedSamples_HCC6_test.rds")
conf.mat<-table(Idents(integratedSamples), sim_list$origLabels)
print(conf.mat)
plot = DimPlot(integratedSamples, ncol = 3, reduction = "umap", split.by = "batch") + ggtitle("Cluster Results of Different Clusters in Different Samples")
print(plot)
```

We can find that splatter simulate very similar cells in corresponding batch?