---
title: "Test AUC&other"
author: "Xinyi Lin"
date: "2/22/2021"
output: html_document
---

This file is used to test whether the evaluation process has problems

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
source("functionsV2.r")
```

```{r}
prop_pst = 0.9
sample_size = 1000
```

```{r}
set.seed(123)
truth = rep("N", sample_size)
indexRep = sample(1:sample_size, prop_pst * sample_size)
truth[indexRep] = "P"
good_pred = rep(NA, sample_size)
good_pred[indexRep] = runif(length(indexRep), 0, 0.05)
good_pred[-indexRep] = runif(sample_size-length(indexRep), 0.05, 1)
bad_pred = runif(sample_size, 0, 1)
```

```{r}
library(pROC)
rocG = roc(truth, good_pred)
roc_rose <- plot(rocG, legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7, print.auc.x = .5, col = 1)
graphics::text(0.1, 0.69, paste("good_pred"), col=1)
rocB = roc(truth, bad_pred)
roc_rose <- plot(rocB, legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7, print.auc.x = .5, col = 1)
graphics::text(0.1, 0.69, paste("bad_pred"), col=1)
```

```{r}
getROC(truth = truth, pred = good_pred)$plot
getROC(truth = truth, pred = bad_pred)$plot
```

```{r}
set.seed(123)
truth = rep("N", sample_size)
indexRep = sample(1:sample_size, prop_pst * sample_size)
truth[indexRep] = "P"
good_pred = rep(NA, sample_size)
#good_pred[indexRep] = runif(length(indexRep), 0, 0.05)
#good_pred[-indexRep] = runif(sample_size-length(indexRep), 0.05, 1)
good_pred[indexRep] = runif(length(indexRep), 0.05, 1)
good_pred[-indexRep] = runif(sample_size-length(indexRep), 0, 0.05)
bad_pred = runif(sample_size, 0, 1)
```

```{r}
library(pROC)
rocG = roc(truth, good_pred)
roc_rose <- plot(rocG, legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7, print.auc.x = .5, col = 1)
graphics::text(0.1, 0.69, paste("good_pred"), col=1)
rocB = roc(truth, bad_pred)
roc_rose <- plot(rocB, legacy.axes = TRUE, print.auc = TRUE, print.auc.y = .7, print.auc.x = .5, col = 1)
graphics::text(0.1, 0.69, paste("bad_pred"), col=1)
```

```{r}
# function 13: plot ROC plot
getROC_rv = function(truth, pred){
  ## sensitivity and specificity
  library(pROC)
  library(ggplot2)
  roc = roc(truth, pred, quiet = TRUE)
  thresholds = c(0, pred+0.0001)
  sensitivity = rep(NA, length(thresholds))
  specificity = rep(NA, length(thresholds))
  index = 1:length(truth)
  TP = rep(NA, length(thresholds))
  TN = rep(NA, length(thresholds))
  FP = rep(NA, length(thresholds))
  FN = rep(NA, length(thresholds))
  for (j in 1:length(thresholds)) {
    #pred_res = ifelse(pred < thresholds[j], "P", "N")
    pred_res = ifelse(pred > thresholds[j], "P", "N")
    TP[j] <- sum(pred_res=="P"&truth=="P")
    TN[j] <- sum(pred_res=="N"&truth=="N")
    FP[j] <- sum(pred_res=="P"&truth=="N")
    FN[j] <- sum(pred_res=="N"&truth=="P")
    sensitivity[j] = TP[j]/(TP[j]+FN[j])
    specificity[j] = TN[j]/(TN[j]+FP[j])
  }
  eval = data.frame(thresholds = thresholds, TP = TP, TN = TN, FP = FP, FN = FN)
  df = data.frame(sensitivity = sensitivity, specificity = specificity, x = 1-specificity) %>% 
    arrange(x)
  ## plot
  plot = df %>% 
    ggplot(aes(x = x, y = sensitivity)) +
    geom_point() + 
    geom_abline(slope=1)
  ## auc
  auc = 0
  for (n in 2:length(thresholds)){
    subArea = (df$sensitivity[n-1]+df$sensitivity[n])*(df$x[n]-df$x[n-1])/2
    auc = auc + subArea
  }
  return(list(plot = plot, auc = auc, df = df, eval = eval, rocDF = data.frame(sensitivity = roc$sensitivities, specificity = roc$specificities)))
}
```

```{r}
getROC_rv(truth = truth, pred = good_pred)$plot
getROC_rv(truth = truth, pred = bad_pred)$plot
```

## test on simulation data

```{r}
cell_pool = "mis1"  # cell pool used, can be selected from ("mis1", "discrete", "realWorld")
cluster_num = 3  # numbers of clusters
concentration = 50 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.4
rep1 = 3
rep2 = 2
simulation_times = 50
sample_size1 = 700
sample_size2 = 2500
more_negative = "_pN"
```

```{r}
file_name = str_c("./data/simulationRES/repplicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, ".RData")
load(file_name)
```

```{r}
res = getROC(simulationDF$truth, simulationDF$betabin_noBC_pvals)
res$plot
```

```{r}
methods = colnames(simulationDF)[3:dim(simulationDF)[2]] %>% str_remove("_pvals")
auc = rep(NA, length(methods))
for (i in 3:dim(simulationDF)[2]){
  res = getROC(simulationDF$truth, simulationDF[,i])
  res$plot %>% print()
  res$eval %>% print()
  auc[i-2] = res$auc
  
}
data.frame(method = methods, auc = auc) %>% arrange(auc)
```

```{r}
cell_pool = "mis1"  # cell pool used, can be selected from ("mis1", "discrete", "realWorld")
cluster_num = 7  # numbers of clusters
concentration = 70 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.4
rep1 = 3
rep2 = 2
simulation_times = 50
sample_size1 = 700
sample_size2 = 2500
more_negative = "_pN"
```

```{r}
file_name = str_c("./data/simulationRES/replicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, ".RData")
load(file_name)
```

```{r}
methods = colnames(simulationDF)[3:dim(simulationDF)]
for (i in 3:dim(simulationDF)[2]){
  res = getROC(simulationDF$truth, simulationDF[,i])
  res$plot %>% print()
  res$eval %>% print()
}
```

```{r}
simulationDF %>% 
  mutate(simulationID = rep())
```

