---
title: "test_milo"
author: "Xinyi Lin"
date: "10/14/2021"
output: html_document
---

```{r}
library(miloR)
library(SingleCellExperiment)
library(scater)
library(scran)
library(tidyverse)
library(patchwork)
library(Seurat)
library(Matrix)
```

## real-world data 1 - Experiment 7

```{r}
exp7_data <- read.csv("./data/real_world/Exp7_Adam_2017/celltypelabels_Haber.txt", sep="") %>% 
  rownames_to_column("cell") %>% 
  separate(cell, c("batch", "barcode", "condition", "clusterRes"), sep = "_") 

head(exp7_data)
summary(exp7_data)

exp7_data %>% 
  group_by(batch, condition) %>% 
  summarise(n = n())
```

```{r}
geneExpM <- read.delim("./data/real_world/Exp7_Adam_2017/GSE92332_SalmHelm_UMIcounts.txt", header=TRUE)
seuratObj <- CreateSeuratObject(counts = geneExpM, project="Exp7")
exp7_sce <- as.SingleCellExperiment(seuratObj)
exp7_milo <- Milo(exp7_sce)
```

Milo part

```{r}
exp7_milo <- buildGraph(exp7_milo, k = 10, d = 30)
exp7_milo <- makeNhoods(exp7_milo, prop = 0.1, k = 10, d=30, refined = TRUE)
exp7_milo <- countCells(exp7_milo, meta.data = exp7_data, sample="condition")
head(nhoodCounts(exp7_milo))
```

```{r}
exp7_milo <- calcNhoodDistance(exp7_milo, d=30)
da_results <- testNhoods(exp7_milo, design = ~ condition, design.df = exp7_data)
```

## real-world data 5: Exp6-demuxlet

### store data

```{r}
exp6_clusterInfo = read.delim("./data/real_world/Exp6_Kang/GSE96583_batch2.total.tsne.df.tsv") %>% 
  dplyr::rename(clusterRes = cell, condition = stim) %>% 
  rownames_to_column("cell") %>% 
  filter(!is.na(clusterRes))
head(exp6_clusterInfo)
exp6_clusterInfo %>% group_by(condition, clusterRes) %>% 
  summarise(n = n())
## check whether exist duplicate barcode -> no
exp6_clusterInfo %>% 
  group_by(cell) %>% 
  summarise(n = n()) %>% 
  filter(n > 1)
```

```{r}
matrix1 = readMM(gzfile("./data/real_world/Exp6_Kang/GSM2560248_2.1.mtx.gz")) %>% 
  as.matrix()
matrix2 = readMM(gzfile("./data/real_world/Exp6_Kang/GSM2560249_2.2.mtx.gz")) %>% 
  as.matrix()
```

```{r}
data_dir1 = "./data/real_world/Exp6_Kang/GSM2560248"
list.files(data_dir1) # Should show barcodes.tsv, genes.tsv, and matrix.mtx
expression_matrix1 <- Read10X(data.dir = data_dir1)
seuratObj1 = CreateSeuratObject(counts = expression_matrix1)
seuratObj1 = AddMetaData(object = seuratObj1, metadata = rep("ctrl", dim(seuratObj1)[2]), col.name = 'sample')

data_dir2 = "./data/real_world/Exp6_Kang/GSM2560249"
list.files(data_dir2) # Should show barcodes.tsv, genes.tsv, and matrix.mtx
expression_matrix2 <- Read10X(data.dir = data_dir2)
seuratObj2 = CreateSeuratObject(counts = expression_matrix2)
seuratObj2 = AddMetaData(object = seuratObj2, metadata = rep("stim", dim(seuratObj2)[2]), col.name = 'sample')
```

```{r}
seuratObjL = c(sub1 = seuratObj1, sub2 = seuratObj2)
```

```{r}
anchors <- FindIntegrationAnchors(object.list = seuratObjL, dims = 1:30)
seurat_intg <- IntegrateData(anchorset = anchors, dims = 1:30)
seurat_intg <- ScaleData(seurat_intg)
seurat_intg <- RunPCA(seurat_intg, npcs = 30, verbose = FALSE)
```

```{r}
ctrl_repInfo <- read.delim("./data/real_world/Exp6_Kang/ye1.ctrl.8.10.sm.best")
stim_repInfo <- read.delim("./data/real_world/Exp6_Kang/ye2.stim.8.10.sm.best")
head(ctrl_repInfo)
head(stim_repInfo)

exp6_repInfo = rbind(ctrl_repInfo, stim_repInfo) %>% 
  dplyr::rename(cell = BARCODE, batch = BEST) %>% 
  filter(str_detect(batch, 'SNG')) %>% 
  dplyr::select(cell, batch)
head(exp6_repInfo)
```

```{r}
exp6_meta = data.frame(cell = str_replace(names(seurat_intg$orig.ident), "_[12]", "")) %>% 
  inner_join(exp6_clusterInfo) %>%
  inner_join(exp6_repInfo) %>% 
  mutate(batch = str_c(condition, batch)) %>% 
  dplyr::select(-cluster, -multiplets, -tsne1, -tsne2, -ind, -cell)

exp6_meta[cellID,]
```

```{r}
exp6_sce <- as.SingleCellExperiment(seurat_intg)
exp6_milo <- Milo(exp6_sce)
```

```{r}
exp6_milo <- buildGraph(exp6_milo, k = 10, d = 30)
exp6_milo <- makeNhoods(exp6_milo, prop = 0.1, k = 10, d=30, refined = TRUE)
exp6_milo <- countCells(exp6_milo, meta.data = seurat_intg@meta.data, sample="sample")
head(nhoodCounts(exp6_milo))
```

```{r}
exp7_milo <- calcNhoodDistance(exp7_milo, d=30)

da_results <- testNhoods(exp7_milo, design = ~ sample, design.df = seurat_intg@meta.data)
```

## Simulation

## Add simple gene expression information

```{r, message=FALSE, warning=FALSE}
library(Seurat)
library(SeuratWrappers)
library(speckle)
library(DCATS)
library(ggplot2)
library(tidyverse)
library(diffcyt)
library(MCMCpack)
#library(scdney)
library(scDC)
library(tidymodels)  ## for DCATS
library(miloR)
library(SingleCellExperiment)
```

```{r}
cluster_num = 12  # numbers of clusters
concentration = 100 # indicate how simulated proportion far away from true, the larger the closer
setresolu = 0.7
rep1 = 3
rep2 = 3
simulation_times = 30
sample_size1 = 1500
sample_size2 = 2500
cell_pool = "splatter"  # cell pool used, can be selected from ("SPAR", "splatter", "realWorld")
more_negative = ""
```

```{r}
if(cluster_num == 8){
  probC1 = c(rep(0.1, 6), 0.2, 0.2)  # True proportions
  probC2 = c(rep(0.1, 3), 0.05, 0.15, 0.2, 0.2, 0.1)
  truthRes = c(rep("N", 3), rep("P", 3), "N", "P")
} else if (cluster_num == 10){
  probC1 = c(rep(0.1, 5), 0.05, 0.05, 0.05, 0.2, 0.15)  # True proportions
  probC2 = c(rep(0.1, 10))
  truthRes = c(rep("N", 5), rep("P", 5))
} else if (cluster_num == 12){
  probC1 = c(rep(0.1, 4), 0.05, 0.05, 0.05, 0.15, 0.05, 0.05, 0.1, 0.1)  # True proportions
  probC2 = c(rep(0.1, 8), rep(0.05, 4))
  truthRes = c(rep("N", 4), rep("P", 4), "N", "N", "P", "P")
} else {
  print("Not pre-set clutser number")
}
```

```{r, message=FALSE, warning=FALSE}
source("functionsV2.r")
source("glm.R")     # for scDC
options(future.globals.maxSize = 15000 * 1024^2)
```

```{r}
if (cell_pool == "splatter"){
  load(str_c("D:/#Data/DCATS/cells_pool", as.character(cluster_num), "_splatter.RData"))
  #load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_splatter.RData"))
} else if (cell_pool == "SPAR") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_SPARSim.RData"))
  
} else if (cell_pool == "realWorld") {
    load(str_c("D:/Data/DCATS/cells_pool", as.character(cluster_num), "_realWorld.RData"))
}
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
## output data
clusterDF = data.frame()  # data frame to store test result
nhoodDF = data.frame()  # data frame to store test result
time = matrix(NA, nrow = simulation_times, ncol = 8) # matrix contains time for each test need in each simulation and time need to calculate svm/rf matrix
true_countL = vector(mode = "list", length = simulation_times) # list contains the count table of each true cluster
seurat_countL = vector(mode = "list", length = simulation_times) # list contains the count table of each cluster defined by seurat
knn_matrixL = vector(mode = "list", length = simulation_times) # list contains the knn matrix getting from each simulation
true_matrixL = vector(mode = "list", length = simulation_times) # list contains the true similarity matrix getting from each simulation
rf_matrixL = vector(mode = "list", length = simulation_times) # list contains the knn matrix getting from each simulation
svm_matrixL = vector(mode = "list", length = simulation_times) # list contains the true similarity matrix getting from each simulation

set.seed(1)
for (sim in 1:simulation_times){
  print(sim)
  timeL = rep(NA, 8) # DCATS w/wto similarity matrix, fisher, speckle, diffcyt, scDC
  ## simulation
  #simulation = simulator_fastMNN(totals1 = runif(rep1, sample_size1, sample_size2), totals2 = runif(rep2, sample_size1, sample_size2), probC1, probC2, setresolu, sim_mat)
  simulation = simulator_noInt(totals1 = runif(rep1, sample_size1, sample_size2), totals2 = runif(rep2, sample_size1, sample_size2), probC1, probC2, setresolu, sim_mat)
  if (is.na(simulation)[1] == FALSE){
    true_countL[[sim]] = c(cond1 = simulation$numb_cond1, cond2 = simulation$numb_cond2)
    
    ## data convert
    numb_cond1 = simulation$dfRes %>% 
      filter(condition == "Cond1") %>%
      group_by(clusterRes, batch) %>% 
      summarise(n = n()) %>% 
      pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
      column_to_rownames(var = "batch")
    numb_cond2 = simulation$dfRes %>% 
      filter(condition == "Cond2") %>%
      group_by(clusterRes, batch) %>% 
      summarise(n = n()) %>% 
      pivot_wider(names_from = "clusterRes", values_from = "n") %>% 
      column_to_rownames(var = "batch")
    numb_cond1[is.na(numb_cond1)] <- 0
    numb_cond2[is.na(numb_cond2)] <- 0
    conf.mat <- table(simulation$trueLabels, Idents(simulation$integratedSamples))
    true.conf <- conf.mat/rowSums(conf.mat)
    
    #print(numb_cond1)
    #print(numb_cond2)
    
    library(clue)
    order2 = as.vector(solve_LSAP(true.conf, maximum = TRUE))
    L_sum1 = colSums(numb_cond1)
    L_sum2 = colSums(numb_cond2)
    decider = sum(L_sum1 > 10)+sum(L_sum2 > 10)
    if (decider == cluster_num*2) {   # if one cluster has least than 10 cells in one condition, then won't continue
      seurat_countL[[sim]] = list(cond1 = numb_cond1[,order2], cond2 = numb_cond2[,order2])
      
      ## Get matrices
      ### KNN matrix
      graphs = simulation$integratedSamples@graphs$RNA_snn
      labels = Idents(simulation$integratedSamples)
      knn_mat = knn_simMat(graphs, labels)
      order1 = colnames(numb_cond1)
      simil_matK = knn_mat[order1, order1]
      knn_matrixL[[sim]] = simil_matK
      ### True matrix
      simil_matT = true.conf[,order2]
      true_matrixL[[sim]] = simil_matT
      ### Uniform matrix
      simil_matU = create_simMat(cluster_num, confuse_rate=0.1)
      ### svm&rf
      mlDF = simulation$integratedSamples@reductions$pca@cell.embeddings %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("cellID") %>% 
        merge(simulation$dfRes, by = "cellID") %>% 
        dplyr::select(-cellID)
      set.seed(123)
      simil_matSVM = svm_simMat(mlDF)
      svm_matrixL[[sim]] = simil_matSVM
      print(simil_matSVM)
      
      ## Test
      ### DCATS---betabinLRT
      sim_count = rbind(numb_cond1, numb_cond2) %>% as.matrix()
      sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
      t1start = Sys.time()
      betabin_null = dcats_GLM(sim_count, sim_design)
      timeL[1] = Sys.time() - t1start
      ###  DCATS---betabinLRT with Bias correction from similarity matrix
      phi = getPhi(sim_count, sim_design)
      estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi)
      numb_cond1 = numb_cond1 %>% as.matrix()
      numb_cond2 = numb_cond2 %>% as.matrix()
      ## KNN
      numb_cond1BC = numb_cond1
      numb_cond2BC = numb_cond2
      for (i in seq_len(nrow(numb_cond1))) {
        numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) * multinom_EM(numb_cond1[i, ], simil_matK, verbose = FALSE)$mu
        numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])}
      for (i in seq_len(nrow(numb_cond2))) {
        numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) * multinom_EM(numb_cond2[i, ], simil_matK, verbose = FALSE)$mu
        numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])}
      countBC_mat = rbind(numb_cond1BC, numb_cond2BC)
      wtoPhi_emK = dcats_GLM(countBC_mat, sim_design)
      estPhi_emK = dcats_GLM(countBC_mat, sim_design, fix_phi = phi)
      ## Uniform
      numb_cond1BC = numb_cond1
      numb_cond2BC = numb_cond2
      for (i in seq_len(nrow(numb_cond1))) {
        numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) * multinom_EM(numb_cond1[i, ], simil_matU, verbose = FALSE)$mu
        numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])}
      for (i in seq_len(nrow(numb_cond2))) {
        numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) * multinom_EM(numb_cond2[i, ], simil_matU, verbose = FALSE)$mu
        numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])}
      countBC_mat = rbind(numb_cond1BC, numb_cond2BC) %>% as.matrix()
      wtoPhi_emU = dcats_GLM(countBC_mat, sim_design)
      estPhi_emU = dcats_GLM(countBC_mat, sim_design, fix_phi = phi)
      ## True
      numb_cond1BC = numb_cond1
      numb_cond2BC = numb_cond2
      for (i in seq_len(nrow(numb_cond1))) {
        numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) * multinom_EM(numb_cond1[i, ], simil_matT, verbose = FALSE)$mu
        numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])}
      for (i in seq_len(nrow(numb_cond2))) {
        numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) * multinom_EM(numb_cond2[i, ], simil_matT, verbose = FALSE)$mu
        numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])}
      countBC_mat = rbind(numb_cond1BC, numb_cond2BC) %>% as.matrix()
      wtoPhi_emT = dcats_GLM(countBC_mat, sim_design)
      estPhi_emT = dcats_GLM(countBC_mat, sim_design, fix_phi = phi)
      ## svm
      numb_cond1BC = numb_cond1
      numb_cond2BC = numb_cond2
      for (i in seq_len(nrow(numb_cond1))) {
        numb_cond1BC[i, ] <- sum(numb_cond1[i, ]) * multinom_EM(numb_cond1[i, ], simil_matSVM, verbose = FALSE)$mu
        numb_cond1BC[i, ] = ceiling(numb_cond1BC[i, ])}
      for (i in seq_len(nrow(numb_cond2))) {
        numb_cond2BC[i, ] <- sum(numb_cond2[i, ]) * multinom_EM(numb_cond2[i, ], simil_matSVM, verbose = FALSE)$mu
        numb_cond2BC[i, ] = ceiling(numb_cond2BC[i, ])}
      countBC_mat = rbind(numb_cond1BC, numb_cond2BC) %>% as.matrix()
      wtoPhi_emSVM = dcats_GLM(countBC_mat, sim_design)
      estPhi_emSVM = dcats_GLM(countBC_mat, sim_design, fix_phi = phi)
      
      ## Fisher's exact test
      t3start = Sys.time()
      fisher_pvals = getFisher(as.matrix(numb_cond1), as.matrix(numb_cond2))
      timeL[3] = Sys.time() - t3start
      ## speckle
      t4start = Sys.time()
      speckleRes = propeller(clusters = simulation$dfRes$clusterRes, sample = simulation$dfRes$batch, group = simulation$dfRes$condition) %>% 
        dplyr::rename(cluster = BaselineProp.clusters,
                      speckle_pvals = FDR) %>%
        dplyr::select(cluster, speckle_pvals)
      timeL[4] = Sys.time() - t4start
      ## diffcyt
      t5start = Sys.time()
      diffcytP = getDiffcyt(numb_cond1, numb_cond2, simulation$dfRes)
      timeL[5] = Sys.time() - t5start
      ## scDC
      t6start = Sys.time()
      res_scDC <- scDC_noClustering(cellTypes = simulation$dfRes$clusterRes, simulation$dfRes$batch, calCI = TRUE, calCI_method = c("percentile", "BCa", "multinom"),nboot = 1000, verbose = FALSE)
      res_GLM <- fitGLM(res_scDC, c(rep("cond1",rep1*cluster_num),rep("cond2",rep2*cluster_num)), pairwise = FALSE, fixed_only = TRUE, verbose = FALSE)
      timeL[6] = Sys.time() - t6start
      scDCRes_temp = summary(res_GLM$pool_res_fixed)
      scDCRes = scDCRes_temp[c(cluster_num+1,(dim(scDCRes_temp)[1]-cluster_num+2):dim(scDCRes_temp)[1]),]
      ## results
      cluster_map = data.frame(cluster = colnames(numb_cond1[,order2]), truth = truthRes) %>% 
        arrange(cluster)
      all_res = cluster_map %>% 
        mutate(betabin_null_pvals = as.vector(betabin_null$LRT_pvals),
               estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals),
               wtoPhi_emSVM_pvals = as.vector(wtoPhi_emSVM$LRT_pvals),
               estPhi_emSVM_pvals = as.vector(estPhi_emSVM$LRT_pvals),
               wtoPhi_emT_pvals = as.vector(wtoPhi_emT$LRT_pvals),
               estPhi_emT_pvals = as.vector(estPhi_emT$LRT_pvals),
               wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals),
               estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals),
               wtoPhi_emK_pvals = as.vector(wtoPhi_emK$LRT_pvals),
               estPhi_emK_pvals = as.vector(estPhi_emK$LRT_pvals),
               fisher_pvals = fisher_pvals,
               scDC_pvals = scDCRes$p.value) %>%
        merge(speckleRes, by = "cluster") %>% 
        merge(diffcytP, by = "cluster")
      clusterDF = rbind(clusterDF, all_res)
      ## milo
      clusterP = all_res %>% filter(truth == "P") %>% .$cluster
      milo_res = getMilo(simulation$integratedSamples)
      ## subset data
      subsetSamples = subset(simulation$integratedSamples, cells = names(milo_res$nhoodsID))
      subsetSamples = AddMetaData(object = subsetSamples, metadata = milo_res$nhoodsID[Cells(subsetSamples)], col.name = 'nhoods')
      ### Uniform matrix
      simil_matU = create_simMat(nrow(milo_res$da_results), confuse_rate=0.15)
      ## Test
      ### DCATS---betabinLRT
      sim_count = milo_res$counts %>% as.matrix() %>% t()
      sim_design = data.frame(condition = c(rep("g1", rep1), rep("g2", rep2)))
      betabin_null = dcats_GLM(sim_count, sim_design)
      ###  DCATS---betabinLRT with Bias correction from similarity matrix
      phi = getPhi(sim_count[,sample(1:ncol(sim_count), 20)], sim_design)
      estPhi_null = dcats_GLM(sim_count, sim_design, fix_phi = phi)
      wtoPhi_emU = dcats_GLM(sim_count, sim_design, similarity_mat = simil_matU)
      estPhi_emU = dcats_GLM(sim_count, sim_design, similarity_mat = simil_matU, fix_phi = phi)
      ## Fisher's exact test
      fisher_pvals = getFisher(sim_count[1:rep1,], sim_count[(rep1+1):(rep1+rep2),])
      ## speckle
      speckleRes = propeller(clusters = subsetSamples$nhoods, sample = subsetSamples$batch, group = subsetSamples$condition) %>% 
        dplyr::rename(Nhood = BaselineProp.clusters,
                      speckle_pvals = FDR) %>%
        dplyr::select(Nhood, speckle_pvals)
      posCluster = all_res %>% 
        filter(truth == "P") %>% 
        .$cluster
      all_res2 = milo_res$da_results %>% 
        mutate(truth = ifelse(ident %in% posCluster, "P", "N"),
               betabin_null_pvals = as.vector(betabin_null$LRT_pvals),
               estPhi_null_pvals = as.vector(estPhi_null$LRT_pvals),
               wtoPhi_emU_pvals = as.vector(wtoPhi_emU$LRT_pvals),
               estPhi_emU_pvals = as.vector(estPhi_emU$LRT_pvals),
               fisher_pvals = fisher_pvals,
               Nhood = str_c("hoods", Nhood)) %>%
        merge(speckleRes, by = "Nhood")
        nhoodDF = rbind(nhoodDF, all_res2)
    }
  }
}

## send email after finishing
#sendEmail('Simulation is done!!')
```


```{r}
file_name = str_c("D:/#Data/DCATS/simulation/replicates", as.character(rep1), "&", as.character(rep2), "_K", as.character(cluster_num), "_con", as.character(concentration), "_", cell_pool, more_negative, sample_size1, "&", sample_size2, "withMilo.RData")
colnames(time) = c("DCATS_wtoM", "DCATS_wM", "fisher", "speckle", "diffcyt", "scDC", "rfM", "svmM")
save(clusterDF, nhoodDF, time, true_countL, seurat_countL, knn_matrixL, true_matrixL, file = file_name)
head(nhoodDF, 15)
```

```{r}
load(file_name)
nhoodDF = nhoodDF %>% na.omit() %>% 
  dplyr::rename(milo_pvals = SpatialFDR)
methods = colnames(nhoodDF)[colnames(nhoodDF) %>% str_detect("_pvals")] %>% str_remove("_pvals")
numb_mthd = length(methods)
mcc = rep(NA, numb_mthd)
auc = rep(NA, numb_mthd)
prauc = rep(NA, numb_mthd)
sensitivity = rep(NA, numb_mthd)
specificity = rep(NA, numb_mthd)
precision = rep(NA, numb_mthd)
F1 = rep(NA, numb_mthd)
truth = nhoodDF$truth
select_col = colnames(nhoodDF)[colnames(nhoodDF) %>% str_detect("_pvals")]
for (i in 1:length(select_col)){
  auc[i] = getROC(nhoodDF$truth, nhoodDF[,select_col[i]])$auc
  pred = nhoodDF[,select_col[i]]
  if (i == 1) {pred_res = ifelse(pred < 0.1, "P", "N")}
  else {pred_res = ifelse(pred < 0.1, "P", "N")}
  TP <- sum(pred_res=="P"&truth=="P")
  TN <- sum(pred_res=="N"&truth=="N")
  FP <- sum(pred_res=="P"&truth=="N")
  FN <- sum(pred_res=="N"&truth=="P")
  truthN = TN + FP
  truthP = FN + TP
  predP = TP + FP
  predN = FN + TN
  sensitivity[i] = TP/truthP
  specificity[i] = TN/truthN
  precision[i] = TP/predP
  mcc[i] = sqrt(sensitivity[i]*specificity[i]*precision[i]*(TN/(TN+FN))) - sqrt((1-sensitivity[i])*(1-specificity[i])*(FN/predN)*(FP/predP))
  #mcc[i] = (TP*TN-FP*FN)/sqrt(predP*truthP*truthN*predN)
  F1[i] = 2*TP/(2*TP+FP+FN)
  prauc[i] = getPRC(nhoodDF$truth, nhoodDF[,select_col[i]])$prauc
  
}
res = data.frame(methods = methods, mcc = mcc, auc = auc, prauc = prauc, sensitivity = sensitivity, specificity = specificity, precision = precision, F1 = F1) %>% 
  arrange(desc(auc)) %>% 
  #filter(methods == "wtoPhi_fullK" | methods == "diffcyt" | methods == "speckle" | methods == "fisher" | methods == "scDC")
print(res)
```


```{r}
load(file_name)
nhoodDF_res = nhoodDF %>% 
  na.omit() %>% 
  mutate(milo_res = ifelse(SpatialFDR < 0.1, "P", "N"),
         betabin_null_res = ifelse(betabin_null_pvals < 0.1, "P", "N"),
         estPhi_null_res = ifelse(estPhi_null_pvals < 0.05, "P", "N"),
         wtoPhi_emU_res = ifelse(wtoPhi_emU_pvals < 0.05, "P", "N"),
         estPhi_emU_res = ifelse(estPhi_emU_pvals < 0.05, "P", "N"),
         fisher_res = ifelse(fisher_pvals < 0.05, "P", "N"),
         speckle_res = ifelse(speckle_pvals < 0.05, "P", "N")) %>% 
  pivot_longer(contains("_res"), names_to = "method", values_to = "res") %>% 
  group_by(truth, method, res) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n)) %>%
  dplyr::select(-n) %>% 
  pivot_wider(names_from = res, values_from = freq) %>% 
  mutate()
nhoodDF_res
```

